import type { Metadata, Viewport } from "next";
import { Oswald, DM_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Navigation } from "@/components/Navigation";
import { Toaster } from "@/components/ui/Toaster";
import { StructuredData } from "@/components/StructuredData";
import { Footer } from "@/components/Footer";
import { GoogleAnalytics } from "@/components/GoogleAnalytics";

// Athletic Editorial Typography
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  fallback: ["system-ui", "sans-serif"],
  display: "swap",
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  fallback: ["system-ui", "sans-serif"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  fallback: ["ui-monospace", "monospace"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "https://pitchrank.io"),
  title: {
    default: "PitchRank — Youth Soccer Rankings",
    template: "%s | PitchRank",
  },
  description: "Data-powered youth soccer team rankings and performance analytics. Compare U10-U18 boys and girls teams nationally and across all 50 states.",
  keywords: [
    "youth soccer rankings",
    "soccer team rankings",
    "youth soccer",
    "club soccer rankings",
    "soccer power rankings",
    "U10 soccer",
    "U12 soccer",
    "U14 soccer",
    "U16 soccer",
    "U18 soccer",
    "soccer analytics",
  ],
  authors: [{ name: "PitchRank" }],
  creator: "PitchRank",
  publisher: "PitchRank",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  icons: {
    icon: "/logos/favicon.ico",
    shortcut: "/logos/favicon.ico",
    apple: "/logos/pitchrank-symbol.svg",
  },
  alternates: {
    canonical: process.env.NEXT_PUBLIC_SITE_URL || "https://pitchrank.io",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "/",
    siteName: "PitchRank",
    title: "PitchRank — Youth Soccer Rankings",
    description: "Data-powered youth soccer team rankings and performance analytics. Compare U10-U18 boys and girls teams nationally and across all 50 states.",
    // OG image auto-generated by app/opengraph-image.tsx (1200x630 PNG)
  },
  twitter: {
    card: "summary_large_image",
    title: "PitchRank — Youth Soccer Rankings",
    description: "Data-powered youth soccer team rankings and performance analytics. Compare U10-U18 boys and girls teams nationally and across all 50 states.",
    // Twitter image auto-generated by app/opengraph-image.tsx
    creator: "@pitchrank",
    site: "@pitchrank",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: "#052E27", // Athletic Editorial dark green
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Structured Data for SEO */}
        <StructuredData />

        {/* Google Analytics */}
        <GoogleAnalytics measurementId={process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID} />
      </head>
      <body
        className={`${oswald.variable} ${dmSans.variable} ${jetbrainsMono.variable} antialiased transition-colors duration-300 ease-in-out flex flex-col min-h-screen`}
      >
        <Providers>
          <Navigation />
          <main className="flex-1 bg-background text-foreground">
            {children}
          </main>
          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
