-- Fix empty club_name fields
-- Generated by fix_missing_club_names.py
-- Total fixes: 742

-- AL: Alabama FC (2 teams)
UPDATE teams SET club_name = 'Alabama FC'
WHERE team_id_master IN ('413bd733-2b6b-4805-97ad-5fef6e0e4197', '83e836a1-4e60-45a6-83fe-614743371348');

-- AL: Auburn Soccer Club (2 teams)
UPDATE teams SET club_name = 'Auburn Soccer Club'
WHERE team_id_master IN ('8dc8e218-df87-4c14-a2ea-f0a861e18fd3', '44d5f9b1-c164-42bd-8157-6080a133a4dd');

-- AL: Homewood Soccer Club (2 teams)
UPDATE teams SET club_name = 'Homewood Soccer Club'
WHERE team_id_master IN ('9b58a65b-37d1-49bc-96bc-d8283d64296a', '7cc1078b-2d1d-4944-9e52-93924a443941');

-- AR: Advantage Academy (1 teams)
UPDATE teams SET club_name = 'Advantage Academy'
WHERE team_id_master IN ('79c29237-6069-4c95-aacc-fb973bf0c5ca');

-- AR: Arkansas Rising Soccer Club (1 teams)
UPDATE teams SET club_name = 'Arkansas Rising Soccer Club'
WHERE team_id_master IN ('f898c066-546d-4d7b-959f-5c94fefd18fc');

-- AR: Little Rock Rangers Academy (2 teams)
UPDATE teams SET club_name = 'Little Rock Rangers Academy'
WHERE team_id_master IN ('0dc31452-db6a-4627-84b6-acbd94b8dc0d', '516ef691-9964-4188-ad57-0192e2abf62b');

-- AR: NWA Dragons (2 teams)
UPDATE teams SET club_name = 'NWA Dragons'
WHERE team_id_master IN ('45a2de38-0ea2-4123-bbee-db197632325c', '441c026c-3833-4be5-8b0a-c71ab00e3216');

-- AR: Sporting Arkansas (1 teams)
UPDATE teams SET club_name = 'Sporting Arkansas'
WHERE team_id_master IN ('f453c1bf-2702-4944-9bcc-e90623a4e51c');

-- AR: Tigres Academy (1 teams)
UPDATE teams SET club_name = 'Tigres Academy'
WHERE team_id_master IN ('2e6cc317-c88f-4b4f-ab0a-fb26e7366714');

-- AZ: Amore Soccer (1 teams)
UPDATE teams SET club_name = 'Amore Soccer'
WHERE team_id_master IN ('21e78d96-dd7a-4027-9cfe-488a5fdac002');

-- CA: City SC (1 teams)
UPDATE teams SET club_name = 'City SC'
WHERE team_id_master IN ('25e43102-6aea-4239-bd94-d3a2f450d1f1');

-- CA: Clippers FC (1 teams)
UPDATE teams SET club_name = 'Clippers FC'
WHERE team_id_master IN ('f064b22b-49ee-4002-b87a-fe8521c21552');

-- CA: Eagles Soccer Club (1 teams)
UPDATE teams SET club_name = 'Eagles Soccer Club'
WHERE team_id_master IN ('005ca81f-94b8-40c5-b1c4-5decfb79aebf');

-- CA: Empire Surf (1 teams)
UPDATE teams SET club_name = 'Empire Surf'
WHERE team_id_master IN ('2d68dbf9-71d6-4e36-9add-9233b19b7c1f');

-- CA: FC Fresno Academy (3 teams)
UPDATE teams SET club_name = 'FC Fresno Academy'
WHERE team_id_master IN ('f7419165-6c10-4b3c-b2a9-f2f87f0f4fd7', 'd128db2d-31ed-44ce-9872-868ff414e85b', '182c70ae-c0bf-454c-8389-d441696dd2d2');

-- CA: LA Surf Soccer Club (1 teams)
UPDATE teams SET club_name = 'LA Surf Soccer Club'
WHERE team_id_master IN ('1db7e709-3f35-41c8-b806-cafce8c29268');

-- CA: Legends FC (SJ) (2 teams)
UPDATE teams SET club_name = 'Legends FC (SJ)'
WHERE team_id_master IN ('5e4a5eb0-b19f-4e5e-8235-8e9d04c2d11b', 'd78b9815-c205-47a8-81a8-d4acf2a78217');

-- CA: Rebels Soccer Club (2 teams)
UPDATE teams SET club_name = 'Rebels Soccer Club'
WHERE team_id_master IN ('6ccc3e61-4b93-4995-be1a-9b2c6ec19b77', 'f8f76422-b513-4437-a73e-48401d92097d');

-- CA: Santa Rosa United Soccer (1 teams)
UPDATE teams SET club_name = 'Santa Rosa United Soccer'
WHERE team_id_master IN ('d7a47749-a9a3-4486-8956-a639c4e67c85');

-- CA: Sdsc Surf (1 teams)
UPDATE teams SET club_name = 'Sdsc Surf'
WHERE team_id_master IN ('1fb639e0-1111-471e-9abb-8adae24e05c1');

-- CA: Sentinels Soccer Club (1 teams)
UPDATE teams SET club_name = 'Sentinels Soccer Club'
WHERE team_id_master IN ('f983e290-03f0-4615-86c1-8a43e7db8cad');

-- CA: So Cal Blues (1 teams)
UPDATE teams SET club_name = 'So Cal Blues'
WHERE team_id_master IN ('c655c1ca-4521-495e-9c07-c1de3ed68d23');

-- CA: Sporting California USA (6 teams)
UPDATE teams SET club_name = 'Sporting California USA'
WHERE team_id_master IN ('62272108-dcd1-46e4-9311-9d837e35be4a', 'a777f671-9b3b-4c38-924e-b63ce5e38189', 'c3ad7c84-233f-4f3b-a7a9-96b7f7600d84', '1474249f-104c-44f7-bff2-4a3bd2658a95', '198cc375-59cb-4e25-92d5-cdd73d82c262', '73b54c28-7a25-4f9e-869e-de2eb25c2456');

-- CA: West Coast FC (1 teams)
UPDATE teams SET club_name = 'West Coast FC'
WHERE team_id_master IN ('d07b7b37-1c57-4e7c-abf6-fa985ff2d9dd');

-- CO: ALBION SC Denver (2 teams)
UPDATE teams SET club_name = 'ALBION SC Denver'
WHERE team_id_master IN ('df15caf0-cf2a-480f-896d-44bcd015bc1c', '193c04c1-4091-4d35-a555-5b9335989043');

-- CO: Arsenal Colorado (2 teams)
UPDATE teams SET club_name = 'Arsenal Colorado'
WHERE team_id_master IN ('26de39b3-e63f-46e2-91d2-5cdbb3d12f66', '1102c5c5-55dc-47f2-b4b7-1c5ad239d995');

-- CO: Broomfield Soccer Club (1 teams)
UPDATE teams SET club_name = 'Broomfield Soccer Club'
WHERE team_id_master IN ('85d2c041-a410-45fe-883d-eff30ecb47f6');

-- CO: Colorado Rapids (2 teams)
UPDATE teams SET club_name = 'Colorado Rapids'
WHERE team_id_master IN ('a65befa9-6093-4503-b039-4bdd9f72f892', 'bb8a26fb-aebc-442a-aae0-dd4ffb7b654c');

-- CO: FC Brighton (1 teams)
UPDATE teams SET club_name = 'FC Brighton'
WHERE team_id_master IN ('e68b7a59-9f6c-4ffd-9a07-68206980266e');

-- CO: North Denver Rush (1 teams)
UPDATE teams SET club_name = 'North Denver Rush'
WHERE team_id_master IN ('5108d7cf-1d4f-4c99-98e0-569effc51318');

-- CO: Pueblo Rangers SC (2 teams)
UPDATE teams SET club_name = 'Pueblo Rangers SC'
WHERE team_id_master IN ('95078c4e-89e6-470b-95d8-4fe3086f0e44', 'd69ed84d-17cd-4e60-bea5-22d3e7f3f30b');

-- CO: Real Colorado (8 teams)
UPDATE teams SET club_name = 'Real Colorado'
WHERE team_id_master IN ('aab8e7c6-e2ab-45ed-9e33-da6be6787f93', 'f22e9286-09fa-4db2-8758-dcb8551abed8', '202d4c93-0148-4619-8382-7e431d8080c5', '67263318-ad10-4e8b-9802-4230cb60743e', 'a2459590-f336-4da3-9364-68afb2a4e767', 'ba743d36-653c-4226-b228-8f6f0f7cc4c4', 'b7ea9987-f1e0-4b79-94a4-481c88bb7744', '482d2803-cd05-48a8-b281-a4c01ba9c7b4');

-- CO: United Soccer Club CO (2 teams)
UPDATE teams SET club_name = 'United Soccer Club CO'
WHERE team_id_master IN ('ef049635-4c3a-46e5-ae0d-61e9ea6d3e70', '778d158b-30f3-45a2-a45e-2d32d7a92896');

-- CT: CFC South (1 teams)
UPDATE teams SET club_name = 'CFC South'
WHERE team_id_master IN ('ea49330c-3e56-4f59-a23d-23e646d41471');

-- CT: CT Rush (4 teams)
UPDATE teams SET club_name = 'CT Rush'
WHERE team_id_master IN ('f8f15e31-9b6f-4f43-840a-7f96003ce482', 'dd992602-87dd-4678-9958-6abdcea27a5a', '8d75047a-eeda-49e6-a3e6-c8e3e3a2009f', '69ea9834-470a-48f1-b025-8b770d5ebe24');

-- CT: Fair Play Soccer (1 teams)
UPDATE teams SET club_name = 'Fair Play Soccer'
WHERE team_id_master IN ('549f3a8f-6ced-461e-9ebe-246cdaed5207');

-- CT: Farmington SC (2 teams)
UPDATE teams SET club_name = 'Farmington SC'
WHERE team_id_master IN ('5266c3df-e1a8-4cdf-8f4f-3f127ecfdfe0', '980ce42f-3007-47d9-9326-932d381d3ae7');

-- CT: Glastonbury Football Club (2 teams)
UPDATE teams SET club_name = 'Glastonbury Football Club'
WHERE team_id_master IN ('fd7af785-cef4-4e99-9796-8e0f7108e5d5', 'c2747796-d870-44e4-a80e-2b6b6be4fdf5');

-- CT: New Canaan FC (1 teams)
UPDATE teams SET club_name = 'New Canaan FC'
WHERE team_id_master IN ('9cafc255-e8e7-44c8-b562-e5463d479ff8');

-- CT: New Fairfield Soccer Club (1 teams)
UPDATE teams SET club_name = 'New Fairfield Soccer Club'
WHERE team_id_master IN ('66d7e577-2f91-4f5c-8ac5-796f744f3dbc');

-- CT: Sporting CT (1 teams)
UPDATE teams SET club_name = 'Sporting CT'
WHERE team_id_master IN ('40f3aca2-7421-4a0a-820f-06c5946dbe46');

-- CT: West Hartford FC (2 teams)
UPDATE teams SET club_name = 'West Hartford FC'
WHERE team_id_master IN ('aa81f54f-b835-4d38-b468-2226efb93e91', '9cf729ff-29e8-4374-b589-5bc2edd1d74b');

-- CT: Westport Soccer Association (1 teams)
UPDATE teams SET club_name = 'Westport Soccer Association'
WHERE team_id_master IN ('cc9e55e2-8b99-4710-8c73-e3fa95d71ef9');

-- DE: Concord SA (3 teams)
UPDATE teams SET club_name = 'Concord SA'
WHERE team_id_master IN ('f1a54ede-bed3-4d37-8377-68d784900016', 'b2481a6d-0de4-4b4f-9b63-59a9184ac5df', '3195df3d-becd-4e12-afa4-ef53fae0c811');

-- DE: Sporting Athletic Club (3 teams)
UPDATE teams SET club_name = 'Sporting Athletic Club'
WHERE team_id_master IN ('44ea4e5e-c3e7-421b-a9e2-8f15afcd7730', 'cd462bd2-7c4a-4f2f-89bd-93c5366e2ed2', 'f4124c16-6949-4dd0-8e72-adbef5140f57');

-- FL: Arsenal Youth FC (2 teams)
UPDATE teams SET club_name = 'Arsenal Youth FC'
WHERE team_id_master IN ('0c22b6e2-67cf-4cf0-8d3a-7ac4e60f1492', 'c4789899-911b-484c-bda3-aa33d25dc507');

-- FL: Bayside Rush (2 teams)
UPDATE teams SET club_name = 'Bayside Rush'
WHERE team_id_master IN ('320ceec4-735b-4961-bcef-1962c66e1df3', '3594beee-0d64-4b27-a643-9ce1d1d99aca');

-- FL: Galacticos Soccer Academy (3 teams)
UPDATE teams SET club_name = 'Galacticos Soccer Academy'
WHERE team_id_master IN ('2185dddc-0bb2-421f-b6b8-754cc9464370', 'e1582c6e-a73f-4979-8d9d-2310c7ca5d24', '0a1ec14c-e6fc-4847-b574-143bc409d3e1');

-- FL: Naples United FC (6 teams)
UPDATE teams SET club_name = 'Naples United FC'
WHERE team_id_master IN ('1fc2ff56-a3da-46df-b2c1-d81bcaea1c39', '307a79bb-b2f5-412e-9232-3d1587176444', 'fc1a58fb-8aec-4672-8a39-876da5045409', 'b9ba74ac-268e-41db-b58c-1884997b2f28', '5b8adae5-4859-48cf-9fb8-93852e20265f', '969de838-01f1-48a5-af6b-7ecc078aaaf3');

-- FL: Sporting Tallahassee Soccer Academy (1 teams)
UPDATE teams SET club_name = 'Sporting Tallahassee Soccer Academy'
WHERE team_id_master IN ('bdbf8f06-3ac7-411d-9fc3-bd05bdeb5dba');

-- GA: AFC Lightning (1 teams)
UPDATE teams SET club_name = 'AFC Lightning'
WHERE team_id_master IN ('799fb087-b021-49d6-aa68-895bce380547');

-- GA: Athens United SA (1 teams)
UPDATE teams SET club_name = 'Athens United SA'
WHERE team_id_master IN ('f8b6f0f4-57ad-4b14-8d4b-8a739f5377fb');

-- GA: Atlanta Fire United (1 teams)
UPDATE teams SET club_name = 'Atlanta Fire United'
WHERE team_id_master IN ('0d30c0cd-c8f8-4c8f-9969-f6df952b12ff');

-- GA: Concorde Fire (1 teams)
UPDATE teams SET club_name = 'Concorde Fire'
WHERE team_id_master IN ('12a366ca-2779-45a3-9ad8-86b2a7228497');

-- GA: Georgia Storm Revolution (3 teams)
UPDATE teams SET club_name = 'Georgia Storm Revolution'
WHERE team_id_master IN ('f0d5b3c4-41bd-4888-a835-13da9644ca3d', '231d10a4-6ae8-4627-adea-c5fec2005748', '02777b9e-fe57-4920-9351-7baf6413a9fc');

-- GA: Grow Soccer Evolutions - 01 (2 teams)
UPDATE teams SET club_name = 'Grow Soccer Evolutions - 01'
WHERE team_id_master IN ('a2e1c68d-a4c4-44d7-94c8-9acd8e1aef50', '37320f26-0aff-4f4e-aeba-94728c22c642');

-- GA: Inter Atlanta FC (13 teams)
UPDATE teams SET club_name = 'Inter Atlanta FC'
WHERE team_id_master IN ('fdaa73bf-0a4f-4f8c-9b1a-0d4d8cce6900', 'fb95e075-a89b-4a80-90c1-d4424b8e6627', 'e157771a-401f-4329-8f43-2d292ef8e986', '271feb42-4d17-4176-9e16-c339a9627737', 'f33e7d48-a14e-4e3f-9faa-26d32b50392c', '6c0b7c08-f4b7-4d58-a735-32d5a58f5aa1', '74f6a217-afe4-45bd-b226-3d598cee1607', 'ad16de73-6c9a-4da6-9785-d795291b9fd6', '150458d4-2909-4976-9446-540dd0f60667', '97ee8103-8e4b-400c-ab56-b286a327e2b0', 'ca7f8670-a9fc-42b3-9af2-04ec7b298619', '9875cbea-336d-4359-9b6e-03378d6f0d83', '117e8dc3-f2b9-4d3f-adea-d268a2b5d2fa');

-- GA: TopHat (1 teams)
UPDATE teams SET club_name = 'TopHat'
WHERE team_id_master IN ('846cfe5e-d168-428a-874a-76f7f1954a85');

-- HI: Hawaii Rush (1 teams)
UPDATE teams SET club_name = 'Hawaii Rush'
WHERE team_id_master IN ('798a998d-5eca-4160-aec8-9c992bb5e417');

-- HI: Hawaii Soccer Academy (1 teams)
UPDATE teams SET club_name = 'Hawaii Soccer Academy'
WHERE team_id_master IN ('8ddf0f95-1c36-4484-8bc7-f66701988d77');

-- HI: Leahi Soccer Club (1 teams)
UPDATE teams SET club_name = 'Leahi Soccer Club'
WHERE team_id_master IN ('74776b73-c53f-4d41-a667-830cdb09b5b1');

-- HI: Lightning FC (1 teams)
UPDATE teams SET club_name = 'Lightning FC'
WHERE team_id_master IN ('1155e29c-88f2-4b6e-8a76-795a84117039');

-- IA: Apex Soccer Academy (1 teams)
UPDATE teams SET club_name = 'Apex Soccer Academy'
WHERE team_id_master IN ('e2b21182-8cd3-4766-a337-c9d3936ece05');

-- IA: DeWitt Soccer League (1 teams)
UPDATE teams SET club_name = 'DeWitt Soccer League'
WHERE team_id_master IN ('734bf9cb-7089-4fb5-907c-9ef202ea9fff');

-- IA: FC America (Ia) (1 teams)
UPDATE teams SET club_name = 'FC America (Ia)'
WHERE team_id_master IN ('0a1b3a26-9405-4bc3-9f26-cb9652f3dce1');

-- IA: Iowa Rush Soccer Club (3 teams)
UPDATE teams SET club_name = 'Iowa Rush Soccer Club'
WHERE team_id_master IN ('d7a2a57f-3544-447d-98bf-449e53db1389', '076d2ac8-21af-4596-a702-87fe5ac8e40e', '4e88e352-7e42-4ab7-975d-6e6ade5ad0fb');

-- IA: Iowa Storm Soccer Club (1 teams)
UPDATE teams SET club_name = 'Iowa Storm Soccer Club'
WHERE team_id_master IN ('68831102-5d45-4569-813b-f796bb8f3724');

-- IA: Iowa United (16 teams)
UPDATE teams SET club_name = 'Iowa United'
WHERE team_id_master IN ('70de5ee4-7ced-4589-85f0-38154b6832ce', '14035c9f-e7ec-4b25-93fa-dd55efdfedbf', '28d0f40c-85e4-406a-924e-cfb92d864890', '06da2317-1a45-4100-b274-d517b1f005ea', '77ad046f-4231-4636-9b72-67fa8e55cb16', '9009ec02-412c-4218-8e42-65463bb82a1e', 'eccabbc5-4a99-41f0-98e3-865bc6a5f0a6', '63002a9c-6baa-4a11-a781-f4da4cf50ad9', '8616241d-017f-4684-8c7d-4723723f3056', '7a99f3eb-70c4-43c3-979b-87103d2f3c1f', '6477fb51-0f7a-4400-9417-3ea10c9b701c', 'a28b9e18-5248-4286-add6-cd1a496b1947', 'afac2523-447b-4081-b192-4de01d5fee99', 'cc19f335-ea6b-4ad3-8a44-930f0ba9cb06', '34dc3fc3-5f83-431a-9dfb-0a0f91b43a64', '1b690a64-1e40-4187-bacb-5c5e9356dfc3');

-- ID: ALBION SC Idaho (1 teams)
UPDATE teams SET club_name = 'ALBION SC Idaho'
WHERE team_id_master IN ('814250ed-8549-4ed0-a299-2de1d0e20443');

-- ID: Global Sports Academy (1 teams)
UPDATE teams SET club_name = 'Global Sports Academy'
WHERE team_id_master IN ('75366e4c-491f-4e36-848a-f4f11b007046');

-- ID: Sun Valley Soccer Club (1 teams)
UPDATE teams SET club_name = 'Sun Valley Soccer Club'
WHERE team_id_master IN ('4777fc1b-b686-4ee8-b7e8-499888a374b4');

-- ID: Timberwolves Futbol Club (1 teams)
UPDATE teams SET club_name = 'Timberwolves Futbol Club'
WHERE team_id_master IN ('abb64ac7-9ba4-462a-8a68-ecd8b24b0c8d');

-- IL: Arlington Aces (3 teams)
UPDATE teams SET club_name = 'Arlington Aces'
WHERE team_id_master IN ('ff9090ec-2d63-48fa-87cf-da089e1e7a9c', '3388599c-ef10-40a4-bae6-494aee09d837', 'f8dbe6f4-c7bf-46f1-a2fb-1cbbe47001a1');

-- IL: Barca Academy Chicago (1 teams)
UPDATE teams SET club_name = 'Barca Academy Chicago'
WHERE team_id_master IN ('70de5884-037f-49d7-baaa-38895b56578b');

-- IL: Berber City FC (1 teams)
UPDATE teams SET club_name = 'Berber City FC'
WHERE team_id_master IN ('731c361d-47bf-4dae-9332-ce7b6f3273d4');

-- IL: Ceba United FC (1 teams)
UPDATE teams SET club_name = 'Ceba United FC'
WHERE team_id_master IN ('6fd7c4f7-0fe0-4f3a-b94b-37c7754d5f3d');

-- IL: Celtic FC Chicago (1 teams)
UPDATE teams SET club_name = 'Celtic FC Chicago'
WHERE team_id_master IN ('9a7fe856-cbba-4f39-b668-c445e280d16b');

-- IL: Chicago City Soccer Club (1 teams)
UPDATE teams SET club_name = 'Chicago City Soccer Club'
WHERE team_id_master IN ('d9555d9f-d503-4434-9af2-46b108845ded');

-- IL: Chicago Inferno (1 teams)
UPDATE teams SET club_name = 'Chicago Inferno'
WHERE team_id_master IN ('118b1a52-c250-46d2-b504-702429d7182f');

-- IL: Chicago Inter (2 teams)
UPDATE teams SET club_name = 'Chicago Inter'
WHERE team_id_master IN ('6d7fe2e3-12e9-460e-bacb-28e5d1c171a4', '96642feb-adb8-4e67-b8d6-f1561da8133e');

-- IL: Chicago Rush Soccer Club (1 teams)
UPDATE teams SET club_name = 'Chicago Rush Soccer Club'
WHERE team_id_master IN ('6bc99d66-dd61-4337-b8f9-821af2ae98b9');

-- IL: Chicago Soccer Academy (Csa) (1 teams)
UPDATE teams SET club_name = 'Chicago Soccer Academy (Csa)'
WHERE team_id_master IN ('7238c736-45e9-4253-ab19-1d44938fdb13');

-- IL: DeKalb County United Academy (1 teams)
UPDATE teams SET club_name = 'DeKalb County United Academy'
WHERE team_id_master IN ('9e152704-feb8-4af7-bd1d-f33fff8e1785');

-- IL: Quad Cities Rush (1 teams)
UPDATE teams SET club_name = 'Quad Cities Rush'
WHERE team_id_master IN ('0b165a13-3cc6-457c-a100-7e3fa1a7f916');

-- IL: Rockford Raptors FC (1 teams)
UPDATE teams SET club_name = 'Rockford Raptors FC'
WHERE team_id_master IN ('a0e2b2b4-769d-459e-9461-dfeb2d6b6ed6');

-- IL: Wheaton United SC (1 teams)
UPDATE teams SET club_name = 'Wheaton United SC'
WHERE team_id_master IN ('294fd3fb-d85e-47db-8765-8d55dc4a592d');

-- IN: FCE United (1 teams)
UPDATE teams SET club_name = 'FCE United'
WHERE team_id_master IN ('ee91159e-4ee8-4a3e-a9a9-cf8b156c3c62');

-- IN: Indy Phoenix FC (1 teams)
UPDATE teams SET club_name = 'Indy Phoenix FC'
WHERE team_id_master IN ('b8dcc5ce-aca3-4192-91ec-22f2716e0051');

-- IN: NWI Lions United (4 teams)
UPDATE teams SET club_name = 'NWI Lions United'
WHERE team_id_master IN ('1487d9b2-2616-4364-ae52-363fa5a37e2c', 'c4acf413-21e3-4770-929a-581cb8b827d3', '6683ae06-91f5-4db1-8602-5f769f985aea', '0bb1cf1b-ffbf-4c70-af54-2b1da80960ea');

-- IN: USAI (1 teams)
UPDATE teams SET club_name = 'USAI'
WHERE team_id_master IN ('9e66088b-4d1a-4ad1-a397-df160909bea0');

-- KS: Fountain City FC (1 teams)
UPDATE teams SET club_name = 'Fountain City FC'
WHERE team_id_master IN ('2e983208-b497-41e3-844c-3059bcbb8a28');

-- KS: Kansas Rush (1 teams)
UPDATE teams SET club_name = 'Kansas Rush'
WHERE team_id_master IN ('d1ab5bc0-7d82-4bb4-8174-e182ef4e0c16');

-- KY: Etown FC (1 teams)
UPDATE teams SET club_name = 'Etown FC'
WHERE team_id_master IN ('34027984-19fe-4a2b-8734-b69da23e4bf9');

-- KY: Javanon FC (1 teams)
UPDATE teams SET club_name = 'Javanon FC'
WHERE team_id_master IN ('cd8aaea5-2524-42c4-8e75-b2feef612d35');

-- KY: Nedo SC (1 teams)
UPDATE teams SET club_name = 'Nedo SC'
WHERE team_id_master IN ('a3dfe604-4be7-4f6e-9800-37c89f97dedc');

-- KY: Nelson County YS (1 teams)
UPDATE teams SET club_name = 'Nelson County YS'
WHERE team_id_master IN ('ade9873b-a72d-4dca-bbcc-8c1649462bf8');

-- KY: Owensboro United SC (2 teams)
UPDATE teams SET club_name = 'Owensboro United SC'
WHERE team_id_master IN ('d1c9ef13-0717-4291-8a76-cac5363d565b', '1d4472da-eec2-4785-8a84-b49d9871d7c1');

-- KY: West louisville Soccer (2 teams)
UPDATE teams SET club_name = 'West louisville Soccer'
WHERE team_id_master IN ('3b6d43a0-992d-4334-ac33-7174e69e4838', 'f1f8fb18-bb22-4c0b-ae75-65cc2d9810e0');

-- LA: Ascension Flight Soccer Club (1 teams)
UPDATE teams SET club_name = 'Ascension Flight Soccer Club'
WHERE team_id_master IN ('3093dd06-02eb-4348-86a9-1667ec0f8b21');

-- LA: Covington FC (1 teams)
UPDATE teams SET club_name = 'Covington FC'
WHERE team_id_master IN ('18c3f225-8ab3-42fc-b07d-54187ccc9872');

-- LA: LA Force Soccer Club (1 teams)
UPDATE teams SET club_name = 'LA Force Soccer Club'
WHERE team_id_master IN ('a7290b65-eb5d-4aa3-bc90-7461868bc482');

-- LA: Madisonville United (2 teams)
UPDATE teams SET club_name = 'Madisonville United'
WHERE team_id_master IN ('1be0f8cf-a346-40af-bb91-6c321de6537a', '364545a9-f43b-4441-a2d5-3e7f3b2a2b4c');

-- MA: FC Juventud New England (1 teams)
UPDATE teams SET club_name = 'FC Juventud New England'
WHERE team_id_master IN ('e383cd97-ecfd-48c5-b1c1-fb61fae3d218');

-- MA: Inter Academy Metrowest Boston (2 teams)
UPDATE teams SET club_name = 'Inter Academy Metrowest Boston'
WHERE team_id_master IN ('1e5e770b-f26d-4620-99d6-70710d7fb731', 'ac7dcb15-57f4-49f4-8ba0-b7038e46e951');

-- MA: NATICK SOCCER CLUB (1 teams)
UPDATE teams SET club_name = 'NATICK SOCCER CLUB'
WHERE team_id_master IN ('5234c8d0-8918-4cc3-93c5-9e21f270ba3c');

-- MA: Valeo FC (1 teams)
UPDATE teams SET club_name = 'Valeo FC'
WHERE team_id_master IN ('2a107fc6-06bb-4349-b4a5-0ae731f855f9');

-- MA: Wachusett United FC (1 teams)
UPDATE teams SET club_name = 'Wachusett United FC'
WHERE team_id_master IN ('04ded68b-0a4e-460a-be52-6cb7c714a9ac');

-- MA: Western United Pioneers FC (1 teams)
UPDATE teams SET club_name = 'Western United Pioneers FC'
WHERE team_id_master IN ('250e9a70-1c6e-45bc-9fbb-553136a0a744');

-- MD: Avid Soccer Club (1 teams)
UPDATE teams SET club_name = 'Avid Soccer Club'
WHERE team_id_master IN ('ea8b6a12-1945-4783-8fc1-b76c0be8f1d7');

-- MD: Baltimore Bays Soccer Club (6 teams)
UPDATE teams SET club_name = 'Baltimore Bays Soccer Club'
WHERE team_id_master IN ('883aae06-5ea6-4a35-9a40-8ee24048fb53', 'b9a6c88e-cb2e-4ea2-b875-a44df9ae2b9c', 'fa2d82dc-5b45-436d-98db-7c432a8e2ba3', '050e6e8c-9740-4470-a1ae-bfb6372d47c6', 'c77fd33c-0548-461a-b11a-8c615f029359', 'be9f3096-885e-4282-b80d-2e33f6e9f04d');

-- MD: Bethesda SC (4 teams)
UPDATE teams SET club_name = 'Bethesda SC'
WHERE team_id_master IN ('bc63321e-5d33-40bd-8765-222be8dd0843', '9f05030a-817e-4ea1-83cd-bcb7c60d68b7', 'a27dd84e-7f36-4a43-85e8-4b61e6642490', '14ce1767-b355-436f-9d53-a8af8198f590');

-- MD: FC Millennium International (1 teams)
UPDATE teams SET club_name = 'FC Millennium International'
WHERE team_id_master IN ('37d9cadd-8a39-4f7f-9cc5-d736b7883094');

-- MD: Fallston Soccer (1 teams)
UPDATE teams SET club_name = 'Fallston Soccer'
WHERE team_id_master IN ('54c49c4b-1d4a-4211-ab53-9c728a0abf49');

-- MD: Freedom Soccer Club (1 teams)
UPDATE teams SET club_name = 'Freedom Soccer Club'
WHERE team_id_master IN ('1e536585-ceff-479c-9401-281db33a60c3');

-- MD: Potomac Soccer Association (1 teams)
UPDATE teams SET club_name = 'Potomac Soccer Association'
WHERE team_id_master IN ('e82a58d9-c1bc-43b0-878c-19a50ed49a95');

-- MD: United Elite Soccer Inc (1 teams)
UPDATE teams SET club_name = 'United Elite Soccer Inc'
WHERE team_id_master IN ('1eaf099e-f5b5-4fb2-88bb-c7f23faa28b7');

-- MI: AYSO United (4 teams)
UPDATE teams SET club_name = 'AYSO United'
WHERE team_id_master IN ('1e9e284d-4b3f-4eea-b7db-abd13dbc7003', 'fe18cd51-b836-4f7b-a7b2-bf21d4181b2f', '460d06ca-f720-4398-8768-265775955b39', '04d86ea9-a9b9-4529-a5d5-add1ad68e6d7');

-- MI: Gaylord Soccer League (1 teams)
UPDATE teams SET club_name = 'Gaylord Soccer League'
WHERE team_id_master IN ('d3209d1f-50fe-44b3-9b27-c684d8baa82b');

-- MI: Lakewood Soccer Club (2 teams)
UPDATE teams SET club_name = 'Lakewood Soccer Club'
WHERE team_id_master IN ('91e20f4c-53e4-409c-b8b0-d60d2f205d2c', '8c662131-cef7-4e41-ac4b-4d706bef9835');

-- MI: Michigan Jaguars (1 teams)
UPDATE teams SET club_name = 'Michigan Jaguars'
WHERE team_id_master IN ('a45c3712-022c-4950-802b-729506469a21');

-- MI: Midwest United FC Scor (1 teams)
UPDATE teams SET club_name = 'Midwest United FC Scor'
WHERE team_id_master IN ('dd8f990f-3441-4518-bb20-c147d4e133a2');

-- MN: Crow River Soccer Club (2 teams)
UPDATE teams SET club_name = 'Crow River Soccer Club'
WHERE team_id_master IN ('d62e9883-7e59-4654-9d4e-5af4b6ade1e1', '822ed987-fcc6-4f07-bdce-f38dd0b4fe0e');

-- MN: Gitchi Gummi Soccer Club (4 teams)
UPDATE teams SET club_name = 'Gitchi Gummi Soccer Club'
WHERE team_id_master IN ('8815dce2-7ee1-4715-af7c-f94718f7096a', '16ec111b-9ade-4a1b-9874-1d0881759095', '126e124c-4962-4b63-ad49-1d3c86ea6441', '26e185e8-beaf-45ca-bc70-5a42fb93b6f8');

-- MN: Salvo SC (2 teams)
UPDATE teams SET club_name = 'Salvo SC'
WHERE team_id_master IN ('2ed796e5-8cfe-4c03-ae0a-a69b7996ff3f', 'e3f2f00f-e185-463c-9d9e-e679daf75db2');

-- MO: Jaguar FC (1 teams)
UPDATE teams SET club_name = 'Jaguar FC'
WHERE team_id_master IN ('26e7b328-c538-418e-a04c-910fe6e68c3a');

-- MO: Monarchy FC (2 teams)
UPDATE teams SET club_name = 'Monarchy FC'
WHERE team_id_master IN ('6a889b62-9845-433a-8aad-07c793a43763', 'a3d2335a-1cc2-4f4f-a922-00400b72acf8');

-- MO: St. Louis Stars SC (2 teams)
UPDATE teams SET club_name = 'St. Louis Stars SC'
WHERE team_id_master IN ('eff828fc-8d52-4855-89c2-351df82b2af2', '2779f591-b85d-4e18-af8b-6a3835249019');

-- MS: Brilla JUNIORS (1 teams)
UPDATE teams SET club_name = 'Brilla JUNIORS'
WHERE team_id_master IN ('6f5b8d0b-9516-4fce-9ffb-71196b0026dc');

-- MS: Oxford FC (2 teams)
UPDATE teams SET club_name = 'Oxford FC'
WHERE team_id_master IN ('c1f76b4d-7716-46ac-940d-22a30fa9e2f4', '6194878d-f0cc-4d0c-8804-4b997f61ec97');

-- MS: Tupelo Futbol Club (2 teams)
UPDATE teams SET club_name = 'Tupelo Futbol Club'
WHERE team_id_master IN ('ba64a7c1-948c-41d7-9257-6a79b556b9f4', 'ab592f49-2ce9-4f42-bb44-de76e356c825');

-- NC: NCFC Youth (1 teams)
UPDATE teams SET club_name = 'NCFC Youth'
WHERE team_id_master IN ('ffc22857-db87-4a6d-9bc8-5037fa4d19ef');

-- ND: Bismarck Bricks SC (1 teams)
UPDATE teams SET club_name = 'Bismarck Bricks SC'
WHERE team_id_master IN ('59d94a19-99a9-4f1f-bb79-07cb02354cce');

-- ND: Dickinson Soccer Club (1 teams)
UPDATE teams SET club_name = 'Dickinson Soccer Club'
WHERE team_id_master IN ('98359e6e-6136-4a53-91fc-dfd7dc8c31b1');

-- ND: Magic Soccer FC (8 teams)
UPDATE teams SET club_name = 'Magic Soccer FC'
WHERE team_id_master IN ('d1e0ac50-3785-4ada-b413-52000202dc0a', 'f95a328e-d172-4ef6-bc22-40cfbbf4551a', '95504304-39cd-4041-9b24-f2a414167135', 'fbb31649-af98-4f1f-8a5a-440c111c69d2', 'be6ead5e-2986-425f-87b4-ee7921a0c3e1', 'd142e061-6145-476c-bcc1-0cd357f396ce', 'ff1a9a85-bb73-48e9-9fae-d27935be97da', '9d1e61df-0d8b-45dd-b6b2-b6bc6b28590c');

-- NE: Evolution SC (1 teams)
UPDATE teams SET club_name = 'Evolution SC'
WHERE team_id_master IN ('d111fa94-ac13-4c0d-b0aa-37fb6995e399');

-- NE: Omaha United SC (2 teams)
UPDATE teams SET club_name = 'Omaha United SC'
WHERE team_id_master IN ('8f5e219e-61b9-43ec-b419-7ef67f1a5455', 'd618adc7-50e9-471e-a4d3-681b50a9edba');

-- NH: ConVal Soccer Club (1 teams)
UPDATE teams SET club_name = 'ConVal Soccer Club'
WHERE team_id_master IN ('f1fa5e4b-a5fa-4b79-9398-aa99e3020451');

-- NJ: Audubon Soccer Youth Association (3 teams)
UPDATE teams SET club_name = 'Audubon Soccer Youth Association'
WHERE team_id_master IN ('d8276240-9976-4a03-859f-c8481958c087', '20a28601-b414-4be7-9913-1a82fbdec5ec', '7524031e-de06-4023-8d02-87443d82b481');

-- NJ: PDA White (Shore) (1 teams)
UPDATE teams SET club_name = 'PDA White (Shore)'
WHERE team_id_master IN ('a77e7eff-4bca-4855-84ee-7c7b28770b53');

-- NJ: SJEB FC (1 teams)
UPDATE teams SET club_name = 'SJEB FC'
WHERE team_id_master IN ('4904eada-e4f2-4b2e-b0af-a86c0ee5cbfc');

-- NJ: STA (1 teams)
UPDATE teams SET club_name = 'STA'
WHERE team_id_master IN ('248b34ea-53f2-448c-8b50-1238fa2d94d9');

-- NJ: Torpedoes SC (1 teams)
UPDATE teams SET club_name = 'Torpedoes SC'
WHERE team_id_master IN ('dacebe09-a09c-4076-8276-5015a6d66b49');

-- NJ: Washington United FC (1 teams)
UPDATE teams SET club_name = 'Washington United FC'
WHERE team_id_master IN ('839a63b5-4829-4aca-ab21-a491990b99be');

-- NM: NM Rapids SC (1 teams)
UPDATE teams SET club_name = 'NM Rapids SC'
WHERE team_id_master IN ('53e11f7d-19ed-44d4-b45c-d304c6a8f464');

-- NV: Dezert Storm FC (1 teams)
UPDATE teams SET club_name = 'Dezert Storm FC'
WHERE team_id_master IN ('b063d3c3-6663-429c-be07-676b05255b02');

-- NV: Nevada Rush (1 teams)
UPDATE teams SET club_name = 'Nevada Rush'
WHERE team_id_master IN ('1c9d2fa6-2c5c-4934-9c05-609e61cfa5c6');

-- NV: Players SC (1 teams)
UPDATE teams SET club_name = 'Players SC'
WHERE team_id_master IN ('b2fab882-9776-4e0d-af38-7e3e64a1820f');

-- NV: Rayados Las Vegas Soccer Academy (2 teams)
UPDATE teams SET club_name = 'Rayados Las Vegas Soccer Academy'
WHERE team_id_master IN ('7b34af0e-5bf3-4fc2-bff1-b07564135aad', 'cb0584cd-d275-4375-86fc-aa4d55947b4c');

-- NV: Sierra Surf (1 teams)
UPDATE teams SET club_name = 'Sierra Surf'
WHERE team_id_master IN ('13ae98fe-ceac-4712-9a08-7bac080ce6cc');

-- NY: Niskayuna (1 teams)
UPDATE teams SET club_name = 'Niskayuna'
WHERE team_id_master IN ('5ace5063-093b-4984-9168-b1db6a9e7968');

-- NY: Rochester NY FC (1 teams)
UPDATE teams SET club_name = 'Rochester NY FC'
WHERE team_id_master IN ('5e6ed3b5-a31d-46ac-8a7c-3132611b98d2');

-- NY: Saints FC (1 teams)
UPDATE teams SET club_name = 'Saints FC'
WHERE team_id_master IN ('18e9551d-92b1-4f66-b9f7-3594ccb76136');

-- OH: Barcelona United (1 teams)
UPDATE teams SET club_name = 'Barcelona United'
WHERE team_id_master IN ('5d4730c0-859f-4d88-bfbc-b9a903351b7f');

-- OH: Bay Area Soccer League (1 teams)
UPDATE teams SET club_name = 'Bay Area Soccer League'
WHERE team_id_master IN ('47044e54-21f1-48d7-9d44-3b7a6c235450');

-- OH: Bluffton SC (1 teams)
UPDATE teams SET club_name = 'Bluffton SC'
WHERE team_id_master IN ('1c32732c-9f02-4e6b-ad18-010c05e3b9bd');

-- OH: Cincinnati United (2 teams)
UPDATE teams SET club_name = 'Cincinnati United'
WHERE team_id_master IN ('b4ba88e1-f43a-4771-b402-c64af9973545', '506b8894-0ce4-4cae-a435-843e5b08b663');

-- OH: Cincy SC (1 teams)
UPDATE teams SET club_name = 'Cincy SC'
WHERE team_id_master IN ('1fd609f5-55bd-49a7-90c6-7e1b653e0217');

-- OH: Club Ohio (1 teams)
UPDATE teams SET club_name = 'Club Ohio'
WHERE team_id_master IN ('1aeada29-db4e-417d-9163-b47fec9e1f12');

-- OH: Cuyahoga Valley Soccer Academy (1 teams)
UPDATE teams SET club_name = 'Cuyahoga Valley Soccer Academy'
WHERE team_id_master IN ('0b3aa50f-3fc7-46a8-a960-a8d7c8258d5f');

-- OH: FC Storm (2 teams)
UPDATE teams SET club_name = 'FC Storm'
WHERE team_id_master IN ('34e18515-79a6-46a1-a8ba-3b0138946178', '2dba24a1-e1b0-4d61-9cb7-5e22ce936de5');

-- OH: Manta United Soccer Club (1 teams)
UPDATE teams SET club_name = 'Manta United Soccer Club'
WHERE team_id_master IN ('60349c78-3fa4-405a-bfbe-b954f1620b07');

-- OH: North Ridgeville Amateur Soccer League (1 teams)
UPDATE teams SET club_name = 'North Ridgeville Amateur Soccer League'
WHERE team_id_master IN ('0a1e607a-2d80-42b9-9045-df195efabbf9');

-- OK: Tulsa SC (1 teams)
UPDATE teams SET club_name = 'Tulsa SC'
WHERE team_id_master IN ('fb31274a-cbce-4fdd-bf34-b5156dfbdda4');

-- OR: College Cup (3 teams)
UPDATE teams SET club_name = 'College Cup'
WHERE team_id_master IN ('a6214aff-805b-410f-9141-a7456db01c9c', '91adcaef-0b30-451a-adae-353265b36e3d', 'dc17d883-cc3d-48c6-9dee-4dc2d9c8a44f');

-- OR: Eastside Timbers (1 teams)
UPDATE teams SET club_name = 'Eastside Timbers'
WHERE team_id_master IN ('0702db4b-0a19-4fe7-a820-9e012d1535e2');

-- OR: United PDX (2 teams)
UPDATE teams SET club_name = 'United PDX'
WHERE team_id_master IN ('a9bc3e0f-3681-440a-bf2f-123d5541e2f1', '3ce64d27-6531-40be-a8b7-d86e21e765bf');

-- PA: Beadling SC (1 teams)
UPDATE teams SET club_name = 'Beadling SC'
WHERE team_id_master IN ('ed867ebd-bf4f-4014-b730-942512f87b99');

-- PA: Century United Soccer (3 teams)
UPDATE teams SET club_name = 'Century United Soccer'
WHERE team_id_master IN ('a1a67f5e-847c-49aa-b7e8-fb3905ec85ec', 'ecc0f419-3694-4659-872b-dc66c7c173d7', 'd51e75b2-581d-4aee-aa6a-9cd6b667c984');

-- PA: FC Brandywine (1 teams)
UPDATE teams SET club_name = 'FC Brandywine'
WHERE team_id_master IN ('cfb060f2-2d25-4cac-8842-b820e6d9c4e5');

-- PA: Pittsburgh Riverhounds (36 teams)
UPDATE teams SET club_name = 'Pittsburgh Riverhounds'
WHERE team_id_master IN ('4ba4f92b-48a9-48bd-a5bc-0d67c25bc219', '4115a560-6dea-41c2-91ac-3db86583d239', 'd688bdf0-c360-455f-afb8-4abb159e4713', 'ddeb1393-62d5-4ed3-bbf1-be441dd9778b', '71de1861-087b-49a4-97e4-5407c4cf410b', '59441c1f-ef88-4915-9d59-403202a59472', '81a5058f-4a14-48c5-9aae-1b1836b1c724', '75ac7037-b072-4ff5-8887-37c8add58314', '89ef7fce-f42b-4cc9-aa34-6011549b0bd1', 'c46f262a-1d8b-49a1-a274-6a697bee4567', 'ca18527d-7556-40c5-958d-cadef13a7904', 'deb7977e-6746-42a4-ae4c-e8d5ffedfe03', '1bc7427a-2e81-494f-8058-388df2a136e0', 'ba15d3de-f46f-4d23-b72a-10c883ae4535', '0dcf6765-dfac-46db-8543-dd8f331c45a9', 'fc6a24ee-7bc0-410f-b3c9-7d862447828f', '1252c790-411c-43ba-8d57-8e49aeb92aff', 'd88b5adc-ebff-407c-afab-b5bc1f59e804', '40bb3df4-02c4-438e-b85b-26bf5fb1a914', 'a7d896de-18a3-4db0-a802-eb0d217622d3', 'ddfb320a-4bd2-4c1c-b6a0-2268c7b67b4a', 'b3757f01-cdce-4b10-a061-3f51d8b5733f', '146166ba-cc5d-4d1a-a437-a261084782c3', '48184198-18c7-4b0d-a10a-e1bbc7e70851', 'c12fdb84-5f70-4c2f-98f7-1a1e5dfcaecf', '9dd85c25-b6bf-490c-9cf9-74c610c6e944', 'fc95b4fc-b706-4b0c-8928-5c6150bad807', 'e61a18e7-9a40-4b10-b008-271cad7ad420', '05b5213d-ca4e-46dc-85bf-b20e67ca14bb', '56663cbb-ead4-4e66-a336-c9b2cf0f7b3f', 'b6a4d721-3757-4ebf-91d0-bae3e4e9c6fb', '3fceb897-df8b-41bf-abda-76281f2e23f7', 'b3c5fe18-7b52-4374-9f87-08c14a6df2b5', 'e5856952-9b76-4fba-9005-0cd017bf606c', 'c48b1dab-f88c-4654-9919-3573b9c9c0cc', '9535fbda-bd4e-4eb7-b055-3be15c35e144');

-- PA: Steel City FC (13 teams)
UPDATE teams SET club_name = 'Steel City FC'
WHERE team_id_master IN ('ffdadf08-2acb-49e3-a0ac-ca59f2ced022', 'da7c1383-2339-487f-9f77-d450e19f00d9', 'ee3e2364-c948-4db2-88f7-480226ea66c0', '3d9afd1c-ebe6-4b9a-b344-44a508685bb9', 'afa3b071-3b54-425a-bab1-2c655216995e', 'a5e1d8fb-b1fd-44df-9d21-dbfbdd3fc66e', '2e26edf7-1687-415f-9b47-a0e4a0c859b6', '58ea4d45-f34a-4bb9-9a4e-0076a2c4bd81', '530211c9-b901-4400-b184-96e55af4cdfd', '46016c3c-fcc4-4697-9eaa-82469a46e219', '70844796-795a-4a6f-aa9c-ff2962523816', 'd5b4c101-ffac-463a-b84a-d8fe5c9cd997', '87a68717-ca12-40bd-be48-757d9fd246b0');

-- PA: Warriors United (1 teams)
UPDATE teams SET club_name = 'Warriors United'
WHERE team_id_master IN ('01b6360f-61cd-4e25-960d-e07297002c90');

-- RI: RI Strikers FC (1 teams)
UPDATE teams SET club_name = 'RI Strikers FC'
WHERE team_id_master IN ('d0eac7e4-4f4f-4dea-bde2-905521a76d46');

-- SC: Bulls SC (1 teams)
UPDATE teams SET club_name = 'Bulls SC'
WHERE team_id_master IN ('c1531355-112a-42cf-8c89-f30a3667edd7');

-- SC: Charleston United SC (1 teams)
UPDATE teams SET club_name = 'Charleston United SC'
WHERE team_id_master IN ('4159250a-5bbc-46fb-b999-752319877a7b');

-- SD: DASC (13 teams)
UPDATE teams SET club_name = 'DASC'
WHERE team_id_master IN ('d880f610-13eb-4472-bdce-f6d595719a34', '356c9877-aada-4022-a0a5-fd8ffbe83aa5', '6992324c-9456-4720-985d-e83d23bee56f', 'c4c5dd7d-5755-4b97-80e2-266790e84ad1', '68441d06-2a39-44a0-8a81-45d9e2c78d81', '811e6fa3-c925-4372-9eb6-deea3215ba9a', '3839eb80-f6b8-4f74-bd23-cde79f96d249', '530c05e7-21f6-4366-ac8b-ecec0956c67b', '6bc74cd6-b603-40c3-814c-f8c32e375291', '13f8e1af-071d-4503-ba20-1865f5d0399d', 'b0697eb7-952f-48c0-888e-2cfbdf58aec4', '65d4fc7e-fbf4-425b-90ba-1724016909c0', '88eb5b42-c52a-4820-a1f0-f7fcb4cc598a');

-- SD: SoDak Spurs SC (12 teams)
UPDATE teams SET club_name = 'SoDak Spurs SC'
WHERE team_id_master IN ('905562ae-9c69-4d0e-9931-77040e83d8f6', '3eb94d4f-32cb-4328-a23a-11bb32788381', '413206dc-6840-4135-9226-0341c04a8170', '2a1b4c99-b046-4013-80d9-037facef387c', '6a1caf9e-e47f-475f-b46c-1b12f905db97', '6b96c7da-f6bf-4701-a441-74bf819ba055', '6fabae9c-d929-4aa1-a8b1-7490831b4602', '5b62d41f-b1cc-4525-8231-153f69a403b6', 'b3c23833-05ef-4d77-b3c5-0f722690ea44', '656f1e9d-93ff-48a7-bf0a-687d2fd69945', '83b0600b-8b87-4378-b1c4-e9ec636168f9', '26f6542c-875d-43a3-b7c6-07ccd1445cf4');

-- SD: Sturgis SA (4 teams)
UPDATE teams SET club_name = 'Sturgis SA'
WHERE team_id_master IN ('001e617c-e81f-4d00-bbcc-d5c506dd32d2', 'fb7bff3e-7dde-42c4-9be8-e2c369e8d086', '994f2049-706e-41ad-ad3c-562297cb5a07', 'f8f2ab91-6a4a-4fd6-903d-171f50badb95');

-- TN: AYSO Alliance (1 teams)
UPDATE teams SET club_name = 'AYSO Alliance'
WHERE team_id_master IN ('df8fa809-9277-4fb4-b829-ef4b4783231c');

-- TN: Clarksville SC (1 teams)
UPDATE teams SET club_name = 'Clarksville SC'
WHERE team_id_master IN ('d3485786-eda7-4efa-ae22-32aeeaeeebf5');

-- TN: Germantown Legends (1 teams)
UPDATE teams SET club_name = 'Germantown Legends'
WHERE team_id_master IN ('0749dd32-8cea-4de2-b171-ff5f144a2966');

-- TN: Midsouth Bartlett (1 teams)
UPDATE teams SET club_name = 'Midsouth Bartlett'
WHERE team_id_master IN ('7fff3bb2-c5d4-4a2a-9880-c3439d6bc0c4');

-- TN: Ole FC (3 teams)
UPDATE teams SET club_name = 'Ole FC'
WHERE team_id_master IN ('a6ae8b90-f784-4271-a9e7-354ff41f9461', 'c02d65e1-eb6a-47e0-a7fb-219f91f53bcb', '298a10a5-7d51-4cec-938d-2fc8f33d0423');

-- TN: One Knoxville Youth Club (1 teams)
UPDATE teams SET club_name = 'One Knoxville Youth Club'
WHERE team_id_master IN ('9f4c235d-4108-4aaa-b05d-4b7d00fbe0f4');

-- TN: Purple Rain SC (2 teams)
UPDATE teams SET club_name = 'Purple Rain SC'
WHERE team_id_master IN ('90b39952-ff87-4d47-a88d-a896275313e4', '08baf664-a015-4674-8e33-d0b4819f4d9c');

-- TN: Rampage SC (1 teams)
UPDATE teams SET club_name = 'Rampage SC'
WHERE team_id_master IN ('0d7dd138-56f8-4d33-a412-cc988beecf74');

-- TN: Sporting United FC (2 teams)
UPDATE teams SET club_name = 'Sporting United FC'
WHERE team_id_master IN ('0fb1eeca-121f-402c-ab85-ecd81852adbf', '89e8a913-2b63-4175-99d3-38b796e644cf');

-- TX: 210 FC (4 teams)
UPDATE teams SET club_name = '210 FC'
WHERE team_id_master IN ('68a84993-c65c-4da5-a6de-f0f771d82f00', '214fc387-9983-47a5-b480-a633975dfa10', 'e245ab1f-e1a7-422f-9bce-7054802063f9', 'c02b25d8-de38-4fe7-8ad1-5cc6aef1dc81');

-- TX: Albion Hurricanes FC (1 teams)
UPDATE teams SET club_name = 'Albion Hurricanes FC'
WHERE team_id_master IN ('51a5f805-f519-44a5-950d-da152ba2cd0f');

-- TX: Austin FC (1 teams)
UPDATE teams SET club_name = 'Austin FC'
WHERE team_id_master IN ('ff574641-ce34-49bd-9ce0-ae030abe6c5d');

-- TX: Barcelona SC (1 teams)
UPDATE teams SET club_name = 'Barcelona SC'
WHERE team_id_master IN ('af534285-9cff-434b-bf47-7e461d04ea09');

-- TX: Challenge SC (1 teams)
UPDATE teams SET club_name = 'Challenge SC'
WHERE team_id_master IN ('44c17c9b-63bc-49d0-9bd7-04babc5ff8b7');

-- TX: Dallas Surf (2 teams)
UPDATE teams SET club_name = 'Dallas Surf'
WHERE team_id_master IN ('bdd720ea-6946-479c-90ab-6843a6ed52e6', 'c0738eb3-27e2-4a1f-8572-84c7e5439444');

-- TX: FC Dallas (2 teams)
UPDATE teams SET club_name = 'FC Dallas'
WHERE team_id_master IN ('ba398dc2-d4d6-46ba-8c40-097d824a9488', '19fc2b23-8165-4152-ac27-a7bcb41ec8d3');

-- TX: FC Dallas High Plains (4 teams)
UPDATE teams SET club_name = 'FC Dallas High Plains'
WHERE team_id_master IN ('5d4bf824-e648-4536-90f2-53cfae4044a7', '10dbd972-1d40-4ac0-8d7e-7ac9f4da45c0', '33289dfe-a060-497d-b20b-f32539c5e682', 'fa3b3d8e-3c87-45be-af8a-8fa18e1d5045');

-- TX: Houston Dynamo FC (1 teams)
UPDATE teams SET club_name = 'Houston Dynamo FC'
WHERE team_id_master IN ('01aa9f63-7b41-4486-9df2-6ce11c79acfb');

-- TX: Lonestar (2 teams)
UPDATE teams SET club_name = 'Lonestar'
WHERE team_id_master IN ('af3fe8c6-7d9c-49aa-9840-3a26caa5606d', '8dc1baf4-2eee-43f9-ba1f-bdf94143e855');

-- TX: NTX UNITED FC (1 teams)
UPDATE teams SET club_name = 'NTX UNITED FC'
WHERE team_id_master IN ('eb9f05d2-7ffd-4803-9ee0-1d8a9b433782');

-- TX: Solar SC (2 teams)
UPDATE teams SET club_name = 'Solar SC'
WHERE team_id_master IN ('25e54c2e-d49c-45bf-b9f1-04d128f5319e', 'eecce062-9e7e-40f7-a1bc-ea5d01bd72ad');

-- UT: AYSO United (2 teams)
UPDATE teams SET club_name = 'AYSO United'
WHERE team_id_master IN ('5ec6661d-f33b-476f-b46d-ece39d705588', 'dc68dd0f-16bd-4a48-8fa3-a7ae4500b622');

-- UT: Aggies FC (13 teams)
UPDATE teams SET club_name = 'Aggies FC'
WHERE team_id_master IN ('fb2f23d2-cefa-40b1-a63b-626bf7f74ea7', '84005bb4-fca9-4f3c-a980-4a18c741d6ee', 'ea52f0c3-8f8c-4242-96e8-7400e97c8816', '70d0947e-b495-4cd0-bc12-1d03fce40ac0', '7d3a0689-6163-4aae-af92-ccc5ecccdc73', 'cd8244fc-6bca-48f9-bd55-a1c98d24da26', '2b7766d5-a0ea-4c9f-8603-2925490ad008', 'd98f2e8c-924a-4ba0-be04-2be6f8e9b5c7', '47c9f538-deba-4cd3-bc1f-c7990af64fe2', 'e0eae292-3d29-47d7-9e1d-57d8ac5f50d3', 'c969def9-d6b0-4409-a970-0159e3e693e3', 'd52a89a2-be06-4e5e-b2eb-76b1353de5e6', 'b0532ea7-d6f4-498d-967e-790a8d2d3856');

-- UT: Atomic Athletics SC (1 teams)
UPDATE teams SET club_name = 'Atomic Athletics SC'
WHERE team_id_master IN ('2e6d1373-8d87-42c3-9992-5a85ffc1d08b');

-- UT: Avalanche Sl/Dw (9 teams)
UPDATE teams SET club_name = 'Avalanche Sl/Dw'
WHERE team_id_master IN ('f0f9436c-edfe-4b66-9046-30724e8cf02b', 'dd7ca8b9-d8bd-4c7a-8559-ff4d868ce400', '67cbfe36-02af-4134-ba58-efca0989f8eb', '6c5858a6-9dd4-45cf-8372-d0baa907941d', '945613a9-121a-4e88-aa7e-c4e0167a40d8', 'c226c38f-810f-4ddb-956e-1c40078688e8', '789d32df-b1ca-4cc0-a5ab-8903d16fea15', '32e54347-898c-4bb3-ac49-8d3d6d900374', '09f82d03-f722-4df8-adad-4f5f71f89fcf');

-- UT: Blast SC (3 teams)
UPDATE teams SET club_name = 'Blast SC'
WHERE team_id_master IN ('e5bf3181-469c-473f-9851-7c288f6032c1', 'c9f9c602-b6da-454b-8d6b-077867fb5c60', 'f244be25-2c47-48a2-b64c-3a813e672251');

-- UT: Blue Knights SC (4 teams)
UPDATE teams SET club_name = 'Blue Knights SC'
WHERE team_id_master IN ('aa118cdb-26c8-424a-b6bd-826291b1b0ac', 'fa40f565-5a8f-4187-9f25-616a0ab1a8dd', 'b2db114c-2a49-4f24-af49-cd20281f55f8', '9f2076e7-e0cb-440a-96d4-242517e625ca');

-- UT: City SC Utah (11 teams)
UPDATE teams SET club_name = 'City SC Utah'
WHERE team_id_master IN ('cf66eb98-817d-4b64-a2cb-ac59a8b1d264', '879b6313-f833-4bf3-aac2-c3a8502d637e', 'bc97415b-e6b5-4774-ae47-018eb5c0b1f8', '0b2f86a3-d307-4588-bf95-745f6a797ed3', 'b7885219-a486-4679-905b-12134b901e81', '535886e9-ec08-4eb8-8d97-b3c12b178210', 'a34a8eb1-dc36-4236-b768-c97957a91596', '6cad13da-ace8-4d8b-bcd4-13414fe598b2', 'aee8b484-2548-4f1c-93e4-185cd911d313', '03327912-04c9-497c-b461-1c90e3f17afd', 'd7e16201-29b0-4548-adc8-f22ece7d793b');

-- UT: Copper Mountain (6 teams)
UPDATE teams SET club_name = 'Copper Mountain'
WHERE team_id_master IN ('688a98ce-f0bd-4dfd-9714-93b0caada6a4', '0051ebef-ca6d-4a82-a4e6-1837328cc1f2', '7103eabb-20ac-4dc6-b76c-72e204ac283c', '2eb131a5-7115-4c1a-9a78-d4e29971105a', '72028af9-1ead-4977-9d1d-9d600fec9dbb', 'efff7cc6-31d1-4994-aac5-3f1912e3f739');

-- UT: Elite FC (18 teams)
UPDATE teams SET club_name = 'Elite FC'
WHERE team_id_master IN ('3a6a4742-4a4e-4c61-8c41-7b181198be9f', '0fc8a473-420e-4663-9aab-0def5bff153c', '8efd03e3-3b47-420f-afad-e127020c39b3', 'a71ef5f2-bffd-4efc-bb4f-fa77ac9e8996', '3729a8f9-228f-4a5b-8b0f-88ec912e26fd', '2f39776e-4323-4e1f-9169-7837c106f1dc', '86a589c6-b84e-4b75-aafe-30598edee228', '7364c1f4-6743-40ea-a789-d577fefc2987', '2871c1c5-3b1e-4d19-8cc2-bfb637b870ac', 'eb7468b5-ab23-410e-b807-2a7afe610d1e', 'b1109215-ed55-4703-8fa4-37a9d8317883', '21283f8d-8cff-4b20-8d0f-a53e95911a37', 'c4775d71-d04a-4b9d-a3a3-0b7cec025e13', 'd3a46a0f-16da-4f86-94b7-d6874d0b1b78', '59069988-9091-4da8-9457-38aa12159880', '065a4ef9-d43f-4d99-a353-a95cc2b75d0e', 'fbf371ec-fb53-4dc9-8b5a-c0d9ba29d770', 'd5e5d9ee-989e-4854-a43c-16f544663237');

-- UT: Fire FC Utah (2 teams)
UPDATE teams SET club_name = 'Fire FC Utah'
WHERE team_id_master IN ('f3bb8cbb-a5de-4c3d-8ac2-03c63dab82d5', 'a835e12e-14a0-4eaa-8328-c3e6f4fd5b07');

-- UT: Gremio FC (3 teams)
UPDATE teams SET club_name = 'Gremio FC'
WHERE team_id_master IN ('e00d3030-826a-42b5-a986-e76bdb98b74c', '6340a81c-c835-4220-8ac1-801bc35a1f2e', '0b86f73a-06b3-4c85-8d06-6be98e6f0efd');

-- UT: Heber Valley United (2 teams)
UPDATE teams SET club_name = 'Heber Valley United'
WHERE team_id_master IN ('f505cdb0-164f-4971-828a-6d28472879a8', 'b33d0669-ced7-41ca-bfda-1581c61e243c');

-- UT: Ignite FC (3 teams)
UPDATE teams SET club_name = 'Ignite FC'
WHERE team_id_master IN ('0965fc02-a7e9-4595-80aa-d9775e755519', '2799aa28-39a4-4d33-a4e5-b5b903c114b9', '62b1e596-225c-4ecb-bc67-b49227db22fd');

-- UT: La Roca FC (5 teams)
UPDATE teams SET club_name = 'La Roca FC'
WHERE team_id_master IN ('952dd219-864b-4538-8c5b-2fee72fc9636', '67454946-dbf8-42d3-b851-98ba80540bcf', 'e440745e-9b7e-4a63-907a-e31e55f6e068', 'bb67671a-1152-48ba-9eb2-db9017cfb76f', '81b55242-d6d8-45b0-8920-12d967cd3fdc');

-- UT: Liverpool FC (2 teams)
UPDATE teams SET club_name = 'Liverpool FC'
WHERE team_id_master IN ('e1ef23b3-04ea-4430-8d7a-9d64b39dbf08', 'd937fb7d-9ade-4c43-b964-ba6ac3a96a62');

-- UT: Magic FC (1 teams)
UPDATE teams SET club_name = 'Magic FC'
WHERE team_id_master IN ('de284f07-f906-4016-b43e-096975bc451f');

-- UT: MetaSport FC (10 teams)
UPDATE teams SET club_name = 'MetaSport FC'
WHERE team_id_master IN ('a3d05ba6-c019-49ee-992d-f52d023e63ae', '895e8008-b5c2-44a5-b07b-761dee3d3f49', 'de3b11c0-66ff-4ff4-9612-16754f5b5054', '4d4e2dad-5666-43c9-b420-9b7b0bb00286', 'f418f1c9-0c25-4be6-932b-d5406c99f5a1', '9cc9c13f-b7c7-4aa6-879e-21c2d8d28f3b', '505f7079-f5ff-4249-b51c-842ab1b22e2d', 'e907d0b1-a6bd-49d6-8f6b-670a4127b9e8', '229d550b-9ae8-49d6-86d3-9c4c6b2a47e0', '9193ffda-be48-4524-ae25-5ce36ffe83d2');

-- UT: Murray SC (2 teams)
UPDATE teams SET club_name = 'Murray SC'
WHERE team_id_master IN ('a7d6c6a6-d472-4c52-a604-328c06cd1dc6', '6efb5a74-75e7-4bc2-9e65-bf5ab487599a');

-- UT: Northern Utah United Soccer (1 teams)
UPDATE teams SET club_name = 'Northern Utah United Soccer'
WHERE team_id_master IN ('ed635218-9231-491b-b1d5-c9c50f792ddf');

-- UT: Ogden Soccer (1 teams)
UPDATE teams SET club_name = 'Ogden Soccer'
WHERE team_id_master IN ('d7706fe9-3a05-4b5a-93d5-267f8028ad40');

-- UT: Park City SC (3 teams)
UPDATE teams SET club_name = 'Park City SC'
WHERE team_id_master IN ('ab2ead0e-790d-4b31-a575-4b7705ef7aaf', 'ea423cc4-b06f-4ad5-b104-69bdd06ba7d8', '7a871a31-1bac-460d-a3b3-10c06e0cf39f');

-- UT: Peak SC (16 teams)
UPDATE teams SET club_name = 'Peak SC'
WHERE team_id_master IN ('f23f6558-bfd4-4d47-88c2-a9d5c9a21e6a', '6e02ca21-175f-4959-b4a5-0b8c89cd6691', '47900572-aa11-4aa6-8e49-e3390ad7fe03', 'ae7940fe-b942-4527-b7e0-656bc4108316', '8dda809e-a6b5-422b-8f82-dc4106a71684', '070a28b5-5263-497e-84d3-589cdec512f9', '2fd26ed3-ae17-49d4-b4f6-82b072e1bdfb', 'c2d691d8-59ef-4841-b94f-f8cfb77ac605', 'a946599d-014c-4f28-a165-b8058a3287b2', '143e22a3-d4bb-4a77-902d-c17097c7d073', '8f7c3cb1-13d9-46cd-893a-d70c173a3134', 'c61deb12-e330-4b71-b01e-5bb662b27756', 'fb2feb9d-d723-4315-a552-30405aae38bb', '0a35c8e2-91da-4c2c-839d-b98f3ab42a62', 'bace340c-5466-40f0-828d-c65168b50c7c', 'e87ba741-cdad-4acd-84dc-1c402a14aa71');

-- UT: Rampage SC (5 teams)
UPDATE teams SET club_name = 'Rampage SC'
WHERE team_id_master IN ('5eb3178c-bf8a-4df1-aece-7dbb0d5d575a', '7d517a40-4e42-494a-82b8-12995bd93868', '55ff8116-5e5f-4b4a-987e-170e7115148f', '9c620e62-9977-4534-878b-577f0554e68f', '7bf84823-c78b-4b25-8a10-c8c3e0c78121');

-- UT: SWAT Soccer (3 teams)
UPDATE teams SET club_name = 'SWAT Soccer'
WHERE team_id_master IN ('14f684d7-439d-4661-8f9e-5fc166101794', '917ceb03-0d02-48e3-97e9-04ed3a71568f', '24c7ed28-b787-43bd-b8fb-f4762bbcc08f');

-- UT: Shooters SC (2 teams)
UPDATE teams SET club_name = 'Shooters SC'
WHERE team_id_master IN ('249f402a-0896-4562-91dc-f45f47f96494', 'a0997a3f-d536-4b97-885c-da1c49463f5a');

-- UT: Summit FC (1 teams)
UPDATE teams SET club_name = 'Summit FC'
WHERE team_id_master IN ('fb27eaef-b38f-4b04-8d4e-ac3f80432f7a');

-- UT: Utah Athletic Club (1 teams)
UPDATE teams SET club_name = 'Utah Athletic Club'
WHERE team_id_master IN ('1e182efa-d5e8-41b3-8b09-c2b636901660');

-- UT: Utah Real FC (3 teams)
UPDATE teams SET club_name = 'Utah Real FC'
WHERE team_id_master IN ('b726cbdc-ff55-49c4-bcd2-f5d5c0e5e650', '07803ca1-6c9c-4d59-8771-7da93844b2a0', 'fc0e387c-a43c-4a70-b0e2-6465acabadd8');

-- UT: Utah Rush (1 teams)
UPDATE teams SET club_name = 'Utah Rush'
WHERE team_id_master IN ('b66e85d5-70e6-4403-9b1d-a4202ca23d9b');

-- UT: Utah Surf (6 teams)
UPDATE teams SET club_name = 'Utah Surf'
WHERE team_id_master IN ('36408179-e91c-48ea-9f39-cd78bc1ccb4b', '8d7ebdc6-e22c-472f-bfba-69dbadacca66', 'd5c9bfc8-6a37-4865-98e5-c3b87f5511b3', 'f1343f77-c7fb-4ac1-8ff2-2d5f2259e98e', 'de3dfef9-fca9-44cf-a875-a32d09886674', 'fda68d80-8522-4c05-9ccb-4e3f0fb94dce');

-- UT: Vipers FC (2 teams)
UPDATE teams SET club_name = 'Vipers FC'
WHERE team_id_master IN ('8029f292-4913-453b-9e91-47a8e013f20e', '1b99635c-1440-4604-8d69-866aa7933ea2');

-- UT: Wasatch SC (28 teams)
UPDATE teams SET club_name = 'Wasatch SC'
WHERE team_id_master IN ('41b25e14-5027-4cd3-95f1-02244501e73e', '09b683f3-031a-49fc-af4d-b3dbb7c8e5ff', 'ad873671-4bff-44e6-9c37-b9f5e7ed27a0', '5d631f1a-f8d6-41c6-b342-ee6062914f2f', '7ba4607d-a3b9-43d8-81e0-defdc90c0d4b', '5a980ac0-0a30-4327-aa78-093721096d2a', 'cb020b86-8c9e-46d8-9025-95767cab568c', '5cb5b2b3-7043-4319-85c0-126544da679d', 'c8ef7a49-62d3-4dfd-8773-0ec308342041', '7158751a-1fdc-4d10-a0d5-ae3035eb2485', '402cb5b0-431e-412e-8a4e-dd7c46a17177', 'd39f6e94-4e4d-42bd-a106-27842c9ab72c', '6cf8db40-6579-4356-a71d-daf1ef8c2afc', '742d7894-2286-43e0-bbb7-c6fbad36b36c', '9e641ec1-4c82-413d-9433-db2b5e1b1e2e', 'e4f144e3-8f2b-437a-b50d-6aab3a4b7a16', '75f111e9-5d2d-48eb-bebf-71b7cf409264', 'eb5e6862-6fc7-4757-86db-5824f5e18584', '0772f07b-94bf-46d1-a77a-9421c3a62d5b', 'a43f4151-a7c9-4eb5-b1ed-b0e158e00db3', '9e892738-726e-4c26-a995-09b58ccdb059', 'd0dd269c-4d22-4552-b3b8-e274383066f6', 'a35921a4-aafa-4033-a399-a94014bcc60f', '2f6c3783-5f72-40d7-9b1c-4ee60281e832', 'd4a130f8-6a90-4fed-81e2-3e88964bc1df', 'c031947a-4c79-4d4a-aaab-6f6641261e79', '378f0de1-3505-4fc4-bcf2-ad6b27fa4a1b', '3b571288-ac26-480a-9ad1-b7deff8735c0');

-- VA: Arlington SA (1 teams)
UPDATE teams SET club_name = 'Arlington SA'
WHERE team_id_master IN ('bed77fc0-772a-41e7-bf5a-0d831daf20e6');

-- VA: Beach FC (2 teams)
UPDATE teams SET club_name = 'Beach FC'
WHERE team_id_master IN ('2ce8471c-e17c-4068-9a77-6808b8ef031a', 'b6ade749-308e-47af-8271-41896e39b351');

-- VA: Blue Ridge United (3 teams)
UPDATE teams SET club_name = 'Blue Ridge United'
WHERE team_id_master IN ('16a4abb8-da7a-4275-b4cf-f5d6ed5197ad', '6108a734-fa66-4bf9-9abc-a0f9f64a1f4d', '84cb1e9b-c641-43ac-9996-70215d8f7a67');

-- VA: FC Dulles (1 teams)
UPDATE teams SET club_name = 'FC Dulles'
WHERE team_id_master IN ('80c9ef29-4bdd-4893-8cac-b840284087ca');

-- VA: Golden Ball Soccer Academy (1 teams)
UPDATE teams SET club_name = 'Golden Ball Soccer Academy'
WHERE team_id_master IN ('55e2c32c-87d3-4d6a-a87b-80e921719686');

-- VA: McLean YS (1 teams)
UPDATE teams SET club_name = 'McLean YS'
WHERE team_id_master IN ('4297b31d-7973-468a-9f06-05d887d7b4d7');

-- VA: Virginia United FC (2 teams)
UPDATE teams SET club_name = 'Virginia United FC'
WHERE team_id_master IN ('f692e1dd-f465-4839-8d86-17bf9bc3ae87', '836a56d1-e7d7-491b-9144-033c3a651d11');

-- VT: Queen City FC (1 teams)
UPDATE teams SET club_name = 'Queen City FC'
WHERE team_id_master IN ('e7ac2743-432c-4059-9835-3b1fe3dc63f1');

-- VT: VT Northern United (1 teams)
UPDATE teams SET club_name = 'VT Northern United'
WHERE team_id_master IN ('c79fdeb4-9222-48b7-932c-405969c9c65b');

-- WA: Bainbridge Island FC (3 teams)
UPDATE teams SET club_name = 'Bainbridge Island FC'
WHERE team_id_master IN ('15df05ce-9857-4598-be6b-cff8c80315a1', '9c12f098-5e13-4ed8-be81-f221f808cbc9', 'e7115df0-8b7c-41c4-af7d-511cc7bb04fe');

-- WA: Blackhills FC (1 teams)
UPDATE teams SET club_name = 'Blackhills FC'
WHERE team_id_master IN ('c12667b2-de06-4f39-bced-3ade3f124056');

-- WA: Cascade FC (7 teams)
UPDATE teams SET club_name = 'Cascade FC'
WHERE team_id_master IN ('c94011ca-59bb-49b8-b152-b4033c28876a', 'd3e336b4-c952-4716-bebf-67c8e11c03d0', '514f3b90-d691-46d6-a6e4-52d2cb564426', 'f24b7e9f-427e-4848-a703-95de200e1a80', 'b9026cbc-27c8-427b-8d53-8782298c6d63', '5c48cc16-bb86-4daa-979c-4b209b05f51c', '2e8ec481-3e12-4905-bba8-84cddf7421ae');

-- WA: Columbia Premier Soccer Club (9 teams)
UPDATE teams SET club_name = 'Columbia Premier Soccer Club'
WHERE team_id_master IN ('b38df89b-3493-4ef1-8cdf-50e87d73f893', '9f3a9282-d9e2-41df-91bc-5e73bb0ff60a', 'e0b4a465-611b-47ee-aa8a-1c927b59ea98', '52d584fd-f974-402d-8b56-d0eae0dd0735', '597e5ac0-85d8-4fb0-b86a-58239b2a706f', 'cf4bd716-f719-4a37-b422-57a720819c19', '9ed5a204-4a55-4450-a65c-1d956264407a', '7d4cf666-35f3-41d1-9774-8ce2e034f5f4', '413e02e7-99f3-4def-b0df-d8f49c5d6056');

-- WA: Crossfire Select (2 teams)
UPDATE teams SET club_name = 'Crossfire Select'
WHERE team_id_master IN ('d888605b-5e93-4acd-9384-da2ffc880e50', '72910b7d-091a-4710-a393-766537ff1dbc');

-- WA: Eastside FC (10 teams)
UPDATE teams SET club_name = 'Eastside FC'
WHERE team_id_master IN ('158ab187-798b-4c51-a56b-4f7e598e0d85', '46fd5930-cc22-4f9d-a265-7c7f918fbdd3', 'c76ad40c-117d-4a09-a5f4-ecc592f98260', '60d0c024-8cab-4bdc-a9e6-c5ed46f086f9', '2cec65f7-a6b7-4b77-a8b3-92a0a5aef304', '45700bd5-76fe-4ef6-80b8-fcd511275e66', '22b4f37e-9573-46f0-9a50-69b6fb23be2c', 'f690c588-8fbe-43d6-9033-21224ccb7fb5', 'fea99886-c3b6-44e9-9d82-0ce2e1f0dbb3', '61baa1ab-a4ac-475b-9411-2e8feeb6227e');

-- WA: FC Salmon Creek (2 teams)
UPDATE teams SET club_name = 'FC Salmon Creek'
WHERE team_id_master IN ('beaf91a5-025d-4492-a83f-fd78b59a6085', '37994092-3ae4-49f7-9846-83ac853fb522');

-- WA: Issaquah FC (3 teams)
UPDATE teams SET club_name = 'Issaquah FC'
WHERE team_id_master IN ('6d09f6fa-f200-4e02-af30-8d5ffb72ca63', '7d037212-a604-436c-9af7-d8d9596c879d', '0eed8c96-2a94-4638-91e3-a526775a4539');

-- WA: Pac NW (2 teams)
UPDATE teams SET club_name = 'Pac NW'
WHERE team_id_master IN ('f5dfadf0-3257-4367-935d-726431ece712', '1ed96e5b-3083-43ff-881d-78a2a0368a70');

-- WA: PacNW (4 teams)
UPDATE teams SET club_name = 'PacNW'
WHERE team_id_master IN ('29eb704e-6f8b-45ad-92be-25db2437b8af', 'daff1a43-910c-45ec-a073-4a39cc7e21ca', '489a3eec-9ae5-41b9-8c3b-4bbf17710334', 'c3324680-7c41-4a5b-8689-a3c0aa73060f');

-- WA: Pacific FC (11 teams)
UPDATE teams SET club_name = 'Pacific FC'
WHERE team_id_master IN ('16c6cec0-8c86-4910-961a-e8791ba3c333', '2075df3f-b4c9-4b30-81a1-15402fe56cd0', '527855fe-c99d-4c64-9ddb-f68e0b2882cc', '9870e27e-ef89-4723-ac3a-bb17ef7e9afe', 'f2dcec76-75d0-45b8-b460-45551dffa9b5', '9cb1e38a-11f3-436d-9ee6-1da8187419a1', 'c2bd0f2d-3d6c-44c7-b8d3-d37e23b542d1', '911cea49-1eed-4974-ba37-bead5a303e59', '62ba2777-c865-4d53-a8e6-80ab0fb4aab0', '886f9df4-898b-4090-ba12-90523255658d', '71304711-d5eb-4a5c-92c5-77c490d951b9');

-- WA: Seattle United (9 teams)
UPDATE teams SET club_name = 'Seattle United'
WHERE team_id_master IN ('691de689-3b0c-4618-8052-5ec23f478c3f', 'a2957301-9817-43d1-9909-307515de7454', '46a2718d-ebde-4d86-8067-348a90f81dbe', '13c130ca-e278-4cf4-bbe7-2d1d11fec45f', '281e9272-ae7f-4770-9834-dd76f31bba48', 'd5d2d73f-9033-4c8a-b79f-f0b06d0e8058', 'bc2e6544-1299-4d66-bd01-88d27ac69374', 'd3244c92-7a95-48dd-a7ec-2b7b8df87df6', '4011d6f8-bf04-4636-8e71-2fe49bdd3c5f');

-- WA: Valor Soccer (1 teams)
UPDATE teams SET club_name = 'Valor Soccer'
WHERE team_id_master IN ('f2733213-d3b3-44cb-8c9b-8a97ad936731');

-- WA: Washington Premier (1 teams)
UPDATE teams SET club_name = 'Washington Premier'
WHERE team_id_master IN ('8d0cb71e-fa82-46c5-ae64-e4d0b617f703');

-- WI: AC Toros (1 teams)
UPDATE teams SET club_name = 'AC Toros'
WHERE team_id_master IN ('0e380a00-fb7d-4545-af88-c08b54a7f02e');

-- WI: ACE SC (2 teams)
UPDATE teams SET club_name = 'ACE SC'
WHERE team_id_master IN ('691756d2-6247-4e1b-b9f8-45813199dac5', '142181a2-03b3-491e-9790-a3151ab94e69');

-- WI: Capital East SC (7 teams)
UPDATE teams SET club_name = 'Capital East SC'
WHERE team_id_master IN ('bf4faa1a-99ab-4a13-bc04-c3b1ccb4a656', '25979894-b550-4de5-976e-3709fd3e89ee', 'a3a63dd7-6d75-4432-b1ca-89f0d5740240', '39d238fe-c072-4048-a017-eed09593f3e6', '1afeb635-86dd-43fb-aff7-80e0b94b9de9', '3b0c25cd-75ab-46dd-a076-e0fe0c2a5240', 'abf08248-cbe7-490b-a33b-a05594d85276');

-- WI: Edgerton Youth SA (1 teams)
UPDATE teams SET club_name = 'Edgerton Youth SA'
WHERE team_id_master IN ('8b19972e-bf1f-414e-a933-94f850cd8f17');

-- WI: Elmbrook United (1 teams)
UPDATE teams SET club_name = 'Elmbrook United'
WHERE team_id_master IN ('e7a53b18-ee98-4245-b27a-43484996529d');

-- WI: Legacy FC (1 teams)
UPDATE teams SET club_name = 'Legacy FC'
WHERE team_id_master IN ('cb7e95ad-04ca-4314-97ad-6786d79c6d8e');

-- WI: Madison 56ers (1 teams)
UPDATE teams SET club_name = 'Madison 56ers'
WHERE team_id_master IN ('4d8a70d0-6d16-4ad2-abea-8c1a66e241a2');

-- WI: Magic Soccer Club (4 teams)
UPDATE teams SET club_name = 'Magic Soccer Club'
WHERE team_id_master IN ('3bbe23c1-829b-4d3e-bc74-3bf974369fae', '090b4b04-fb07-4b38-bd72-ee3f135018ce', '9a19561f-9d2d-497d-95db-fc1ab048f211', 'afb41ed2-79db-4159-81ed-de60ae706cd6');

-- WI: McFarland Soccer Club (7 teams)
UPDATE teams SET club_name = 'McFarland Soccer Club'
WHERE team_id_master IN ('606d2e4e-ac51-4c2f-80f6-f1d15cfe1df7', '98bbd328-3ee9-4c32-bf71-8121faa87a26', '40eb76e0-7c85-454b-834b-25cac37e8237', '74fb0746-08a1-48a4-be78-f9bf76b57c1a', 'fbe3b177-f40d-44a7-a462-4c6c30c895e9', '9c58564e-70c6-47ad-bc24-50a17e7bc55d', 'eaffe997-391b-4787-99bc-89354b10309d');

-- WI: Middleton United Soccer Club (5 teams)
UPDATE teams SET club_name = 'Middleton United Soccer Club'
WHERE team_id_master IN ('bb55053f-cbb7-4d8f-bc20-d624cf9adf05', 'a66ce748-a6b1-4e71-827f-a72e13d2b5be', '3e2c2a6f-1e7a-4f38-b712-24db43f132f0', '06ace890-4992-4b18-9b10-88ca90102042', '30931f28-f792-4c01-b2a4-633b1db7ea51');

-- WI: Milton Soccer Club (1 teams)
UPDATE teams SET club_name = 'Milton Soccer Club'
WHERE team_id_master IN ('da1b9514-ac5e-4e6c-be57-77efcd42dba0');

-- WI: Mount Horeb Youth Soccer Club (2 teams)
UPDATE teams SET club_name = 'Mount Horeb Youth Soccer Club'
WHERE team_id_master IN ('1613a893-1c9e-4b3e-9c82-bfd706f53d09', 'a0702328-71bb-4465-9d27-3aa9f9e34bf6');

-- WI: North Shore United (1 teams)
UPDATE teams SET club_name = 'North Shore United'
WHERE team_id_master IN ('9a05b068-a6a7-47bc-9af1-e177be8c6a2f');

-- WI: Oregon SC (6 teams)
UPDATE teams SET club_name = 'Oregon SC'
WHERE team_id_master IN ('7aedd53f-170b-401b-a614-f83e04449fcd', '80ac32e0-7b34-4fff-bfae-7b74890583d6', '22bd4d1f-1d59-4230-9409-504549abdeae', '0c63f9cd-85ec-4aed-8d54-d7b10db84d60', 'b94a5fcf-2c31-4f7a-b8c3-c87737f3e549', '11842a1a-8f14-4fa9-bbc4-1dc6baeae685');

-- WI: Platteville Power Soccer Club (2 teams)
UPDATE teams SET club_name = 'Platteville Power Soccer Club'
WHERE team_id_master IN ('c81d8c6f-da35-42a4-bf0d-a9c03ffaaa26', '0fb04265-e2f7-4783-9956-15eb9004ff88');

-- WI: RUSH WI Southeast (1 teams)
UPDATE teams SET club_name = 'RUSH WI Southeast'
WHERE team_id_master IN ('c77ec9cf-d73f-4eb4-81e9-4c17a7e371bd');

-- WI: River Valley Soccer Association (1 teams)
UPDATE teams SET club_name = 'River Valley Soccer Association'
WHERE team_id_master IN ('1d827bfd-525a-462b-85f3-0f62c29de984');

-- WI: Rock SC Rush (7 teams)
UPDATE teams SET club_name = 'Rock SC Rush'
WHERE team_id_master IN ('6cf70c69-6f32-49b7-8471-b7aad0a22ea4', '581c54b5-1a47-4f48-8c9c-8916906a3639', 'fa6f3954-19b5-43fa-a7c0-7f1f998c9a9e', '81d8f803-5a07-42ec-86f8-3e69d4778735', 'a5994a49-1ce8-4c18-b102-9afe95c00123', '05f2c6ee-fdc0-42e8-93b0-8d804c3e676d', '5914c0fe-c6d7-4a40-8ec3-15bdfab0a584');

-- WI: SC Wave (15 teams)
UPDATE teams SET club_name = 'SC Wave'
WHERE team_id_master IN ('b94f14f6-304d-4412-85f8-241bcfbc7f53', '4140dca4-2ef0-4ecb-a570-ab4b0f34ca5c', 'bfb35108-a02e-447c-91f2-a534b02838e4', '529216a0-6e97-441b-8916-108c8c87ebef', '37fc38f7-d359-4823-b055-c2418406e8d1', '3d43d527-521c-4170-8691-9f21c577af31', '53e510e7-4eee-4a1f-bce1-e41faf416d89', 'a0d5bef9-b1b2-402a-a569-b05accf05522', 'aaaf5597-d5a2-4e74-b8a1-603289a73a8d', 'd38960bc-93f3-4a47-9740-7a5fcb8217f5', '9be9fa0b-db20-436a-a87e-7a9dd8395be6', '904860b8-9ab4-423e-9df1-bc6f4c666bab', '0c6af906-58ba-4039-8b71-b3de8b373ba6', '72b11fd9-7bce-4229-9437-7563a36822c0', '117721e7-47b8-48e7-aca4-9c8eb7914672');

-- WI: Sauk Prairie Strikers (3 teams)
UPDATE teams SET club_name = 'Sauk Prairie Strikers'
WHERE team_id_master IN ('0a6624a1-2007-4ccf-8b3c-f0da9268a453', '5a82fe46-451a-431a-bc37-b1229f30b19e', 'd6c04037-a26a-4f13-9042-0e1cdab1b715');

-- WI: Sonic Sport Club (1 teams)
UPDATE teams SET club_name = 'Sonic Sport Club'
WHERE team_id_master IN ('2c16533c-98e4-4ca3-9b9a-df2545ace210');

-- WI: Sugar River SC (1 teams)
UPDATE teams SET club_name = 'Sugar River SC'
WHERE team_id_master IN ('69917d2d-36b7-4b66-8651-20be91d83389');

-- WI: TikiTaka Academy (3 teams)
UPDATE teams SET club_name = 'TikiTaka Academy'
WHERE team_id_master IN ('d1e5368f-4dec-4153-a2f4-1108fd0454fb', '6c6b4b2c-59fd-4f44-8fd6-63e652840389', '81f898b5-a54b-455f-ac79-42d5050bc542');

-- WI: Verona Soccer Club (5 teams)
UPDATE teams SET club_name = 'Verona Soccer Club'
WHERE team_id_master IN ('3eaefdf9-60dc-4f09-a161-20298b78034b', '3ee8ff75-efd2-46d0-8ed4-417834da28e1', '825d80ee-544e-4c14-bf7f-4b7487aa2533', '8c1c3aee-6029-4384-bd8e-bd7b489c08ae', '916fcd49-3ae6-4a13-91bf-685d14cb11fc');

-- WI: Waunakee Area Soccer Club (1 teams)
UPDATE teams SET club_name = 'Waunakee Area Soccer Club'
WHERE team_id_master IN ('2f9ab1c4-b0b8-4d6c-a2ce-91f57a9829da');

-- WV: East River Soccer Club (2 teams)
UPDATE teams SET club_name = 'East River Soccer Club'
WHERE team_id_master IN ('cc99794d-132a-4dba-8360-22f7c9047c5c', '7f3089f2-ea11-44b9-a4da-afcf93f84de9');
