// AUTO-GENERATED by scripts/generate_state_report.py — do not edit by hand.
export const report = {
  "state": "TX",
  "stateName": "Texas",
  "year": 2026,
  "slug": "state-of-texas-youth-soccer-2026",
  "generatedAt": "2026-06-22",
  "windowBucket": 30,
  "temporalCoverage": "2025-06-22/2026-06-22",
  "rankedTeams": 10783,
  "matchesAnalyzed": 117747,
  "totalGroups": 18,
  "genderSplit": {
    "male": 7134,
    "female": 3649
  },
  "deepestAgeGroup": {
    "ageGroup": "u10",
    "count": 1819
  },
  "ageGroups": [
    {
      "ageGroup": "u10",
      "count": 1819
    },
    {
      "ageGroup": "u12",
      "count": 1769
    },
    {
      "ageGroup": "u11",
      "count": 1716
    },
    {
      "ageGroup": "u13",
      "count": 1429
    },
    {
      "ageGroup": "u14",
      "count": 1260
    },
    {
      "ageGroup": "u15",
      "count": 958
    },
    {
      "ageGroup": "u16",
      "count": 705
    },
    {
      "ageGroup": "u19",
      "count": 637
    },
    {
      "ageGroup": "u17",
      "count": 490
    }
  ],
  "leagues": [
    {
      "league": "ECNL_RL",
      "count": 872
    },
    {
      "league": "ECNL",
      "count": 197
    },
    {
      "league": "NPL",
      "count": 167
    },
    {
      "league": "MLS_NEXT_AD",
      "count": 76
    },
    {
      "league": "DPL",
      "count": 60
    },
    {
      "league": "MLS_NEXT_HD",
      "count": 41
    },
    {
      "league": "ASPIRE",
      "count": 37
    },
    {
      "league": "GA",
      "count": 37
    },
    {
      "league": "NL",
      "count": 34
    },
    {
      "league": "EA",
      "count": 8
    }
  ],
  "topMovers": {
    "up": [
      {
        "teamName": "El Paso Locomotive FC - 2016 Locomotive EPPL Lopez",
        "clubName": "El Paso Locomotive FC",
        "league": null,
        "distinction": "locomotive|eppl|lopez",
        "ageGroup": "u10",
        "gender": "Male",
        "rankChange": 295,
        "currentRank": 12
      },
      {
        "teamName": "FC Dallas Midland-Odessa 2012/13 B",
        "clubName": "FC Dallas Midland-Odessa",
        "league": null,
        "distinction": null,
        "ageGroup": "u14",
        "gender": "Male",
        "rankChange": 246,
        "currentRank": 66
      },
      {
        "teamName": "Solar 2013 Tremblay RLNTX",
        "clubName": "Solar SC",
        "league": null,
        "distinction": "tremblay|rlntx",
        "ageGroup": "u13",
        "gender": "Male",
        "rankChange": 245,
        "currentRank": 41
      },
      {
        "teamName": "GC Academy 2016 White",
        "clubName": "Gulf Coast SC",
        "league": null,
        "distinction": "white|gc",
        "ageGroup": "u10",
        "gender": "Male",
        "rankChange": 243,
        "currentRank": 78
      },
      {
        "teamName": "Spindletop Youth Soccer Association - OC NABOR Kaos 2013 D2",
        "clubName": "Spindletop Youth Soccer Association",
        "league": null,
        "distinction": "association|d2|kaos|nabor",
        "ageGroup": "u13",
        "gender": "Male",
        "rankChange": 228,
        "currentRank": 75
      }
    ],
    "down": [
      {
        "teamName": "ID Houston Allstars 2013 NLFC TX-S",
        "clubName": "Inwood SC",
        "league": null,
        "distinction": "nlfc|south|allstars|houston",
        "ageGroup": "u13",
        "gender": "Male",
        "rankChange": -77,
        "currentRank": 100
      },
      {
        "teamName": "Aspire FC - AFC 2007 Black EDPL",
        "clubName": "Aspire FC",
        "league": "ASPIRE",
        "distinction": "black|edpl|afc",
        "ageGroup": "u19",
        "gender": "Female",
        "rankChange": -77,
        "currentRank": 93
      },
      {
        "teamName": "Dallas Hornets Texas DFW 2009",
        "clubName": "Dallas Hornets",
        "league": null,
        "distinction": "dfw",
        "ageGroup": "u17",
        "gender": "Male",
        "rankChange": -72,
        "currentRank": 88
      },
      {
        "teamName": "Sting NPL NTX 2013 Pitcock/C Rodriguez",
        "clubName": "Sting Soccer Club",
        "league": "NPL",
        "distinction": "c|pitcock|rodriguez",
        "ageGroup": "u13",
        "gender": "Male",
        "rankChange": -71,
        "currentRank": 90
      },
      {
        "teamName": "Sting 2013 Robles",
        "clubName": "Sting Soccer Club",
        "league": null,
        "distinction": "robles",
        "ageGroup": "u13",
        "gender": "Female",
        "rankChange": -68,
        "currentRank": 99
      }
    ]
  },
  "leagueCallouts": [
    {
      "teamName": "Liverpool FC Houston U17 EA",
      "clubName": "Liverpool FC Texas",
      "league": "EA",
      "distinction": "houston",
      "ageGroup": "u17",
      "gender": "Male"
    },
    {
      "teamName": "Sting Black ECNL 2009",
      "clubName": "Sting Soccer Club",
      "league": "ECNL",
      "distinction": "black",
      "ageGroup": "u17",
      "gender": "Female"
    },
    {
      "teamName": "2010 North NL TX-S",
      "clubName": "HTX",
      "league": "NL",
      "distinction": "north|south|nl",
      "ageGroup": "u16",
      "gender": "Female"
    }
  ]
} as const;
