-- Club Name Standardization: Female Teams (All States)
-- Generated by analyze_female_clubs.py
-- IMPORTANT: Every UPDATE filters by state_code AND gender='Female'

BEGIN;

-- === AK ===
-- [VARIATION] "Cook Inlet SC" → "Cook Inlet Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Cook Inlet Soccer Club' WHERE club_name = 'Cook Inlet SC' AND state_code = 'AK' AND gender = 'Female';


-- === AL ===
-- [CAPS] "ALBION SC Merced" → "Albion SC Merced" (1 teams)
UPDATE teams SET club_name = 'Albion SC Merced' WHERE club_name = 'ALBION SC Merced' AND state_code = 'AL' AND gender = 'Female';

-- [CAPS] "VERO FC" → "Vero FC" (3 teams)
UPDATE teams SET club_name = 'Vero FC' WHERE club_name = 'VERO FC' AND state_code = 'AL' AND gender = 'Female';


-- === AR ===
-- [CAPS] "AVSA" → "Avsa" (3 teams)
UPDATE teams SET club_name = 'Avsa' WHERE club_name = 'AVSA' AND state_code = 'AR' AND gender = 'Female';

-- [VARIATION] "Arkansas Rising" → "Arkansas Rising Soccer Club" (8 teams)
UPDATE teams SET club_name = 'Arkansas Rising Soccer Club' WHERE club_name = 'Arkansas Rising' AND state_code = 'AR' AND gender = 'Female';


-- === AZ ===
-- [CAPS] "AYSO United (AZ)" → "AYSO United (Az)" (21 teams)
UPDATE teams SET club_name = 'AYSO United (Az)' WHERE club_name = 'AYSO United (AZ)' AND state_code = 'AZ' AND gender = 'Female';

-- [CAPS] "AZFC" → "Azfc" (2 teams)
UPDATE teams SET club_name = 'Azfc' WHERE club_name = 'AZFC' AND state_code = 'AZ' AND gender = 'Female';

-- [VARIATION] "Arizona Arsenal" → "Arizona Arsenal Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Arizona Arsenal Soccer Club' WHERE club_name = 'Arizona Arsenal' AND state_code = 'AZ' AND gender = 'Female';

-- [CAPS] "Cochise United (AZ)" → "Cochise United (Az)" (1 teams)
UPDATE teams SET club_name = 'Cochise United (Az)' WHERE club_name = 'Cochise United (AZ)' AND state_code = 'AZ' AND gender = 'Female';

-- [CAPS] "FBSL" → "Fbsl" (14 teams)
UPDATE teams SET club_name = 'Fbsl' WHERE club_name = 'FBSL' AND state_code = 'AZ' AND gender = 'Female';

-- [VARIATION] "FC Tucson Youth SC" → "FC Tucson Youth Soccer" (1 teams)
UPDATE teams SET club_name = 'FC Tucson Youth Soccer' WHERE club_name = 'FC Tucson Youth SC' AND state_code = 'AZ' AND gender = 'Female';

-- [CAPS] "Next Level Soccer (AZ)" → "Next Level Soccer (Az)" (19 teams)
UPDATE teams SET club_name = 'Next Level Soccer (Az)' WHERE club_name = 'Next Level Soccer (AZ)' AND state_code = 'AZ' AND gender = 'Female';

-- [VARIATION] "Pima County SURF" → "Pima County Surf Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Pima County Surf Soccer Club' WHERE club_name = 'Pima County SURF' AND state_code = 'AZ' AND gender = 'Female';

-- [CAPS] "RSL-AZ" → "Rsl-Az" (2 teams)
UPDATE teams SET club_name = 'Rsl-Az' WHERE club_name = 'RSL-AZ' AND state_code = 'AZ' AND gender = 'Female';

-- [CAPS] "Sun Warriors AZFC" → "Sun Warriors Azfc" (1 teams)
UPDATE teams SET club_name = 'Sun Warriors Azfc' WHERE club_name = 'Sun Warriors AZFC' AND state_code = 'AZ' AND gender = 'Female';


-- === CA ===
-- [CAPS] "ACFC Soccer Academy" → "Acfc Soccer Academy" (1 teams)
UPDATE teams SET club_name = 'Acfc Soccer Academy' WHERE club_name = 'ACFC Soccer Academy' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC" → "Albion SC" (19 teams)
UPDATE teams SET club_name = 'Albion SC' WHERE club_name = 'ALBION SC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC Antelope Valley" → "Albion SC Antelope Valley" (9 teams)
UPDATE teams SET club_name = 'Albion SC Antelope Valley' WHERE club_name = 'ALBION SC Antelope Valley' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC Central Valley" → "Albion SC Central Valley" (8 teams)
UPDATE teams SET club_name = 'Albion SC Central Valley' WHERE club_name = 'ALBION SC Central Valley' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC Merced" → "Albion SC Merced" (5 teams)
UPDATE teams SET club_name = 'Albion SC Merced' WHERE club_name = 'ALBION SC Merced' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC Riverside" → "Albion SC Riverside" (11 teams)
UPDATE teams SET club_name = 'Albion SC Riverside' WHERE club_name = 'ALBION SC Riverside' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC San Diego" → "Albion SC San Diego" (34 teams)
UPDATE teams SET club_name = 'Albion SC San Diego' WHERE club_name = 'ALBION SC San Diego' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC Santa Ana" → "Albion SC Santa Ana" (2 teams)
UPDATE teams SET club_name = 'Albion SC Santa Ana' WHERE club_name = 'ALBION SC Santa Ana' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC Santa Monica" → "Albion SC Santa Monica" (24 teams)
UPDATE teams SET club_name = 'Albion SC Santa Monica' WHERE club_name = 'ALBION SC Santa Monica' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC Silicon Valley" → "Albion SC Silicon Valley" (7 teams)
UPDATE teams SET club_name = 'Albion SC Silicon Valley' WHERE club_name = 'ALBION SC Silicon Valley' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC Silicon Valley East Bay" → "Albion SC Silicon Valley East Bay" (9 teams)
UPDATE teams SET club_name = 'Albion SC Silicon Valley East Bay' WHERE club_name = 'ALBION SC Silicon Valley East Bay' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ALBION SC Silicon Valley San Mateo" → "Albion SC Silicon Valley San Mateo" (10 teams)
UPDATE teams SET club_name = 'Albion SC Silicon Valley San Mateo' WHERE club_name = 'ALBION SC Silicon Valley San Mateo' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "APFC" → "Apfc" (3 teams)
UPDATE teams SET club_name = 'Apfc' WHERE club_name = 'APFC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "AYSO United SoCal" → "AYSO United Socal" (1 teams)
UPDATE teams SET club_name = 'AYSO United Socal' WHERE club_name = 'AYSO United SoCal' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Alameda SC" → "Alameda Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Alameda Soccer Club' WHERE club_name = 'Alameda SC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Beach FC" → "Beach Futbol Club" (2 teams)
UPDATE teams SET club_name = 'Beach Futbol Club' WHERE club_name = 'Beach FC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Beach FC  (CA)" → "Beach FC (Ca)" (25 teams)
UPDATE teams SET club_name = 'Beach FC (Ca)' WHERE club_name = 'Beach FC  (CA)' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Beach United FC" → "Beach Futbol Club" (2 teams)
UPDATE teams SET club_name = 'Beach Futbol Club' WHERE club_name = 'Beach United FC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Burlingame SC" → "Burlingame Soccer Club" (4 teams)
UPDATE teams SET club_name = 'Burlingame Soccer Club' WHERE club_name = 'Burlingame SC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "CAL STARS" → "Cal Stars" (1 teams)
UPDATE teams SET club_name = 'Cal Stars' WHERE club_name = 'CAL STARS' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "CZ Elite (CA-S)" → "Cz Elite (Ca-S)" (3 teams)
UPDATE teams SET club_name = 'Cz Elite (Ca-S)' WHERE club_name = 'CZ Elite (CA-S)' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Castro Valley SC" → "Castro Valley Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Castro Valley Soccer Club' WHERE club_name = 'Castro Valley SC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Celtic Soccer Club (S-CA)" → "Celtic Soccer Club (S-Ca)" (4 teams)
UPDATE teams SET club_name = 'Celtic Soccer Club (S-Ca)' WHERE club_name = 'Celtic Soccer Club (S-CA)' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Central Coast FC" → "Central Coast United SC" (2 teams)
UPDATE teams SET club_name = 'Central Coast United SC' WHERE club_name = 'Central Coast FC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "City SC NOCO" → "City SC Noco" (1 teams)
UPDATE teams SET club_name = 'City SC Noco' WHERE club_name = 'City SC NOCO' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "DEPORTIVO BARCELONA SOCCER CLUB" → "Deportivo Barcelona Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Deportivo Barcelona Soccer Club' WHERE club_name = 'DEPORTIVO BARCELONA SOCCER CLUB' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "ELI7E FC" → "Eli7E FC" (9 teams)
UPDATE teams SET club_name = 'Eli7E FC' WHERE club_name = 'ELI7E FC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Eagles FC" → "Eagles Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Eagles Soccer Club' WHERE club_name = 'Eagles FC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Elite Fc" → "Elite FC" (1 teams)
UPDATE teams SET club_name = 'Elite FC' WHERE club_name = 'Elite Fc' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Elk Grove United Soccer Club" → "Elk Grove Soccer" (2 teams)
UPDATE teams SET club_name = 'Elk Grove Soccer' WHERE club_name = 'Elk Grove United Soccer Club' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "FASC" → "Fasc" (1 teams)
UPDATE teams SET club_name = 'Fasc' WHERE club_name = 'FASC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "FC Premier (CA)" → "FC Premier (Ca)" (21 teams)
UPDATE teams SET club_name = 'FC Premier (Ca)' WHERE club_name = 'FC Premier (CA)' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "FC Scorpions (CA)" → "FC Scorpions (Ca)" (3 teams)
UPDATE teams SET club_name = 'FC Scorpions (Ca)' WHERE club_name = 'FC Scorpions (CA)' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "FLYTE SC IE" → "Flyte SC Ie" (11 teams)
UPDATE teams SET club_name = 'Flyte SC Ie' WHERE club_name = 'FLYTE SC IE' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "FRAM SC" → "Fram SC" (30 teams)
UPDATE teams SET club_name = 'Fram SC' WHERE club_name = 'FRAM SC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "FRESNO HEAT FC" → "Fresno Heat FC" (7 teams)
UPDATE teams SET club_name = 'Fresno Heat FC' WHERE club_name = 'FRESNO HEAT FC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "FYSL" → "Fysl" (3 teams)
UPDATE teams SET club_name = 'Fysl' WHERE club_name = 'FYSL' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Fury FC (S-CA)" → "Fury FC (S-Ca)" (7 teams)
UPDATE teams SET club_name = 'Fury FC (S-Ca)' WHERE club_name = 'Fury FC (S-CA)' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Future FC (CAS)" → "Future FC (Cas)" (13 teams)
UPDATE teams SET club_name = 'Future FC (Cas)' WHERE club_name = 'Future FC (CAS)' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Imperial Valley Socal" → "Imperial Valley SoCal" (2 teams)
UPDATE teams SET club_name = 'Imperial Valley SoCal' WHERE club_name = 'Imperial Valley Socal' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "JOGA Bonito" → "Joga Bonito FC" (2 teams)
UPDATE teams SET club_name = 'Joga Bonito FC' WHERE club_name = 'JOGA Bonito' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "JUSA" → "Jusa" (3 teams)
UPDATE teams SET club_name = 'Jusa' WHERE club_name = 'JUSA' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "JUSA Select" → "Jusa Select" (1 teams)
UPDATE teams SET club_name = 'Jusa Select' WHERE club_name = 'JUSA Select' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Joga Bonito (CA)" → "Joga Bonito (Ca)" (6 teams)
UPDATE teams SET club_name = 'Joga Bonito (Ca)' WHERE club_name = 'Joga Bonito (CA)' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "LAFC So Cal" → "Lafc So Cal" (36 teams)
UPDATE teams SET club_name = 'Lafc So Cal' WHERE club_name = 'LAFC So Cal' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "LARC" → "Larc" (1 teams)
UPDATE teams SET club_name = 'Larc' WHERE club_name = 'LARC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "LASC-SCV" → "Lasc-Scv" (10 teams)
UPDATE teams SET club_name = 'Lasc-Scv' WHERE club_name = 'LASC-SCV' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "LMFC" → "Lmfc" (1 teams)
UPDATE teams SET club_name = 'Lmfc' WHERE club_name = 'LMFC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Legends FC (CA)" → "Legends FC (Ca)" (76 teams)
UPDATE teams SET club_name = 'Legends FC (Ca)' WHERE club_name = 'Legends FC (CA)' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Legends FC SD (DMCV)" → "Legends FC SD (Dmcv)" (35 teams)
UPDATE teams SET club_name = 'Legends FC SD (Dmcv)' WHERE club_name = 'Legends FC SD (DMCV)' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Legends FC-SFV" → "Legends Fc-Sfv" (1 teams)
UPDATE teams SET club_name = 'Legends Fc-Sfv' WHERE club_name = 'Legends FC-SFV' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Legends Futbol Academy" → "Legends FC" (2 teams)
UPDATE teams SET club_name = 'Legends FC' WHERE club_name = 'Legends Futbol Academy' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Los Angeles United FC" → "Los Angeles Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Los Angeles Soccer Club' WHERE club_name = 'Los Angeles United FC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Merced United" → "Merced United FC" (1 teams)
UPDATE teams SET club_name = 'Merced United FC' WHERE club_name = 'Merced United' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Monterey Surf SC" → "Monterey Surf Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Monterey Surf Soccer Club' WHERE club_name = 'Monterey Surf SC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Moorpark Soccer Club" → "Moorpark SC" (1 teams)
UPDATE teams SET club_name = 'Moorpark SC' WHERE club_name = 'Moorpark Soccer Club' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Mustang SC" → "Mustang Soccer" (17 teams)
UPDATE teams SET club_name = 'Mustang Soccer' WHERE club_name = 'Mustang SC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "North Coast FC" → "North Coast Futbol Club" (8 teams)
UPDATE teams SET club_name = 'North Coast Futbol Club' WHERE club_name = 'North Coast FC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "PYSL" → "Pysl" (3 teams)
UPDATE teams SET club_name = 'Pysl' WHERE club_name = 'PYSL' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "PYSL Blast SC" → "Pysl Blast SC" (17 teams)
UPDATE teams SET club_name = 'Pysl Blast SC' WHERE club_name = 'PYSL Blast SC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Pajaro Valley Youth SC" → "Pajaro Valley Youth Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Pajaro Valley Youth Soccer Club' WHERE club_name = 'Pajaro Valley Youth SC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Pateadores NB/CM" → "Pateadores Nb/Cm" (1 teams)
UPDATE teams SET club_name = 'Pateadores Nb/Cm' WHERE club_name = 'Pateadores NB/CM' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Piedmont Soccer Club" → "Piedmont SC" (1 teams)
UPDATE teams SET club_name = 'Piedmont SC' WHERE club_name = 'Piedmont Soccer Club' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "RENEGADES FC" → "Renegades FC" (1 teams)
UPDATE teams SET club_name = 'Renegades FC' WHERE club_name = 'RENEGADES FC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "Riverside MGFM Soccer Organization" → "Riverside Mgfm Soccer Organization" (2 teams)
UPDATE teams SET club_name = 'Riverside Mgfm Soccer Organization' WHERE club_name = 'Riverside MGFM Soccer Organization' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "SDSC Escondido" → "Sdsc Escondido" (4 teams)
UPDATE teams SET club_name = 'Sdsc Escondido' WHERE club_name = 'SDSC Escondido' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "SDSC Surf" → "Sdsc Surf" (59 teams)
UPDATE teams SET club_name = 'Sdsc Surf' WHERE club_name = 'SDSC Surf' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "SDSC Surf Escondido" → "Sdsc Surf Escondido" (10 teams)
UPDATE teams SET club_name = 'Sdsc Surf Escondido' WHERE club_name = 'SDSC Surf Escondido' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "SPORTING REVOLUTION FC" → "Sporting Revolution FC" (1 teams)
UPDATE teams SET club_name = 'Sporting Revolution FC' WHERE club_name = 'SPORTING REVOLUTION FC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "San Juan South SC" → "San Juan South Soccer Club" (4 teams)
UPDATE teams SET club_name = 'San Juan South Soccer Club' WHERE club_name = 'San Juan South SC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "So Cal Blues SC" → "So Cal Blues" (16 teams)
UPDATE teams SET club_name = 'So Cal Blues' WHERE club_name = 'So Cal Blues SC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Stanislaus United SC" → "Stanislaus United" (7 teams)
UPDATE teams SET club_name = 'Stanislaus United' WHERE club_name = 'Stanislaus United SC' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "Valley FC" → "Valley United SC" (1 teams)
UPDATE teams SET club_name = 'Valley United SC' WHERE club_name = 'Valley FC' AND state_code = 'CA' AND gender = 'Female';

-- [CAPS] "WESCO United" → "Wesco United" (10 teams)
UPDATE teams SET club_name = 'Wesco United' WHERE club_name = 'WESCO United' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "West Coast Soccer" → "West Coast FC" (9 teams)
UPDATE teams SET club_name = 'West Coast FC' WHERE club_name = 'West Coast Soccer' AND state_code = 'CA' AND gender = 'Female';

-- [VARIATION] "West Coast Soccer Club" → "West Coast FC" (8 teams)
UPDATE teams SET club_name = 'West Coast FC' WHERE club_name = 'West Coast Soccer Club' AND state_code = 'CA' AND gender = 'Female';


-- === CO ===
-- [CAPS] "ALBION SC Colorado" → "Albion SC Colorado" (25 teams)
UPDATE teams SET club_name = 'Albion SC Colorado' WHERE club_name = 'ALBION SC Colorado' AND state_code = 'CO' AND gender = 'Female';

-- [CAPS] "ALBION SC Denver" → "Albion SC Denver" (13 teams)
UPDATE teams SET club_name = 'Albion SC Denver' WHERE club_name = 'ALBION SC Denver' AND state_code = 'CO' AND gender = 'Female';

-- [CAPS] "Colorado EDGE" → "Colorado Edge" (29 teams)
UPDATE teams SET club_name = 'Colorado Edge' WHERE club_name = 'Colorado EDGE' AND state_code = 'CO' AND gender = 'Female';

-- [VARIATION] "Colorado EDGE SC" → "Colorado Edge" (6 teams)
UPDATE teams SET club_name = 'Colorado Edge' WHERE club_name = 'Colorado EDGE SC' AND state_code = 'CO' AND gender = 'Female';

-- [VARIATION] "Pueblo Rangers" → "Pueblo Rangers SC" (1 teams)
UPDATE teams SET club_name = 'Pueblo Rangers SC' WHERE club_name = 'Pueblo Rangers' AND state_code = 'CO' AND gender = 'Female';

-- [VARIATION] "Westy Soccer" → "Westy Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Westy Soccer Club' WHERE club_name = 'Westy Soccer' AND state_code = 'CO' AND gender = 'Female';


-- === CT ===
-- [CAPS] "JCFC Academy" → "Jcfc Academy" (1 teams)
UPDATE teams SET club_name = 'Jcfc Academy' WHERE club_name = 'JCFC Academy' AND state_code = 'CT' AND gender = 'Female';

-- [CAPS] "OGRCC" → "Ogrcc" (4 teams)
UPDATE teams SET club_name = 'Ogrcc' WHERE club_name = 'OGRCC' AND state_code = 'CT' AND gender = 'Female';


-- === DE ===
-- [CAPS] "ALBION SC Delaware" → "Albion SC Delaware" (1 teams)
UPDATE teams SET club_name = 'Albion SC Delaware' WHERE club_name = 'ALBION SC Delaware' AND state_code = 'DE' AND gender = 'Female';

-- [VARIATION] "Delaware FC" → "Delaware Futbol Academy" (2 teams)
UPDATE teams SET club_name = 'Delaware Futbol Academy' WHERE club_name = 'Delaware FC' AND state_code = 'DE' AND gender = 'Female';


-- === FL ===
-- [CAPS] "ALBION SC Miami" → "Albion SC Miami" (3 teams)
UPDATE teams SET club_name = 'Albion SC Miami' WHERE club_name = 'ALBION SC Miami' AND state_code = 'FL' AND gender = 'Female';

-- [CAPS] "AVENTURA F.C. BOLD NATION" → "Aventura F.C. Bold Nation" (2 teams)
UPDATE teams SET club_name = 'Aventura F.C. Bold Nation' WHERE club_name = 'AVENTURA F.C. BOLD NATION' AND state_code = 'FL' AND gender = 'Female';

-- [VARIATION] "Cape Coral SA" → "Cape Coral Soccer" (7 teams)
UPDATE teams SET club_name = 'Cape Coral Soccer' WHERE club_name = 'Cape Coral SA' AND state_code = 'FL' AND gender = 'Female';

-- [CAPS] "EJE7" → "Eje7" (4 teams)
UPDATE teams SET club_name = 'Eje7' WHERE club_name = 'EJE7' AND state_code = 'FL' AND gender = 'Female';

-- [VARIATION] "Florida Hawks FC" → "Florida Hawks Futbol Club" (3 teams)
UPDATE teams SET club_name = 'Florida Hawks Futbol Club' WHERE club_name = 'Florida Hawks FC' AND state_code = 'FL' AND gender = 'Female';

-- [CAPS] "Naples City UDAG FC" → "Naples City Udag FC" (1 teams)
UPDATE teams SET club_name = 'Naples City Udag FC' WHERE club_name = 'Naples City UDAG FC' AND state_code = 'FL' AND gender = 'Female';

-- [CAPS] "OCSS Windermere & Clermont" → "Ocss Windermere & Clermont" (2 teams)
UPDATE teams SET club_name = 'Ocss Windermere & Clermont' WHERE club_name = 'OCSS Windermere & Clermont' AND state_code = 'FL' AND gender = 'Female';

-- [CAPS] "RONALDO ACADEMY TAMPA BAY" → "Ronaldo Academy Tampa Bay" (2 teams)
UPDATE teams SET club_name = 'Ronaldo Academy Tampa Bay' WHERE club_name = 'RONALDO ACADEMY TAMPA BAY' AND state_code = 'FL' AND gender = 'Female';

-- [CAPS] "SABR - Team Boca" → "Sabr - Team Boca" (19 teams)
UPDATE teams SET club_name = 'Sabr - Team Boca' WHERE club_name = 'SABR - Team Boca' AND state_code = 'FL' AND gender = 'Female';

-- [CAPS] "SWFL Surge" → "Swfl Surge" (1 teams)
UPDATE teams SET club_name = 'Swfl Surge' WHERE club_name = 'SWFL Surge' AND state_code = 'FL' AND gender = 'Female';

-- [CAPS] "VENICE SC" → "Venice SC" (5 teams)
UPDATE teams SET club_name = 'Venice SC' WHERE club_name = 'VENICE SC' AND state_code = 'FL' AND gender = 'Female';

-- [VARIATION] "Wellington Soccer Club" → "Wellington SC" (8 teams)
UPDATE teams SET club_name = 'Wellington SC' WHERE club_name = 'Wellington Soccer Club' AND state_code = 'FL' AND gender = 'Female';


-- === GA ===
-- [VARIATION] "Alliance Soccer Club" → "Alliance SC" (3 teams)
UPDATE teams SET club_name = 'Alliance SC' WHERE club_name = 'Alliance Soccer Club' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "Augusta Arsenal SC (GA)" → "Augusta Arsenal SC (Ga)" (8 teams)
UPDATE teams SET club_name = 'Augusta Arsenal SC (Ga)' WHERE club_name = 'Augusta Arsenal SC (GA)' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "Augusta Arsenal SC (SC)" → "Augusta Arsenal SC (Sc)" (2 teams)
UPDATE teams SET club_name = 'Augusta Arsenal SC (Sc)' WHERE club_name = 'Augusta Arsenal SC (SC)' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "Decatur-DeKalb YMCA Soccer Club" → "Decatur-Dekalb Ymca Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Decatur-Dekalb Ymca Soccer Club' WHERE club_name = 'Decatur-DeKalb YMCA Soccer Club' AND state_code = 'GA' AND gender = 'Female';

-- [VARIATION] "Legion FC" → "Legion Futbol Club" (1 teams)
UPDATE teams SET club_name = 'Legion Futbol Club' WHERE club_name = 'Legion FC' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "Madison Area YMCA" → "Madison Area Ymca" (2 teams)
UPDATE teams SET club_name = 'Madison Area Ymca' WHERE club_name = 'Madison Area YMCA' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "Metro Atlanta YMCA Soccer" → "Metro Atlanta Ymca Soccer" (2 teams)
UPDATE teams SET club_name = 'Metro Atlanta Ymca Soccer' WHERE club_name = 'Metro Atlanta YMCA Soccer' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "NASA Tophat" → "Nasa Tophat" (84 teams)
UPDATE teams SET club_name = 'Nasa Tophat' WHERE club_name = 'NASA Tophat' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "OTOF FC" → "Otof FC" (1 teams)
UPDATE teams SET club_name = 'Otof FC' WHERE club_name = 'OTOF FC' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "Rapids FC (GA)" → "Rapids FC (Ga)" (6 teams)
UPDATE teams SET club_name = 'Rapids FC (Ga)' WHERE club_name = 'Rapids FC (GA)' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "TRAC Covered Bridge Soccer Club" → "Trac Covered Bridge Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Trac Covered Bridge Soccer Club' WHERE club_name = 'TRAC Covered Bridge Soccer Club' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "United Futbol Academy (UFA)" → "United Futbol Academy (Ufa)" (2 teams)
UPDATE teams SET club_name = 'United Futbol Academy (Ufa)' WHERE club_name = 'United Futbol Academy (UFA)' AND state_code = 'GA' AND gender = 'Female';

-- [CAPS] "YMCA Arsenal Rome" → "Ymca Arsenal Rome" (10 teams)
UPDATE teams SET club_name = 'Ymca Arsenal Rome' WHERE club_name = 'YMCA Arsenal Rome' AND state_code = 'GA' AND gender = 'Female';


-- === HI ===
-- [CAPS] "ALBION SC Hawaii" → "Albion SC Hawaii" (11 teams)
UPDATE teams SET club_name = 'Albion SC Hawaii' WHERE club_name = 'ALBION SC Hawaii' AND state_code = 'HI' AND gender = 'Female';

-- [VARIATION] "Hawaii Surf SC" → "Hawaii Surf Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Hawaii Surf Soccer Club' WHERE club_name = 'Hawaii Surf SC' AND state_code = 'HI' AND gender = 'Female';


-- === IA ===
-- [CAPS] "FC America (IA)" → "FC America (Ia)" (3 teams)
UPDATE teams SET club_name = 'FC America (Ia)' WHERE club_name = 'FC America (IA)' AND state_code = 'IA' AND gender = 'Female';

-- [CAPS] "United Futbol Academy (UFA)" → "United Futbol Academy (Ufa)" (10 teams)
UPDATE teams SET club_name = 'United Futbol Academy (Ufa)' WHERE club_name = 'United Futbol Academy (UFA)' AND state_code = 'IA' AND gender = 'Female';


-- === ID ===
-- [CAPS] "ALBION SC Idaho" → "Albion SC Idaho" (9 teams)
UPDATE teams SET club_name = 'Albion SC Idaho' WHERE club_name = 'ALBION SC Idaho' AND state_code = 'ID' AND gender = 'Female';

-- [CAPS] "BYSL" → "Bysl" (29 teams)
UPDATE teams SET club_name = 'Bysl' WHERE club_name = 'BYSL' AND state_code = 'ID' AND gender = 'Female';

-- [VARIATION] "Boise Timbers | Thorns FC" → "Boise Timbers | Thorns" (10 teams)
UPDATE teams SET club_name = 'Boise Timbers | Thorns' WHERE club_name = 'Boise Timbers | Thorns FC' AND state_code = 'ID' AND gender = 'Female';

-- [VARIATION] "Idaho Rush SC" → "Idaho Rush Soccer Club" (6 teams)
UPDATE teams SET club_name = 'Idaho Rush Soccer Club' WHERE club_name = 'Idaho Rush SC' AND state_code = 'ID' AND gender = 'Female';

-- [VARIATION] "Indie Chicas Soccer Club" → "Indie Chicas" (1 teams)
UPDATE teams SET club_name = 'Indie Chicas' WHERE club_name = 'Indie Chicas Soccer Club' AND state_code = 'ID' AND gender = 'Female';

-- [CAPS] "JYSA Soccer" → "Jysa Soccer" (8 teams)
UPDATE teams SET club_name = 'Jysa Soccer' WHERE club_name = 'JYSA Soccer' AND state_code = 'ID' AND gender = 'Female';

-- [CAPS] "PVSC United (GCYSL)" → "Pvsc United (Gcysl)" (20 teams)
UPDATE teams SET club_name = 'Pvsc United (Gcysl)' WHERE club_name = 'PVSC United (GCYSL)' AND state_code = 'ID' AND gender = 'Female';

-- [CAPS] "Palacios Futbol Club (PFC)" → "Palacios Futbol Club (Pfc)" (6 teams)
UPDATE teams SET club_name = 'Palacios Futbol Club (Pfc)' WHERE club_name = 'Palacios Futbol Club (PFC)' AND state_code = 'ID' AND gender = 'Female';


-- === IL ===
-- [CAPS] "BLFC" → "Blfc" (5 teams)
UPDATE teams SET club_name = 'Blfc' WHERE club_name = 'BLFC' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "Chicago Fire Youth SC (CFYSC)" → "Chicago Fire Youth SC (Cfysc)" (15 teams)
UPDATE teams SET club_name = 'Chicago Fire Youth SC (Cfysc)' WHERE club_name = 'Chicago Fire Youth SC (CFYSC)' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "Chicago Futbol Alliance (CFA)" → "Chicago Futbol Alliance (Cfa)" (9 teams)
UPDATE teams SET club_name = 'Chicago Futbol Alliance (Cfa)' WHERE club_name = 'Chicago Futbol Alliance (CFA)' AND state_code = 'IL' AND gender = 'Female';

-- [VARIATION] "Chicago Inter Soccer" → "Chicago Inter" (15 teams)
UPDATE teams SET club_name = 'Chicago Inter' WHERE club_name = 'Chicago Inter Soccer' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "Chicago KICS Football Club" → "Chicago Kics Football Club" (7 teams)
UPDATE teams SET club_name = 'Chicago Kics Football Club' WHERE club_name = 'Chicago KICS Football Club' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "Chicago Soccer Academy (CSA)" → "Chicago Soccer Academy (Csa)" (10 teams)
UPDATE teams SET club_name = 'Chicago Soccer Academy (Csa)' WHERE club_name = 'Chicago Soccer Academy (CSA)' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "Delete - Evergreen United FC (IL)" → "Delete - Evergreen United FC (Il)" (1 teams)
UPDATE teams SET club_name = 'Delete - Evergreen United FC (Il)' WHERE club_name = 'Delete - Evergreen United FC (IL)' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "EGSC Elk Grove Soccer Club" → "Egsc Elk Grove Soccer Club" (5 teams)
UPDATE teams SET club_name = 'Egsc Elk Grove Soccer Club' WHERE club_name = 'EGSC Elk Grove Soccer Club' AND state_code = 'IL' AND gender = 'Female';

-- [VARIATION] "Eclipse Select SC" → "Eclipse Select Soccer Club" (7 teams)
UPDATE teams SET club_name = 'Eclipse Select Soccer Club' WHERE club_name = 'Eclipse Select SC' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "FC Stars (IL)" → "FC Stars (Il)" (10 teams)
UPDATE teams SET club_name = 'FC Stars (Il)' WHERE club_name = 'FC Stars (IL)' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "FC-1 Academy" → "Fc-1 Academy" (13 teams)
UPDATE teams SET club_name = 'Fc-1 Academy' WHERE club_name = 'FC-1 Academy' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "Lyons Township SC (LTSC)" → "Lyons Township SC (Ltsc)" (13 teams)
UPDATE teams SET club_name = 'Lyons Township SC (Ltsc)' WHERE club_name = 'Lyons Township SC (LTSC)' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "RBFC" → "Rbfc" (3 teams)
UPDATE teams SET club_name = 'Rbfc' WHERE club_name = 'RBFC' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "SASA Spirits SC" → "Sasa Spirits SC" (5 teams)
UPDATE teams SET club_name = 'Sasa Spirits SC' WHERE club_name = 'SASA Spirits SC' AND state_code = 'IL' AND gender = 'Female';

-- [CAPS] "SCFC" → "Scfc" (4 teams)
UPDATE teams SET club_name = 'Scfc' WHERE club_name = 'SCFC' AND state_code = 'IL' AND gender = 'Female';


-- === IN ===
-- [CAPS] "INACTIVE - Hurricane Soccer" → "Inactive - Hurricane Soccer" (2 teams)
UPDATE teams SET club_name = 'Inactive - Hurricane Soccer' WHERE club_name = 'INACTIVE - Hurricane Soccer' AND state_code = 'IN' AND gender = 'Female';

-- [CAPS] "SWISA" → "Swisa" (3 teams)
UPDATE teams SET club_name = 'Swisa' WHERE club_name = 'SWISA' AND state_code = 'IN' AND gender = 'Female';

-- [CAPS] "USAI" → "Usai" (12 teams)
UPDATE teams SET club_name = 'Usai' WHERE club_name = 'USAI' AND state_code = 'IN' AND gender = 'Female';


-- === KS ===
-- [CAPS] "AZTECA" → "Azteca" (5 teams)
UPDATE teams SET club_name = 'Azteca' WHERE club_name = 'AZTECA' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "CLUB AZZURRI" → "Club Azzurri" (4 teams)
UPDATE teams SET club_name = 'Club Azzurri' WHERE club_name = 'CLUB AZZURRI' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "DERBY UNITED" → "Derby United" (7 teams)
UPDATE teams SET club_name = 'Derby United' WHERE club_name = 'DERBY UNITED' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "FC ATLAS" → "FC Atlas" (5 teams)
UPDATE teams SET club_name = 'FC Atlas' WHERE club_name = 'FC ATLAS' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "FC ATLETICO" → "FC Atletico" (3 teams)
UPDATE teams SET club_name = 'FC Atletico' WHERE club_name = 'FC ATLETICO' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "FC KANSAS" → "FC Kansas" (6 teams)
UPDATE teams SET club_name = 'FC Kansas' WHERE club_name = 'FC KANSAS' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "NEWTON RAILERS" → "Newton Railers" (2 teams)
UPDATE teams SET club_name = 'Newton Railers' WHERE club_name = 'NEWTON RAILERS' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "RAPTORS SC" → "Raptors SC" (7 teams)
UPDATE teams SET club_name = 'Raptors SC' WHERE club_name = 'RAPTORS SC' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "SOUTHWEST KANSAS" → "Southwest Kansas" (1 teams)
UPDATE teams SET club_name = 'Southwest Kansas' WHERE club_name = 'SOUTHWEST KANSAS' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "STARS UNITED" → "Stars United" (1 teams)
UPDATE teams SET club_name = 'Stars United' WHERE club_name = 'STARS UNITED' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "TISC" → "Tisc" (2 teams)
UPDATE teams SET club_name = 'Tisc' WHERE club_name = 'TISC' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "VC FUSION" → "VC Fusion" (6 teams)
UPDATE teams SET club_name = 'VC Fusion' WHERE club_name = 'VC FUSION' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "WICHITA RUSH" → "Wichita Rush" (13 teams)
UPDATE teams SET club_name = 'Wichita Rush' WHERE club_name = 'WICHITA RUSH' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "WICHITA UNITED FC" → "Wichita United FC" (17 teams)
UPDATE teams SET club_name = 'Wichita United FC' WHERE club_name = 'WICHITA UNITED FC' AND state_code = 'KS' AND gender = 'Female';

-- [CAPS] "WICHITA WARRIORS SOCCER CLUB" → "Wichita Warriors Soccer Club" (5 teams)
UPDATE teams SET club_name = 'Wichita Warriors Soccer Club' WHERE club_name = 'WICHITA WARRIORS SOCCER CLUB' AND state_code = 'KS' AND gender = 'Female';


-- === KY ===
-- [CAPS] "Campbell Soccer Club (CSC)" → "Campbell Soccer Club (Csc)" (6 teams)
UPDATE teams SET club_name = 'Campbell Soccer Club (Csc)' WHERE club_name = 'Campbell Soccer Club (CSC)' AND state_code = 'KY' AND gender = 'Female';

-- [CAPS] "EYSA" → "Eysa" (1 teams)
UPDATE teams SET club_name = 'Eysa' WHERE club_name = 'EYSA' AND state_code = 'KY' AND gender = 'Female';

-- [CAPS] "I AM 3RD SOCCER" → "I Am 3Rd Soccer" (8 teams)
UPDATE teams SET club_name = 'I Am 3Rd Soccer' WHERE club_name = 'I AM 3RD SOCCER' AND state_code = 'KY' AND gender = 'Female';

-- [CAPS] "WKSA Western Kentucky Soccer Academy" → "Wksa Western Kentucky Soccer Academy" (3 teams)
UPDATE teams SET club_name = 'Wksa Western Kentucky Soccer Academy' WHERE club_name = 'WKSA Western Kentucky Soccer Academy' AND state_code = 'KY' AND gender = 'Female';


-- === LA ===
-- [VARIATION] "Louisiana Fire Soccer Club" → "Louisiana Fire SC" (6 teams)
UPDATE teams SET club_name = 'Louisiana Fire SC' WHERE club_name = 'Louisiana Fire Soccer Club' AND state_code = 'LA' AND gender = 'Female';

-- [CAPS] "NOLA Soccer Academy" → "Nola Soccer Academy" (6 teams)
UPDATE teams SET club_name = 'Nola Soccer Academy' WHERE club_name = 'NOLA Soccer Academy' AND state_code = 'LA' AND gender = 'Female';

-- [CAPS] "PARDS Soccer Club" → "Pards Soccer Club" (4 teams)
UPDATE teams SET club_name = 'Pards Soccer Club' WHERE club_name = 'PARDS Soccer Club' AND state_code = 'LA' AND gender = 'Female';


-- === MA ===
-- [CAPS] "Marshfield United Soccer Club (MUSC)" → "Marshfield United Soccer Club (Musc)" (6 teams)
UPDATE teams SET club_name = 'Marshfield United Soccer Club (Musc)' WHERE club_name = 'Marshfield United Soccer Club (MUSC)' AND state_code = 'MA' AND gender = 'Female';

-- [CAPS] "NEFC" → "Nefc" (155 teams)
UPDATE teams SET club_name = 'Nefc' WHERE club_name = 'NEFC' AND state_code = 'MA' AND gender = 'Female';

-- [CAPS] "USASA" → "Usasa" (1 teams)
UPDATE teams SET club_name = 'Usasa' WHERE club_name = 'USASA' AND state_code = 'MA' AND gender = 'Female';


-- === MD ===
-- [CAPS] "AVID Soccer Club" → "Avid Soccer Club" (4 teams)
UPDATE teams SET club_name = 'Avid Soccer Club' WHERE club_name = 'AVID Soccer Club' AND state_code = 'MD' AND gender = 'Female';

-- [CAPS] "Abingdon Football Club (AFC Soccer)" → "Abingdon Football Club (Afc Soccer)" (1 teams)
UPDATE teams SET club_name = 'Abingdon Football Club (Afc Soccer)' WHERE club_name = 'Abingdon Football Club (AFC Soccer)' AND state_code = 'MD' AND gender = 'Female';

-- [VARIATION] "Coppermine SC" → "Coppermine Soccer Club" (3 teams)
UPDATE teams SET club_name = 'Coppermine Soccer Club' WHERE club_name = 'Coppermine SC' AND state_code = 'MD' AND gender = 'Female';

-- [CAPS] "FCGB Center of Excellence" → "Fcgb Center Of Excellence" (8 teams)
UPDATE teams SET club_name = 'Fcgb Center Of Excellence' WHERE club_name = 'FCGB Center of Excellence' AND state_code = 'MD' AND gender = 'Female';

-- [VARIATION] "Future Soccer Club" → "Future FC" (1 teams)
UPDATE teams SET club_name = 'Future FC' WHERE club_name = 'Future Soccer Club' AND state_code = 'MD' AND gender = 'Female';

-- [CAPS] "Montgomery Soccer (MSI)" → "Montgomery Soccer (Msi)" (25 teams)
UPDATE teams SET club_name = 'Montgomery Soccer (Msi)' WHERE club_name = 'Montgomery Soccer (MSI)' AND state_code = 'MD' AND gender = 'Female';

-- [CAPS] "SAC/BA" → "Sac/Ba" (30 teams)
UPDATE teams SET club_name = 'Sac/Ba' WHERE club_name = 'SAC/BA' AND state_code = 'MD' AND gender = 'Female';


-- === ME ===
-- [CAPS] "NEFC" → "Nefc" (1 teams)
UPDATE teams SET club_name = 'Nefc' WHERE club_name = 'NEFC' AND state_code = 'ME' AND gender = 'Female';

-- [CAPS] "NEFC Maine" → "Nefc Maine" (3 teams)
UPDATE teams SET club_name = 'Nefc Maine' WHERE club_name = 'NEFC Maine' AND state_code = 'ME' AND gender = 'Female';


-- === MI ===
-- [CAPS] "DBSS" → "Dbss" (7 teams)
UPDATE teams SET club_name = 'Dbss' WHERE club_name = 'DBSS' AND state_code = 'MI' AND gender = 'Female';

-- [CAPS] "JACS" → "Jacs" (5 teams)
UPDATE teams SET club_name = 'Jacs' WHERE club_name = 'JACS' AND state_code = 'MI' AND gender = 'Female';

-- [CAPS] "Jackson NW AYSO Alliance" → "Jackson Nw AYSO Alliance" (2 teams)
UPDATE teams SET club_name = 'Jackson Nw AYSO Alliance' WHERE club_name = 'Jackson NW AYSO Alliance' AND state_code = 'MI' AND gender = 'Female';

-- [CAPS] "Liverpool FC-IA Michigan" → "Liverpool Fc-Ia Michigan" (60 teams)
UPDATE teams SET club_name = 'Liverpool Fc-Ia Michigan' WHERE club_name = 'Liverpool FC-IA Michigan' AND state_code = 'MI' AND gender = 'Female';

-- [CAPS] "MPSA Crush" → "Mpsa Crush" (9 teams)
UPDATE teams SET club_name = 'Mpsa Crush' WHERE club_name = 'MPSA Crush' AND state_code = 'MI' AND gender = 'Female';

-- [CAPS] "Midwest United FC SCOR" → "Midwest United FC Scor" (16 teams)
UPDATE teams SET club_name = 'Midwest United FC Scor' WHERE club_name = 'Midwest United FC SCOR' AND state_code = 'MI' AND gender = 'Female';

-- [VARIATION] "Nationals SC" → "Nationals" (34 teams)
UPDATE teams SET club_name = 'Nationals' WHERE club_name = 'Nationals SC' AND state_code = 'MI' AND gender = 'Female';

-- [VARIATION] "Northville SA" → "Northville FC" (3 teams)
UPDATE teams SET club_name = 'Northville FC' WHERE club_name = 'Northville SA' AND state_code = 'MI' AND gender = 'Female';

-- [CAPS] "PASS FC" → "Pass FC" (13 teams)
UPDATE teams SET club_name = 'Pass FC' WHERE club_name = 'PASS FC' AND state_code = 'MI' AND gender = 'Female';

-- [VARIATION] "Portage SC" → "Portage Soccer Club" (5 teams)
UPDATE teams SET club_name = 'Portage Soccer Club' WHERE club_name = 'Portage SC' AND state_code = 'MI' AND gender = 'Female';

-- [CAPS] "WAZA FC" → "Waza FC" (3 teams)
UPDATE teams SET club_name = 'Waza FC' WHERE club_name = 'WAZA FC' AND state_code = 'MI' AND gender = 'Female';


-- === MN ===
-- [CAPS] "BOREAL FC" → "Boreal FC" (3 teams)
UPDATE teams SET club_name = 'Boreal FC' WHERE club_name = 'BOREAL FC' AND state_code = 'MN' AND gender = 'Female';

-- [CAPS] "BV UNITED" → "Bv United" (3 teams)
UPDATE teams SET club_name = 'Bv United' WHERE club_name = 'BV UNITED' AND state_code = 'MN' AND gender = 'Female';

-- [CAPS] "EPSC" → "Epsc" (11 teams)
UPDATE teams SET club_name = 'Epsc' WHERE club_name = 'EPSC' AND state_code = 'MN' AND gender = 'Female';

-- [CAPS] "KMYSA" → "Kmysa" (2 teams)
UPDATE teams SET club_name = 'Kmysa' WHERE club_name = 'KMYSA' AND state_code = 'MN' AND gender = 'Female';

-- [VARIATION] "Maplebrook Soccer Club" → "MapleBrook SC" (1 teams)
UPDATE teams SET club_name = 'MapleBrook SC' WHERE club_name = 'Maplebrook Soccer Club' AND state_code = 'MN' AND gender = 'Female';

-- [VARIATION] "Minneapolis United SC" → "Minneapolis United" (3 teams)
UPDATE teams SET club_name = 'Minneapolis United' WHERE club_name = 'Minneapolis United SC' AND state_code = 'MN' AND gender = 'Female';

-- [VARIATION] "North Suburban" → "North Suburban SA" (3 teams)
UPDATE teams SET club_name = 'North Suburban SA' WHERE club_name = 'North Suburban' AND state_code = 'MN' AND gender = 'Female';


-- === MO ===
-- [CAPS] "Alliance Futbol Club (MO)" → "Alliance Futbol Club (Mo)" (10 teams)
UPDATE teams SET club_name = 'Alliance Futbol Club (Mo)' WHERE club_name = 'Alliance Futbol Club (MO)' AND state_code = 'MO' AND gender = 'Female';

-- [CAPS] "MYSA Independent Teams" → "Mysa Independent Teams" (21 teams)
UPDATE teams SET club_name = 'Mysa Independent Teams' WHERE club_name = 'MYSA Independent Teams' AND state_code = 'MO' AND gender = 'Female';

-- [CAPS] "REAL WC St. Louis Soccer Club" → "Real Wc St. Louis Soccer Club" (13 teams)
UPDATE teams SET club_name = 'Real Wc St. Louis Soccer Club' WHERE club_name = 'REAL WC St. Louis Soccer Club' AND state_code = 'MO' AND gender = 'Female';

-- [CAPS] "SEMO Elite FC" → "Semo Elite FC" (7 teams)
UPDATE teams SET club_name = 'Semo Elite FC' WHERE club_name = 'SEMO Elite FC' AND state_code = 'MO' AND gender = 'Female';

-- [CAPS] "SEMO Swarm" → "Semo Swarm" (1 teams)
UPDATE teams SET club_name = 'Semo Swarm' WHERE club_name = 'SEMO Swarm' AND state_code = 'MO' AND gender = 'Female';

-- [CAPS] "SLSG" → "Slsg" (29 teams)
UPDATE teams SET club_name = 'Slsg' WHERE club_name = 'SLSG' AND state_code = 'MO' AND gender = 'Female';

-- [CAPS] "WGSC Soccer" → "Wgsc Soccer" (3 teams)
UPDATE teams SET club_name = 'Wgsc Soccer' WHERE club_name = 'WGSC Soccer' AND state_code = 'MO' AND gender = 'Female';


-- === MS ===
-- [CAPS] "Brilla JUNIORS" → "Brilla Juniors" (6 teams)
UPDATE teams SET club_name = 'Brilla Juniors' WHERE club_name = 'Brilla JUNIORS' AND state_code = 'MS' AND gender = 'Female';

-- [VARIATION] "Hattiesburg FC" → "Hattiesburg Futbol Club" (6 teams)
UPDATE teams SET club_name = 'Hattiesburg Futbol Club' WHERE club_name = 'Hattiesburg FC' AND state_code = 'MS' AND gender = 'Female';

-- [CAPS] "NWRAA" → "Nwraa" (10 teams)
UPDATE teams SET club_name = 'Nwraa' WHERE club_name = 'NWRAA' AND state_code = 'MS' AND gender = 'Female';

-- [VARIATION] "Tupelo FC" → "Tupelo Futbol Club" (6 teams)
UPDATE teams SET club_name = 'Tupelo Futbol Club' WHERE club_name = 'Tupelo FC' AND state_code = 'MS' AND gender = 'Female';


-- === MT ===
-- [CAPS] "Queen City Football Club (MT)" → "Queen City Football Club (Mt)" (1 teams)
UPDATE teams SET club_name = 'Queen City Football Club (Mt)' WHERE club_name = 'Queen City Football Club (MT)' AND state_code = 'MT' AND gender = 'Female';


-- === NC ===
-- [VARIATION] "Charlotte Independence Soccer Club" → "Charlotte Independence SC" (11 teams)
UPDATE teams SET club_name = 'Charlotte Independence SC' WHERE club_name = 'Charlotte Independence Soccer Club' AND state_code = 'NC' AND gender = 'Female';

-- [VARIATION] "Charlotte SA" → "Charlotte Soccer Academy" (27 teams)
UPDATE teams SET club_name = 'Charlotte Soccer Academy' WHERE club_name = 'Charlotte SA' AND state_code = 'NC' AND gender = 'Female';

-- [CAPS] "FC ATHLETICO" → "FC Athletico" (10 teams)
UPDATE teams SET club_name = 'FC Athletico' WHERE club_name = 'FC ATHLETICO' AND state_code = 'NC' AND gender = 'Female';

-- [CAPS] "SOCA" → "Soca" (8 teams)
UPDATE teams SET club_name = 'Soca' WHERE club_name = 'SOCA' AND state_code = 'NC' AND gender = 'Female';

-- [VARIATION] "Trinity SA" → "Trinity Soccer Academy" (1 teams)
UPDATE teams SET club_name = 'Trinity Soccer Academy' WHERE club_name = 'Trinity SA' AND state_code = 'NC' AND gender = 'Female';

-- [CAPS] "YCVSC Eagles Soccer Club" → "Ycvsc Eagles Soccer Club" (6 teams)
UPDATE teams SET club_name = 'Ycvsc Eagles Soccer Club' WHERE club_name = 'YCVSC Eagles Soccer Club' AND state_code = 'NC' AND gender = 'Female';


-- === NE ===
-- [CAPS] "DASC" → "Dasc" (2 teams)
UPDATE teams SET club_name = 'Dasc' WHERE club_name = 'DASC' AND state_code = 'NE' AND gender = 'Female';

-- [CAPS] "Evolution SC (NE)" → "Evolution SC (Ne)" (14 teams)
UPDATE teams SET club_name = 'Evolution SC (Ne)' WHERE club_name = 'Evolution SC (NE)' AND state_code = 'NE' AND gender = 'Female';

-- [CAPS] "Hawks FC (NE)" → "Hawks FC (Ne)" (6 teams)
UPDATE teams SET club_name = 'Hawks FC (Ne)' WHERE club_name = 'Hawks FC (NE)' AND state_code = 'NE' AND gender = 'Female';

-- [VARIATION] "Omaha Surf sc" → "Omaha Surf Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Omaha Surf Soccer Club' WHERE club_name = 'Omaha Surf sc' AND state_code = 'NE' AND gender = 'Female';

-- [VARIATION] "Omaha United" → "Omaha United SC" (6 teams)
UPDATE teams SET club_name = 'Omaha United SC' WHERE club_name = 'Omaha United' AND state_code = 'NE' AND gender = 'Female';

-- [CAPS] "PACE Soccer Academy" → "Pace Soccer Academy" (2 teams)
UPDATE teams SET club_name = 'Pace Soccer Academy' WHERE club_name = 'PACE Soccer Academy' AND state_code = 'NE' AND gender = 'Female';


-- === NH ===
-- [CAPS] "ROSO Soccer Club" → "Roso Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Roso Soccer Club' WHERE club_name = 'ROSO Soccer Club' AND state_code = 'NH' AND gender = 'Female';


-- === NJ ===
-- [CAPS] "Arsenal Soccer Club (NJ)" → "Arsenal Soccer Club (Nj)" (2 teams)
UPDATE teams SET club_name = 'Arsenal Soccer Club (Nj)' WHERE club_name = 'Arsenal Soccer Club (NJ)' AND state_code = 'NJ' AND gender = 'Female';

-- [VARIATION] "Atlantic United" → "Atlantic United Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Atlantic United Soccer Club' WHERE club_name = 'Atlantic United' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "BOTB Slay Select" → "Botb Slay Select" (1 teams)
UPDATE teams SET club_name = 'Botb Slay Select' WHERE club_name = 'BOTB Slay Select' AND state_code = 'NJ' AND gender = 'Female';

-- [VARIATION] "Cherry Hill SC" → "Cherry Hill FC" (11 teams)
UPDATE teams SET club_name = 'Cherry Hill FC' WHERE club_name = 'Cherry Hill SC' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "EP UNITED SOCCER CLUB" → "Ep United Soccer Club" (3 teams)
UPDATE teams SET club_name = 'Ep United Soccer Club' WHERE club_name = 'EP UNITED SOCCER CLUB' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "Hanover Soccer Club (NJ)" → "Hanover Soccer Club (Nj)" (2 teams)
UPDATE teams SET club_name = 'Hanover Soccer Club (Nj)' WHERE club_name = 'Hanover Soccer Club (NJ)' AND state_code = 'NJ' AND gender = 'Female';

-- [VARIATION] "Harrison Futbol Club" → "Harrison SC" (2 teams)
UPDATE teams SET club_name = 'Harrison SC' WHERE club_name = 'Harrison Futbol Club' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "Jackson SC(NJ)" → "Jackson Sc(Nj)" (7 teams)
UPDATE teams SET club_name = 'Jackson Sc(Nj)' WHERE club_name = 'Jackson SC(NJ)' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "Mount Laurel United (MLU)" → "Mount Laurel United (Mlu)" (13 teams)
UPDATE teams SET club_name = 'Mount Laurel United (Mlu)' WHERE club_name = 'Mount Laurel United (MLU)' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "Mountain Lakes-Boonton Township-Boonton Soccer Club (MLBTB)" → "Mountain Lakes-Boonton Township-Boonton Soccer Club (Mlbtb)" (1 teams)
UPDATE teams SET club_name = 'Mountain Lakes-Boonton Township-Boonton Soccer Club (Mlbtb)' WHERE club_name = 'Mountain Lakes-Boonton Township-Boonton Soccer Club (MLBTB)' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "NESA" → "Nesa" (7 teams)
UPDATE teams SET club_name = 'Nesa' WHERE club_name = 'NESA' AND state_code = 'NJ' AND gender = 'Female';

-- [VARIATION] "NJ Nationals" → "NJ Nationals FC" (3 teams)
UPDATE teams SET club_name = 'NJ Nationals FC' WHERE club_name = 'NJ Nationals' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "NJ14 Soccer Club" → "Nj14 Soccer Club" (13 teams)
UPDATE teams SET club_name = 'Nj14 Soccer Club' WHERE club_name = 'NJ14 Soccer Club' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "NLSA Surf" → "Nlsa Surf" (7 teams)
UPDATE teams SET club_name = 'Nlsa Surf' WHERE club_name = 'NLSA Surf' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "Next Level Soccer Academy (NJ)" → "Next Level Soccer Academy (Nj)" (13 teams)
UPDATE teams SET club_name = 'Next Level Soccer Academy (Nj)' WHERE club_name = 'Next Level Soccer Academy (NJ)' AND state_code = 'NJ' AND gender = 'Female';

-- [VARIATION] "Piscataway Soccer Club" → "Piscataway SC" (1 teams)
UPDATE teams SET club_name = 'Piscataway SC' WHERE club_name = 'Piscataway Soccer Club' AND state_code = 'NJ' AND gender = 'Female';

-- [VARIATION] "Princeton FC" → "Princeton SA" (7 teams)
UPDATE teams SET club_name = 'Princeton SA' WHERE club_name = 'Princeton FC' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "RYSA Wildcats Youth Soccer" → "Rysa Wildcats Youth Soccer" (4 teams)
UPDATE teams SET club_name = 'Rysa Wildcats Youth Soccer' WHERE club_name = 'RYSA Wildcats Youth Soccer' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "Red Bulls (NJ)" → "Red Bulls (Nj)" (4 teams)
UPDATE teams SET club_name = 'Red Bulls (Nj)' WHERE club_name = 'Red Bulls (NJ)' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "SJEB FC" → "Sjeb FC" (26 teams)
UPDATE teams SET club_name = 'Sjeb FC' WHERE club_name = 'SJEB FC' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "SJYS" → "Sjys" (12 teams)
UPDATE teams SET club_name = 'Sjys' WHERE club_name = 'SJYS' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "SPFSC EP3" → "Spfsc Ep3" (5 teams)
UPDATE teams SET club_name = 'Spfsc Ep3' WHERE club_name = 'SPFSC EP3' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "Sporting Club Premier (NJ)" → "Sporting Club Premier (Nj)" (22 teams)
UPDATE teams SET club_name = 'Sporting Club Premier (Nj)' WHERE club_name = 'Sporting Club Premier (NJ)' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "TBAA" → "Tbaa" (8 teams)
UPDATE teams SET club_name = 'Tbaa' WHERE club_name = 'TBAA' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "Union City Soccer Club (NJ)" → "Union City Soccer Club (Nj)" (1 teams)
UPDATE teams SET club_name = 'Union City Soccer Club (Nj)' WHERE club_name = 'Union City Soccer Club (NJ)' AND state_code = 'NJ' AND gender = 'Female';

-- [CAPS] "WTSC" → "Wtsc" (8 teams)
UPDATE teams SET club_name = 'Wtsc' WHERE club_name = 'WTSC' AND state_code = 'NJ' AND gender = 'Female';

-- [VARIATION] "Wall SC" → "Wall Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Wall Soccer Club' WHERE club_name = 'Wall SC' AND state_code = 'NJ' AND gender = 'Female';


-- === NM ===
-- [CAPS] "AYSO United Soccer Club (NM)" → "AYSO United Soccer Club (Nm)" (12 teams)
UPDATE teams SET club_name = 'AYSO United Soccer Club (Nm)' WHERE club_name = 'AYSO United Soccer Club (NM)' AND state_code = 'NM' AND gender = 'Female';

-- [CAPS] "Elite Football Club (NM)" → "Elite Football Club (Nm)" (1 teams)
UPDATE teams SET club_name = 'Elite Football Club (Nm)' WHERE club_name = 'Elite Football Club (NM)' AND state_code = 'NM' AND gender = 'Female';

-- [CAPS] "FC United (NM)" → "FC United (Nm)" (3 teams)
UPDATE teams SET club_name = 'FC United (Nm)' WHERE club_name = 'FC United (NM)' AND state_code = 'NM' AND gender = 'Female';

-- [VARIATION] "Farmington SC" → "Farmington United" (3 teams)
UPDATE teams SET club_name = 'Farmington United' WHERE club_name = 'Farmington SC' AND state_code = 'NM' AND gender = 'Female';

-- [CAPS] "GUADALAJARA NM" → "Guadalajara NM" (1 teams)
UPDATE teams SET club_name = 'Guadalajara NM' WHERE club_name = 'GUADALAJARA NM' AND state_code = 'NM' AND gender = 'Female';

-- [VARIATION] "NM Rapids Soccer Club" → "NM Rapids SC" (9 teams)
UPDATE teams SET club_name = 'NM Rapids SC' WHERE club_name = 'NM Rapids Soccer Club' AND state_code = 'NM' AND gender = 'Female';

-- [CAPS] "New Mexico Soccer Academy (NMSA)" → "New Mexico Soccer Academy (Nmsa)" (3 teams)
UPDATE teams SET club_name = 'New Mexico Soccer Academy (Nmsa)' WHERE club_name = 'New Mexico Soccer Academy (NMSA)' AND state_code = 'NM' AND gender = 'Female';


-- === NV ===
-- [CAPS] "ALBION SC Las Vegas" → "Albion SC Las Vegas" (20 teams)
UPDATE teams SET club_name = 'Albion SC Las Vegas' WHERE club_name = 'ALBION SC Las Vegas' AND state_code = 'NV' AND gender = 'Female';

-- [CAPS] "APD F.C." → "Apd F.C." (3 teams)
UPDATE teams SET club_name = 'Apd F.C.' WHERE club_name = 'APD F.C.' AND state_code = 'NV' AND gender = 'Female';

-- [CAPS] "Elite FC (NV)" → "Elite FC (Nv)" (4 teams)
UPDATE teams SET club_name = 'Elite FC (Nv)' WHERE club_name = 'Elite FC (NV)' AND state_code = 'NV' AND gender = 'Female';

-- [CAPS] "PRIME Soccer Club" → "Prime Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Prime Soccer Club' WHERE club_name = 'PRIME Soccer Club' AND state_code = 'NV' AND gender = 'Female';

-- [VARIATION] "Players Soccer Club" → "Players SC" (1 teams)
UPDATE teams SET club_name = 'Players SC' WHERE club_name = 'Players Soccer Club' AND state_code = 'NV' AND gender = 'Female';

-- [VARIATION] "Reno APEX SC" → "Reno Apex Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Reno Apex Soccer Club' WHERE club_name = 'Reno APEX SC' AND state_code = 'NV' AND gender = 'Female';

-- [CAPS] "Reno APEX Soccer Club" → "Reno Apex Soccer Club" (23 teams)
UPDATE teams SET club_name = 'Reno Apex Soccer Club' WHERE club_name = 'Reno APEX Soccer Club' AND state_code = 'NV' AND gender = 'Female';

-- [VARIATION] "Sierra Surf" → "Sierra Surf SC" (1 teams)
UPDATE teams SET club_name = 'Sierra Surf SC' WHERE club_name = 'Sierra Surf' AND state_code = 'NV' AND gender = 'Female';

-- [VARIATION] "Vegas United SC" → "Vegas United Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Vegas United Soccer Club' WHERE club_name = 'Vegas United SC' AND state_code = 'NV' AND gender = 'Female';


-- === NY ===
-- [CAPS] "Atlantic United SB/LGN SC" → "Atlantic United Sb/Lgn SC" (27 teams)
UPDATE teams SET club_name = 'Atlantic United Sb/Lgn SC' WHERE club_name = 'Atlantic United SB/LGN SC' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Babylon (LIJSL)" → "Babylon (Lijsl)" (5 teams)
UPDATE teams SET club_name = 'Babylon (Lijsl)' WHERE club_name = 'Babylon (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Bay Shore (LIJSL)" → "Bay Shore (Lijsl)" (3 teams)
UPDATE teams SET club_name = 'Bay Shore (Lijsl)' WHERE club_name = 'Bay Shore (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Baymen (LIJSL)" → "Baymen (Lijsl)" (17 teams)
UPDATE teams SET club_name = 'Baymen (Lijsl)' WHERE club_name = 'Baymen (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Bellmore (LIJSL)" → "Bellmore (Lijsl)" (3 teams)
UPDATE teams SET club_name = 'Bellmore (Lijsl)' WHERE club_name = 'Bellmore (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Brentwood SC (LIJSL)" → "Brentwood SC (Lijsl)" (3 teams)
UPDATE teams SET club_name = 'Brentwood SC (Lijsl)' WHERE club_name = 'Brentwood SC (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Carle Place (LIJSL)" → "Carle Place (Lijsl)" (5 teams)
UPDATE teams SET club_name = 'Carle Place (Lijsl)' WHERE club_name = 'Carle Place (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Center Moriches (LIJSL)" → "Center Moriches (Lijsl)" (1 teams)
UPDATE teams SET club_name = 'Center Moriches (Lijsl)' WHERE club_name = 'Center Moriches (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Central Islip SC (LIJSL)" → "Central Islip SC (Lijsl)" (2 teams)
UPDATE teams SET club_name = 'Central Islip SC (Lijsl)' WHERE club_name = 'Central Islip SC (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Cold Spring Harbor Huntington (LIJSL)" → "Cold Spring Harbor Huntington (Lijsl)" (10 teams)
UPDATE teams SET club_name = 'Cold Spring Harbor Huntington (Lijsl)' WHERE club_name = 'Cold Spring Harbor Huntington (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Connetquot United Youth Soccer (LIJSL)" → "Connetquot United Youth Soccer (Lijsl)" (11 teams)
UPDATE teams SET club_name = 'Connetquot United Youth Soccer (Lijsl)' WHERE club_name = 'Connetquot United Youth Soccer (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "DUSC" → "Dusc" (13 teams)
UPDATE teams SET club_name = 'Dusc' WHERE club_name = 'DUSC' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Deer Park (LIJSL)" → "Deer Park (Lijsl)" (4 teams)
UPDATE teams SET club_name = 'Deer Park (Lijsl)' WHERE club_name = 'Deer Park (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "EPC-BK (Elite Players Center Brooklyn)" → "Epc-Bk (Elite Players Center Brooklyn)" (1 teams)
UPDATE teams SET club_name = 'Epc-Bk (Elite Players Center Brooklyn)' WHERE club_name = 'EPC-BK (Elite Players Center Brooklyn)' AND state_code = 'NY' AND gender = 'Female';

-- [VARIATION] "East Coast Surf SC" → "East Coast Surf" (7 teams)
UPDATE teams SET club_name = 'East Coast Surf' WHERE club_name = 'East Coast Surf SC' AND state_code = 'NY' AND gender = 'Female';

-- [VARIATION] "East Meadow SC" → "East Meadow Soccer Club" (15 teams)
UPDATE teams SET club_name = 'East Meadow Soccer Club' WHERE club_name = 'East Meadow SC' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Elmont SC (LIJSL)" → "Elmont SC (Lijsl)" (3 teams)
UPDATE teams SET club_name = 'Elmont SC (Lijsl)' WHERE club_name = 'Elmont SC (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Elwood (LIJSL)" → "Elwood (Lijsl)" (3 teams)
UPDATE teams SET club_name = 'Elwood (Lijsl)' WHERE club_name = 'Elwood (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "FC COPA" → "FC Copa" (5 teams)
UPDATE teams SET club_name = 'FC Copa' WHERE club_name = 'FC COPA' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Farmingdale SC (LIJSL)" → "Farmingdale SC (Lijsl)" (9 teams)
UPDATE teams SET club_name = 'Farmingdale SC (Lijsl)' WHERE club_name = 'Farmingdale SC (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Floral Park (LIJSL)" → "Floral Park (Lijsl)" (12 teams)
UPDATE teams SET club_name = 'Floral Park (Lijsl)' WHERE club_name = 'Floral Park (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Freeport Village Football Club (LIJSL)" → "Freeport Village Football Club (Lijsl)" (1 teams)
UPDATE teams SET club_name = 'Freeport Village Football Club (Lijsl)' WHERE club_name = 'Freeport Village Football Club (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Garden City (LIJSL)" → "Garden City (Lijsl)" (23 teams)
UPDATE teams SET club_name = 'Garden City (Lijsl)' WHERE club_name = 'Garden City (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Glen Cove (LIJSL)" → "Glen Cove (Lijsl)" (4 teams)
UPDATE teams SET club_name = 'Glen Cove (Lijsl)' WHERE club_name = 'Glen Cove (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Great Neck SC (LIJSL)" → "Great Neck SC (Lijsl)" (2 teams)
UPDATE teams SET club_name = 'Great Neck SC (Lijsl)' WHERE club_name = 'Great Neck SC (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Greater Long Beach (LIJSL)" → "Greater Long Beach (Lijsl)" (9 teams)
UPDATE teams SET club_name = 'Greater Long Beach (Lijsl)' WHERE club_name = 'Greater Long Beach (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "HBC Soccer Club (LIJSL)" → "Hbc Soccer Club (Lijsl)" (12 teams)
UPDATE teams SET club_name = 'Hbc Soccer Club (Lijsl)' WHERE club_name = 'HBC Soccer Club (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Hauppauge (LIJSL)" → "Hauppauge (Lijsl)" (3 teams)
UPDATE teams SET club_name = 'Hauppauge (Lijsl)' WHERE club_name = 'Hauppauge (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Hewlett/Lawrence (LIJSL)" → "Hewlett/Lawrence (Lijsl)" (1 teams)
UPDATE teams SET club_name = 'Hewlett/Lawrence (Lijsl)' WHERE club_name = 'Hewlett/Lawrence (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "LIJSL Academy" → "Lijsl Academy" (4 teams)
UPDATE teams SET club_name = 'Lijsl Academy' WHERE club_name = 'LIJSL Academy' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "LMFC" → "Lmfc" (11 teams)
UPDATE teams SET club_name = 'Lmfc' WHERE club_name = 'LMFC' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Levittown Soccer Club (LIJSL)" → "Levittown Soccer Club (Lijsl)" (9 teams)
UPDATE teams SET club_name = 'Levittown Soccer Club (Lijsl)' WHERE club_name = 'Levittown Soccer Club (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Lindenhurst Soccer Club (LIJSL)" → "Lindenhurst Soccer Club (Lijsl)" (7 teams)
UPDATE teams SET club_name = 'Lindenhurst Soccer Club (Lijsl)' WHERE club_name = 'Lindenhurst Soccer Club (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Locust Valley Bayville Soccer Club (LIJSL)" → "Locust Valley Bayville Soccer Club (Lijsl)" (3 teams)
UPDATE teams SET club_name = 'Locust Valley Bayville Soccer Club (Lijsl)' WHERE club_name = 'Locust Valley Bayville Soccer Club (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [VARIATION] "Long Island Soccer Club" → "Long Island SC" (1 teams)
UPDATE teams SET club_name = 'Long Island SC' WHERE club_name = 'Long Island Soccer Club' AND state_code = 'NY' AND gender = 'Female';

-- [VARIATION] "Manhattan Soccer Club" → "Manhattan SC" (3 teams)
UPDATE teams SET club_name = 'Manhattan SC' WHERE club_name = 'Manhattan Soccer Club' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Manorville (LIJSL)" → "Manorville (Lijsl)" (6 teams)
UPDATE teams SET club_name = 'Manorville (Lijsl)' WHERE club_name = 'Manorville (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Middle Country Children SC (LIJSL)" → "Middle Country Children SC (Lijsl)" (1 teams)
UPDATE teams SET club_name = 'Middle Country Children SC (Lijsl)' WHERE club_name = 'Middle Country Children SC (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Mineola (LIJSL)" → "Mineola (Lijsl)" (5 teams)
UPDATE teams SET club_name = 'Mineola (Lijsl)' WHERE club_name = 'Mineola (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Mohawk Valley Soccer Club (MVSC)" → "Mohawk Valley Soccer Club (Mvsc)" (4 teams)
UPDATE teams SET club_name = 'Mohawk Valley Soccer Club (Mvsc)' WHERE club_name = 'Mohawk Valley Soccer Club (MVSC)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Moriches Youth (LIJSL)" → "Moriches Youth (Lijsl)" (5 teams)
UPDATE teams SET club_name = 'Moriches Youth (Lijsl)' WHERE club_name = 'Moriches Youth (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [VARIATION] "New York Soccer Club" → "New York SC" (3 teams)
UPDATE teams SET club_name = 'New York SC' WHERE club_name = 'New York Soccer Club' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "North Fork (LIJSL)" → "North Fork (Lijsl)" (3 teams)
UPDATE teams SET club_name = 'North Fork (Lijsl)' WHERE club_name = 'North Fork (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Oceanside United Soccer (LIJSL)" → "Oceanside United Soccer (Lijsl)" (5 teams)
UPDATE teams SET club_name = 'Oceanside United Soccer (Lijsl)' WHERE club_name = 'Oceanside United Soccer (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Oyster Bay/East Norwich (LIJSL)" → "Oyster Bay/East Norwich (Lijsl)" (5 teams)
UPDATE teams SET club_name = 'Oyster Bay/East Norwich (Lijsl)' WHERE club_name = 'Oyster Bay/East Norwich (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Plainedge (LIJSL)" → "Plainedge (Lijsl)" (12 teams)
UPDATE teams SET club_name = 'Plainedge (Lijsl)' WHERE club_name = 'Plainedge (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Plainview Old Bethpage (LIJSL)" → "Plainview Old Bethpage (Lijsl)" (8 teams)
UPDATE teams SET club_name = 'Plainview Old Bethpage (Lijsl)' WHERE club_name = 'Plainview Old Bethpage (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Queens United (LIJSL)" → "Queens United (Lijsl)" (1 teams)
UPDATE teams SET club_name = 'Queens United (Lijsl)' WHERE club_name = 'Queens United (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Rocky Point (LIJSL)" → "Rocky Point (Lijsl)" (2 teams)
UPDATE teams SET club_name = 'Rocky Point (Lijsl)' WHERE club_name = 'Rocky Point (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Roosevelt (LIJSL)" → "Roosevelt (Lijsl)" (1 teams)
UPDATE teams SET club_name = 'Roosevelt (Lijsl)' WHERE club_name = 'Roosevelt (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "SOAP Football Company" → "Soap Football Company" (3 teams)
UPDATE teams SET club_name = 'Soap Football Company' WHERE club_name = 'SOAP Football Company' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "SUSA FC" → "Susa FC" (62 teams)
UPDATE teams SET club_name = 'Susa FC' WHERE club_name = 'SUSA FC' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Smithtown Kickers SC (LIJSL)" → "Smithtown Kickers SC (Lijsl)" (21 teams)
UPDATE teams SET club_name = 'Smithtown Kickers SC (Lijsl)' WHERE club_name = 'Smithtown Kickers SC (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "South Huntington (LIJSL)" → "South Huntington (Lijsl)" (4 teams)
UPDATE teams SET club_name = 'South Huntington (Lijsl)' WHERE club_name = 'South Huntington (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Sporting Club Premier (NY)" → "Sporting Club Premier (Ny)" (1 teams)
UPDATE teams SET club_name = 'Sporting Club Premier (Ny)' WHERE club_name = 'Sporting Club Premier (NY)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Syracuse Development Academy (SDA)" → "Syracuse Development Academy (Sda)" (6 teams)
UPDATE teams SET club_name = 'Syracuse Development Academy (Sda)' WHERE club_name = 'Syracuse Development Academy (SDA)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Terryville (LIJSL)" → "Terryville (Lijsl)" (5 teams)
UPDATE teams SET club_name = 'Terryville (Lijsl)' WHERE club_name = 'Terryville (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "VOB Soccer Club (LIJSL)" → "Vob Soccer Club (Lijsl)" (8 teams)
UPDATE teams SET club_name = 'Vob Soccer Club (Lijsl)' WHERE club_name = 'VOB Soccer Club (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Valley Stream (LIJSL)" → "Valley Stream (Lijsl)" (1 teams)
UPDATE teams SET club_name = 'Valley Stream (Lijsl)' WHERE club_name = 'Valley Stream (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "W. Hempstead (LIJSL)" → "W. Hempstead (Lijsl)" (2 teams)
UPDATE teams SET club_name = 'W. Hempstead (Lijsl)' WHERE club_name = 'W. Hempstead (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "WSSL TT" → "Wssl Tt" (3 teams)
UPDATE teams SET club_name = 'Wssl Tt' WHERE club_name = 'WSSL TT' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "Wantagh Seaford PAL Soccer Club (LIJSL)" → "Wantagh Seaford Pal Soccer Club (Lijsl)" (6 teams)
UPDATE teams SET club_name = 'Wantagh Seaford Pal Soccer Club (Lijsl)' WHERE club_name = 'Wantagh Seaford PAL Soccer Club (LIJSL)' AND state_code = 'NY' AND gender = 'Female';

-- [CAPS] "West Babylon SC (LIJSL)" → "West Babylon SC (Lijsl)" (2 teams)
UPDATE teams SET club_name = 'West Babylon SC (Lijsl)' WHERE club_name = 'West Babylon SC (LIJSL)' AND state_code = 'NY' AND gender = 'Female';


-- === OH ===
-- [CAPS] "Ambassadors FC (OH)" → "Ambassadors FC (Oh)" (15 teams)
UPDATE teams SET club_name = 'Ambassadors FC (Oh)' WHERE club_name = 'Ambassadors FC (OH)' AND state_code = 'OH' AND gender = 'Female';

-- [VARIATION] "Anthony Wayne United" → "Anthony Wayne United SC" (1 teams)
UPDATE teams SET club_name = 'Anthony Wayne United SC' WHERE club_name = 'Anthony Wayne United' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "BCSA" → "Bcsa" (2 teams)
UPDATE teams SET club_name = 'Bcsa' WHERE club_name = 'BCSA' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "COPL-OCL" → "Copl-Ocl" (1 teams)
UPDATE teams SET club_name = 'Copl-Ocl' WHERE club_name = 'COPL-OCL' AND state_code = 'OH' AND gender = 'Female';

-- [VARIATION] "Cincinnati United Soccer Club" → "Cincinnati United" (4 teams)
UPDATE teams SET club_name = 'Cincinnati United' WHERE club_name = 'Cincinnati United Soccer Club' AND state_code = 'OH' AND gender = 'Female';

-- [VARIATION] "Cincinnati West Soccer Club" → "Cincinnati West" (3 teams)
UPDATE teams SET club_name = 'Cincinnati West' WHERE club_name = 'Cincinnati West Soccer Club' AND state_code = 'OH' AND gender = 'Female';

-- [VARIATION] "Cuyahoga Valley SA" → "Cuyahoga Valley Soccer Academy" (2 teams)
UPDATE teams SET club_name = 'Cuyahoga Valley Soccer Academy' WHERE club_name = 'Cuyahoga Valley SA' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "ESSL Arsenal" → "Essl Arsenal" (10 teams)
UPDATE teams SET club_name = 'Essl Arsenal' WHERE club_name = 'ESSL Arsenal' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "GFSC Geauga Federation Soccer Club" → "Gfsc Geauga Federation Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Gfsc Geauga Federation Soccer Club' WHERE club_name = 'GFSC Geauga Federation Soccer Club' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "GTFC Impact" → "Gtfc Impact" (71 teams)
UPDATE teams SET club_name = 'Gtfc Impact' WHERE club_name = 'GTFC Impact' AND state_code = 'OH' AND gender = 'Female';

-- [VARIATION] "Kings Hammer SC" → "Kings Hammer Soccer Club" (8 teams)
UPDATE teams SET club_name = 'Kings Hammer Soccer Club' WHERE club_name = 'Kings Hammer SC' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "LUFC" → "Lufc" (7 teams)
UPDATE teams SET club_name = 'Lufc' WHERE club_name = 'LUFC' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "Lancaster Select Soccer Association (LSSA)" → "Lancaster Select Soccer Association (Lssa)" (11 teams)
UPDATE teams SET club_name = 'Lancaster Select Soccer Association (Lssa)' WHERE club_name = 'Lancaster Select Soccer Association (LSSA)' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "MVSA Sting" → "Mvsa Sting" (6 teams)
UPDATE teams SET club_name = 'Mvsa Sting' WHERE club_name = 'MVSA Sting' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "NASA Xtabi" → "Nasa Xtabi" (6 teams)
UPDATE teams SET club_name = 'Nasa Xtabi' WHERE club_name = 'NASA Xtabi' AND state_code = 'OH' AND gender = 'Female';

-- [VARIATION] "Ohio Elite Soccer Academy" → "Ohio Elite SA" (14 teams)
UPDATE teams SET club_name = 'Ohio Elite SA' WHERE club_name = 'Ohio Elite Soccer Academy' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "Oxford United FC(OH)" → "Oxford United Fc(Oh)" (4 teams)
UPDATE teams SET club_name = 'Oxford United Fc(Oh)' WHERE club_name = 'Oxford United FC(OH)' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "PCFC" → "Pcfc" (10 teams)
UPDATE teams SET club_name = 'Pcfc' WHERE club_name = 'PCFC' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "Pataskala Futbol Club Extreme (PFC Extreme)" → "Pataskala Futbol Club Extreme (Pfc Extreme)" (3 teams)
UPDATE teams SET club_name = 'Pataskala Futbol Club Extreme (Pfc Extreme)' WHERE club_name = 'Pataskala Futbol Club Extreme (PFC Extreme)' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "STAR Rush Cincinnati" → "Star Rush Cincinnati" (6 teams)
UPDATE teams SET club_name = 'Star Rush Cincinnati' WHERE club_name = 'STAR Rush Cincinnati' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "TFA CINCINNATI" → "Tfa Cincinnati" (4 teams)
UPDATE teams SET club_name = 'Tfa Cincinnati' WHERE club_name = 'TFA CINCINNATI' AND state_code = 'OH' AND gender = 'Female';

-- [VARIATION] "Toledo Celtics Soccer Club" → "Toledo Celtics" (2 teams)
UPDATE teams SET club_name = 'Toledo Celtics' WHERE club_name = 'Toledo Celtics Soccer Club' AND state_code = 'OH' AND gender = 'Female';

-- [CAPS] "UPPER 90 FC" → "Upper 90 FC" (1 teams)
UPDATE teams SET club_name = 'Upper 90 FC' WHERE club_name = 'UPPER 90 FC' AND state_code = 'OH' AND gender = 'Female';


-- === OK ===
-- [CAPS] "Choctaw SA (CNP)" → "Choctaw SA (Cnp)" (2 teams)
UPDATE teams SET club_name = 'Choctaw SA (Cnp)' WHERE club_name = 'Choctaw SA (CNP)' AND state_code = 'OK' AND gender = 'Female';

-- [VARIATION] "Edmond Soccer Club" → "Edmond SC" (3 teams)
UPDATE teams SET club_name = 'Edmond SC' WHERE club_name = 'Edmond Soccer Club' AND state_code = 'OK' AND gender = 'Female';

-- [VARIATION] "Lawton Soccer Club" → "Lawton SC" (1 teams)
UPDATE teams SET club_name = 'Lawton SC' WHERE club_name = 'Lawton Soccer Club' AND state_code = 'OK' AND gender = 'Female';

-- [VARIATION] "Midwest City Soccer Club" → "Midwest City SC" (4 teams)
UPDATE teams SET club_name = 'Midwest City SC' WHERE club_name = 'Midwest City Soccer Club' AND state_code = 'OK' AND gender = 'Female';

-- [CAPS] "NEOFC" → "Neofc" (8 teams)
UPDATE teams SET club_name = 'Neofc' WHERE club_name = 'NEOFC' AND state_code = 'OK' AND gender = 'Female';

-- [CAPS] "NEOFC Bartlesville" → "Neofc Bartlesville" (3 teams)
UPDATE teams SET club_name = 'Neofc Bartlesville' WHERE club_name = 'NEOFC Bartlesville' AND state_code = 'OK' AND gender = 'Female';

-- [VARIATION] "Tulsa SC" → "Tulsa Soccer Club" (17 teams)
UPDATE teams SET club_name = 'Tulsa Soccer Club' WHERE club_name = 'Tulsa SC' AND state_code = 'OK' AND gender = 'Female';

-- [VARIATION] "West Side Alliance" → "West Side Alliance SC" (36 teams)
UPDATE teams SET club_name = 'West Side Alliance SC' WHERE club_name = 'West Side Alliance' AND state_code = 'OK' AND gender = 'Female';


-- === OR ===
-- [VARIATION] "Capital Futbol Club" → "Capital FC" (6 teams)
UPDATE teams SET club_name = 'Capital FC' WHERE club_name = 'Capital Futbol Club' AND state_code = 'OR' AND gender = 'Female';

-- [CAPS] "Genesis FC (OR)" → "Genesis FC (Or)" (3 teams)
UPDATE teams SET club_name = 'Genesis FC (Or)' WHERE club_name = 'Genesis FC (OR)' AND state_code = 'OR' AND gender = 'Female';

-- [VARIATION] "Oregon Surf" → "Oregon Surf SC" (8 teams)
UPDATE teams SET club_name = 'Oregon Surf SC' WHERE club_name = 'Oregon Surf' AND state_code = 'OR' AND gender = 'Female';

-- [VARIATION] "Oregon United FC" → "Oregon Futbol Academy" (1 teams)
UPDATE teams SET club_name = 'Oregon Futbol Academy' WHERE club_name = 'Oregon United FC' AND state_code = 'OR' AND gender = 'Female';

-- [CAPS] "Pacific FC (OR)" → "Pacific FC (Or)" (1 teams)
UPDATE teams SET club_name = 'Pacific FC (Or)' WHERE club_name = 'Pacific FC (OR)' AND state_code = 'OR' AND gender = 'Female';

-- [CAPS] "Southeast Soccer Club (OR)" → "Southeast Soccer Club (Or)" (5 teams)
UPDATE teams SET club_name = 'Southeast Soccer Club (Or)' WHERE club_name = 'Southeast Soccer Club (OR)' AND state_code = 'OR' AND gender = 'Female';


-- === PA ===
-- [VARIATION] "Black Diamond FC" → "Black Diamond Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Black Diamond Soccer Club' WHERE club_name = 'Black Diamond FC' AND state_code = 'PA' AND gender = 'Female';

-- [CAPS] "Buckingham United Soccer Club (CBAA)" → "Buckingham United Soccer Club (Cbaa)" (9 teams)
UPDATE teams SET club_name = 'Buckingham United Soccer Club (Cbaa)' WHERE club_name = 'Buckingham United Soccer Club (CBAA)' AND state_code = 'PA' AND gender = 'Female';

-- [CAPS] "Dillsburg Area SC (DASC)" → "Dillsburg Area SC (Dasc)" (9 teams)
UPDATE teams SET club_name = 'Dillsburg Area SC (Dasc)' WHERE club_name = 'Dillsburg Area SC (DASC)' AND state_code = 'PA' AND gender = 'Female';

-- [CAPS] "ENCO United Soccer Club" → "Enco United Soccer Club" (10 teams)
UPDATE teams SET club_name = 'Enco United Soccer Club' WHERE club_name = 'ENCO United Soccer Club' AND state_code = 'PA' AND gender = 'Female';

-- [CAPS] "FC DELCO" → "FC Delco" (68 teams)
UPDATE teams SET club_name = 'FC Delco' WHERE club_name = 'FC DELCO' AND state_code = 'PA' AND gender = 'Female';

-- [CAPS] "Fusion FC (PA)" → "Fusion FC (Pa)" (6 teams)
UPDATE teams SET club_name = 'Fusion FC (Pa)' WHERE club_name = 'Fusion FC (PA)' AND state_code = 'PA' AND gender = 'Female';

-- [CAPS] "PA Classics Harrisburg (LDSA)" → "PA Classics Harrisburg (Ldsa)" (13 teams)
UPDATE teams SET club_name = 'PA Classics Harrisburg (Ldsa)' WHERE club_name = 'PA Classics Harrisburg (LDSA)' AND state_code = 'PA' AND gender = 'Female';

-- [VARIATION] "Penn Fusion SA" → "Penn Fusion Soccer Academy" (14 teams)
UPDATE teams SET club_name = 'Penn Fusion Soccer Academy' WHERE club_name = 'Penn Fusion SA' AND state_code = 'PA' AND gender = 'Female';

-- [VARIATION] "Springfield FC" → "Springfield SC" (13 teams)
UPDATE teams SET club_name = 'Springfield SC' WHERE club_name = 'Springfield FC' AND state_code = 'PA' AND gender = 'Female';

-- [VARIATION] "Warrington Soccer Club" → "Warrington SC" (1 teams)
UPDATE teams SET club_name = 'Warrington SC' WHERE club_name = 'Warrington Soccer Club' AND state_code = 'PA' AND gender = 'Female';


-- === RI ===
-- [CAPS] "BGYSA" → "Bgysa" (1 teams)
UPDATE teams SET club_name = 'Bgysa' WHERE club_name = 'BGYSA' AND state_code = 'RI' AND gender = 'Female';

-- [CAPS] "CLCF Soccer" → "Clcf Soccer" (7 teams)
UPDATE teams SET club_name = 'Clcf Soccer' WHERE club_name = 'CLCF Soccer' AND state_code = 'RI' AND gender = 'Female';

-- [CAPS] "CYSA - Cumberland Youth Soccer Association" → "Cysa - Cumberland Youth Soccer Association" (5 teams)
UPDATE teams SET club_name = 'Cysa - Cumberland Youth Soccer Association' WHERE club_name = 'CYSA - Cumberland Youth Soccer Association' AND state_code = 'RI' AND gender = 'Female';

-- [CAPS] "Coventry Soccer Association (CSA)" → "Coventry Soccer Association (Csa)" (2 teams)
UPDATE teams SET club_name = 'Coventry Soccer Association (Csa)' WHERE club_name = 'Coventry Soccer Association (CSA)' AND state_code = 'RI' AND gender = 'Female';

-- [CAPS] "MACH 1 FC" → "Mach 1 FC" (12 teams)
UPDATE teams SET club_name = 'Mach 1 FC' WHERE club_name = 'MACH 1 FC' AND state_code = 'RI' AND gender = 'Female';

-- [CAPS] "OSNK United" → "Osnk United" (6 teams)
UPDATE teams SET club_name = 'Osnk United' WHERE club_name = 'OSNK United' AND state_code = 'RI' AND gender = 'Female';

-- [CAPS] "RAMS FC" → "Rams FC" (10 teams)
UPDATE teams SET club_name = 'Rams FC' WHERE club_name = 'RAMS FC' AND state_code = 'RI' AND gender = 'Female';

-- [VARIATION] "Scorpions SC" → "Scorpions Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Scorpions Soccer Club' WHERE club_name = 'Scorpions SC' AND state_code = 'RI' AND gender = 'Female';


-- === SC ===
-- [CAPS] "Augusta Arsenal SC (GA)" → "Augusta Arsenal SC (Ga)" (4 teams)
UPDATE teams SET club_name = 'Augusta Arsenal SC (Ga)' WHERE club_name = 'Augusta Arsenal SC (GA)' AND state_code = 'SC' AND gender = 'Female';

-- [CAPS] "Augusta Arsenal SC (SC)" → "Augusta Arsenal SC (Sc)" (5 teams)
UPDATE teams SET club_name = 'Augusta Arsenal SC (Sc)' WHERE club_name = 'Augusta Arsenal SC (SC)' AND state_code = 'SC' AND gender = 'Female';

-- [VARIATION] "Charleston United SC" → "Charleston Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Charleston Soccer Club' WHERE club_name = 'Charleston United SC' AND state_code = 'SC' AND gender = 'Female';

-- [VARIATION] "Charlotte Independence Soccer Club" → "Charlotte Independence SC" (1 teams)
UPDATE teams SET club_name = 'Charlotte Independence SC' WHERE club_name = 'Charlotte Independence Soccer Club' AND state_code = 'SC' AND gender = 'Female';

-- [VARIATION] "South Carolina Surf" → "South Carolina Surf SC" (6 teams)
UPDATE teams SET club_name = 'South Carolina Surf SC' WHERE club_name = 'South Carolina Surf' AND state_code = 'SC' AND gender = 'Female';

-- [VARIATION] "South Carolina United" → "South Carolina United FC" (13 teams)
UPDATE teams SET club_name = 'South Carolina United FC' WHERE club_name = 'South Carolina United' AND state_code = 'SC' AND gender = 'Female';


-- === SD ===
-- [CAPS] "DASC" → "Dasc" (28 teams)
UPDATE teams SET club_name = 'Dasc' WHERE club_name = 'DASC' AND state_code = 'SD' AND gender = 'Female';


-- === TN ===
-- [CAPS] "JCFC Academy" → "Jcfc Academy" (1 teams)
UPDATE teams SET club_name = 'Jcfc Academy' WHERE club_name = 'JCFC Academy' AND state_code = 'TN' AND gender = 'Female';

-- [CAPS] "Jackson SC(TN)" → "Jackson Sc(Tn)" (18 teams)
UPDATE teams SET club_name = 'Jackson Sc(Tn)' WHERE club_name = 'Jackson SC(TN)' AND state_code = 'TN' AND gender = 'Female';

-- [VARIATION] "Nashville FC" → "Nashville United Soccer Academy" (1 teams)
UPDATE teams SET club_name = 'Nashville United Soccer Academy' WHERE club_name = 'Nashville FC' AND state_code = 'TN' AND gender = 'Female';

-- [VARIATION] "TENNESSEE SOCCER ACADEMY" → "Tennessee SC" (8 teams)
UPDATE teams SET club_name = 'Tennessee SC' WHERE club_name = 'TENNESSEE SOCCER ACADEMY' AND state_code = 'TN' AND gender = 'Female';

-- [VARIATION] "Tennessee Soccer Club" → "Tennessee SC" (18 teams)
UPDATE teams SET club_name = 'Tennessee SC' WHERE club_name = 'Tennessee Soccer Club' AND state_code = 'TN' AND gender = 'Female';

-- [VARIATION] "Tennessee United" → "Tennessee SC" (2 teams)
UPDATE teams SET club_name = 'Tennessee SC' WHERE club_name = 'Tennessee United' AND state_code = 'TN' AND gender = 'Female';

-- [VARIATION] "Tennessee United SC" → "Tennessee SC" (28 teams)
UPDATE teams SET club_name = 'Tennessee SC' WHERE club_name = 'Tennessee United SC' AND state_code = 'TN' AND gender = 'Female';


-- === TX ===
-- [CAPS] "903FC" → "903Fc" (2 teams)
UPDATE teams SET club_name = '903Fc' WHERE club_name = '903FC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "BAYOU CITY LOBOS" → "Bayou City Lobos" (1 teams)
UPDATE teams SET club_name = 'Bayou City Lobos' WHERE club_name = 'BAYOU CITY LOBOS' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "Boerne Soccer Club" → "Boerne SC" (3 teams)
UPDATE teams SET club_name = 'Boerne SC' WHERE club_name = 'Boerne Soccer Club' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "Brownsville Opportunity Youth Soccer Association (BOYSA)" → "Brownsville Opportunity Youth Soccer Association (Boysa)" (6 teams)
UPDATE teams SET club_name = 'Brownsville Opportunity Youth Soccer Association (Boysa)' WHERE club_name = 'Brownsville Opportunity Youth Soccer Association (BOYSA)' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "Dallas Cosmos SC" → "Dallas Cosmos Soccer Club" (4 teams)
UPDATE teams SET club_name = 'Dallas Cosmos Soccer Club' WHERE club_name = 'Dallas Cosmos SC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "Dripping Springs Soccer DSYSA" → "Dripping Springs Soccer Dsysa" (7 teams)
UPDATE teams SET club_name = 'Dripping Springs Soccer Dsysa' WHERE club_name = 'Dripping Springs Soccer DSYSA' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "EL PASO COSMOS FC" → "El Paso Cosmos FC" (5 teams)
UPDATE teams SET club_name = 'El Paso Cosmos FC' WHERE club_name = 'EL PASO COSMOS FC' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "East Texas SC" → "East Texas United SC" (1 teams)
UPDATE teams SET club_name = 'East Texas United SC' WHERE club_name = 'East Texas SC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "FAIRFIELD FC" → "Fairfield FC" (4 teams)
UPDATE teams SET club_name = 'Fairfield FC' WHERE club_name = 'FAIRFIELD FC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "FC Blitz (TX)" → "FC Blitz (Tx)" (1 teams)
UPDATE teams SET club_name = 'FC Blitz (Tx)' WHERE club_name = 'FC Blitz (TX)' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "FCTR Events" → "Fctr Events" (1 teams)
UPDATE teams SET club_name = 'Fctr Events' WHERE club_name = 'FCTR Events' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "FIERCE United" → "Fierce United" (15 teams)
UPDATE teams SET club_name = 'Fierce United' WHERE club_name = 'FIERCE United' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "FLAME FC" → "Flame FC" (2 teams)
UPDATE teams SET club_name = 'Flame FC' WHERE club_name = 'FLAME FC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "FWYSA" → "Fwysa" (3 teams)
UPDATE teams SET club_name = 'Fwysa' WHERE club_name = 'FWYSA' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "GLASA" → "Glasa" (6 teams)
UPDATE teams SET club_name = 'Glasa' WHERE club_name = 'GLASA' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "GLASA LEAGUE TEAM" → "Glasa League Team" (1 teams)
UPDATE teams SET club_name = 'Glasa League Team' WHERE club_name = 'GLASA LEAGUE TEAM' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "HPSA Scots" → "Hpsa Scots" (8 teams)
UPDATE teams SET club_name = 'Hpsa Scots' WHERE club_name = 'HPSA Scots' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "Houstonians FC" → "Houstonians Futbol Club" (5 teams)
UPDATE teams SET club_name = 'Houstonians Futbol Club' WHERE club_name = 'Houstonians FC' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "Irving Elite Soccer Academy" → "Irving Elite FC" (1 teams)
UPDATE teams SET club_name = 'Irving Elite FC' WHERE club_name = 'Irving Elite Soccer Academy' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "Juventus Academy Houston (JA)" → "Juventus Academy Houston (Ja)" (1 teams)
UPDATE teams SET club_name = 'Juventus Academy Houston (Ja)' WHERE club_name = 'Juventus Academy Houston (JA)' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "Juventus Premier  FC" → "Juventus Premier Futbol Club" (2 teams)
UPDATE teams SET club_name = 'Juventus Premier Futbol Club' WHERE club_name = 'Juventus Premier  FC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "LALIGA ACADEMY Dallas" → "Laliga Academy Dallas" (2 teams)
UPDATE teams SET club_name = 'Laliga Academy Dallas' WHERE club_name = 'LALIGA ACADEMY Dallas' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "LTFC" → "Ltfc" (35 teams)
UPDATE teams SET club_name = 'Ltfc' WHERE club_name = 'LTFC' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "Legacy United FC" → "Legacy FC" (2 teams)
UPDATE teams SET club_name = 'Legacy FC' WHERE club_name = 'Legacy United FC' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "Lonestar Soccer Club" → "Lonestar" (45 teams)
UPDATE teams SET club_name = 'Lonestar' WHERE club_name = 'Lonestar Soccer Club' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "MAFC" → "Mafc" (5 teams)
UPDATE teams SET club_name = 'Mafc' WHERE club_name = 'MAFC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "MCYSO Runners" → "Mcyso Runners" (3 teams)
UPDATE teams SET club_name = 'Mcyso Runners' WHERE club_name = 'MCYSO Runners' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "MOJO FC" → "Mojo FC" (1 teams)
UPDATE teams SET club_name = 'Mojo FC' WHERE club_name = 'MOJO FC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "MYSA" → "Mysa" (4 teams)
UPDATE teams SET club_name = 'Mysa' WHERE club_name = 'MYSA' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "Mansfield SA" → "Mansfield FC" (1 teams)
UPDATE teams SET club_name = 'Mansfield FC' WHERE club_name = 'Mansfield SA' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "NTX UNITED FC" → "NTX United FC" (1 teams)
UPDATE teams SET club_name = 'NTX United FC' WHERE club_name = 'NTX UNITED FC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "PAYD FC" → "Payd FC" (1 teams)
UPDATE teams SET club_name = 'Payd FC' WHERE club_name = 'PAYD FC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "Pflugerville AYSL" → "Pflugerville Aysl" (20 teams)
UPDATE teams SET club_name = 'Pflugerville Aysl' WHERE club_name = 'Pflugerville AYSL' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "RISE SC" → "Rise SC" (21 teams)
UPDATE teams SET club_name = 'Rise SC' WHERE club_name = 'RISE SC' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "RISE Soccer Club" → "Rise SC" (17 teams)
UPDATE teams SET club_name = 'Rise SC' WHERE club_name = 'RISE Soccer Club' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "SA United" → "SA United Soccer Club" (3 teams)
UPDATE teams SET club_name = 'SA United Soccer Club' WHERE club_name = 'SA United' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "SEABREEZE YOUTH SOCCER" → "Seabreeze Youth Soccer" (2 teams)
UPDATE teams SET club_name = 'Seabreeze Youth Soccer' WHERE club_name = 'SEABREEZE YOUTH SOCCER' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "SG1 Soccer" → "SG1" (18 teams)
UPDATE teams SET club_name = 'SG1' WHERE club_name = 'SG1 Soccer' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "Scorpions (TX)" → "Scorpions (Tx)" (1 teams)
UPDATE teams SET club_name = 'Scorpions (Tx)' WHERE club_name = 'Scorpions (TX)' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "Solar Soccer Club" → "Solar SC" (52 teams)
UPDATE teams SET club_name = 'Solar SC' WHERE club_name = 'Solar Soccer Club' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "TOKA FUTBOL CLUB" → "Toka Futbol Club" (1 teams)
UPDATE teams SET club_name = 'Toka Futbol Club' WHERE club_name = 'TOKA FUTBOL CLUB' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "TXMAMBAS Soccer Club" → "Txmambas Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Txmambas Soccer Club' WHERE club_name = 'TXMAMBAS Soccer Club' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "The ACDMY" → "The Acdmy" (2 teams)
UPDATE teams SET club_name = 'The Acdmy' WHERE club_name = 'The ACDMY' AND state_code = 'TX' AND gender = 'Female';

-- [VARIATION] "Tyler FC" → "Tyler SA" (3 teams)
UPDATE teams SET club_name = 'Tyler SA' WHERE club_name = 'Tyler FC' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "USYS Cups" → "Usys Cups" (1 teams)
UPDATE teams SET club_name = 'Usys Cups' WHERE club_name = 'USYS Cups' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "WDDOA" → "Wddoa" (2 teams)
UPDATE teams SET club_name = 'Wddoa' WHERE club_name = 'WDDOA' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "WTX ROYALTY" → "Wtx Royalty" (1 teams)
UPDATE teams SET club_name = 'Wtx Royalty' WHERE club_name = 'WTX ROYALTY' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "Warriors FC (TX) U11 Girls" → "Warriors FC (Tx) U11 Girls" (1 teams)
UPDATE teams SET club_name = 'Warriors FC (Tx) U11 Girls' WHERE club_name = 'Warriors FC (TX) U11 Girls' AND state_code = 'TX' AND gender = 'Female';

-- [CAPS] "YMCA CTX Soccer Academy" → "Ymca Ctx Soccer Academy" (2 teams)
UPDATE teams SET club_name = 'Ymca Ctx Soccer Academy' WHERE club_name = 'YMCA CTX Soccer Academy' AND state_code = 'TX' AND gender = 'Female';


-- === UT ===
-- [CAPS] "AYSO UNITED" → "AYSO United" (5 teams)
UPDATE teams SET club_name = 'AYSO United' WHERE club_name = 'AYSO UNITED' AND state_code = 'UT' AND gender = 'Female';

-- [CAPS] "Avalanche SL/DW" → "Avalanche Sl/Dw" (1 teams)
UPDATE teams SET club_name = 'Avalanche Sl/Dw' WHERE club_name = 'Avalanche SL/DW' AND state_code = 'UT' AND gender = 'Female';

-- [VARIATION] "Colorado Elevation FC" → "Colorado Elevation" (1 teams)
UPDATE teams SET club_name = 'Colorado Elevation' WHERE club_name = 'Colorado Elevation FC' AND state_code = 'UT' AND gender = 'Female';

-- [CAPS] "Elite FC (UT)" → "Elite FC (Ut)" (3 teams)
UPDATE teams SET club_name = 'Elite FC (Ut)' WHERE club_name = 'Elite FC (UT)' AND state_code = 'UT' AND gender = 'Female';

-- [VARIATION] "Ignite" → "Ignite FC" (1 teams)
UPDATE teams SET club_name = 'Ignite FC' WHERE club_name = 'Ignite' AND state_code = 'UT' AND gender = 'Female';

-- [VARIATION] "Impact United" → "Impact United SC" (1 teams)
UPDATE teams SET club_name = 'Impact United SC' WHERE club_name = 'Impact United' AND state_code = 'UT' AND gender = 'Female';

-- [VARIATION] "La Roca" → "La Roca FC" (16 teams)
UPDATE teams SET club_name = 'La Roca FC' WHERE club_name = 'La Roca' AND state_code = 'UT' AND gender = 'Female';

-- [CAPS] "SWAT SC" → "Swat SC" (2 teams)
UPDATE teams SET club_name = 'Swat SC' WHERE club_name = 'SWAT SC' AND state_code = 'UT' AND gender = 'Female';

-- [VARIATION] "SWAT Soccer" → "Swat SC" (2 teams)
UPDATE teams SET club_name = 'Swat SC' WHERE club_name = 'SWAT Soccer' AND state_code = 'UT' AND gender = 'Female';

-- [CAPS] "St George FC (UT)" → "St George FC (Ut)" (4 teams)
UPDATE teams SET club_name = 'St George FC (Ut)' WHERE club_name = 'St George FC (UT)' AND state_code = 'UT' AND gender = 'Female';

-- [VARIATION] "Strikers SC" → "Strikers FC" (1 teams)
UPDATE teams SET club_name = 'Strikers FC' WHERE club_name = 'Strikers SC' AND state_code = 'UT' AND gender = 'Female';

-- [VARIATION] "Utah Celtic FC" → "Utah Celtic" (1 teams)
UPDATE teams SET club_name = 'Utah Celtic' WHERE club_name = 'Utah Celtic FC' AND state_code = 'UT' AND gender = 'Female';

-- [CAPS] "Utah County Soccer Club (UCSC)" → "Utah County Soccer Club (Ucsc)" (7 teams)
UPDATE teams SET club_name = 'Utah County Soccer Club (Ucsc)' WHERE club_name = 'Utah County Soccer Club (UCSC)' AND state_code = 'UT' AND gender = 'Female';

-- [VARIATION] "Utah Surf Soccer" → "Utah Surf" (9 teams)
UPDATE teams SET club_name = 'Utah Surf' WHERE club_name = 'Utah Surf Soccer' AND state_code = 'UT' AND gender = 'Female';


-- === VA ===
-- [CAPS] "Beach FC  (VA)" → "Beach FC (Va)" (12 teams)
UPDATE teams SET club_name = 'Beach FC (Va)' WHERE club_name = 'Beach FC  (VA)' AND state_code = 'VA' AND gender = 'Female';

-- [VARIATION] "Chesapeake SC" → "Chesapeake United SC" (1 teams)
UPDATE teams SET club_name = 'Chesapeake United SC' WHERE club_name = 'Chesapeake SC' AND state_code = 'VA' AND gender = 'Female';

-- [VARIATION] "Chesapeake Soccer Club" → "Chesapeake United SC" (5 teams)
UPDATE teams SET club_name = 'Chesapeake United SC' WHERE club_name = 'Chesapeake Soccer Club' AND state_code = 'VA' AND gender = 'Female';

-- [VARIATION] "Fredericksburg Soccer Club" → "Fredericksburg FC" (5 teams)
UPDATE teams SET club_name = 'Fredericksburg FC' WHERE club_name = 'Fredericksburg Soccer Club' AND state_code = 'VA' AND gender = 'Female';

-- [CAPS] "LMVSC" → "Lmvsc" (6 teams)
UPDATE teams SET club_name = 'Lmvsc' WHERE club_name = 'LMVSC' AND state_code = 'VA' AND gender = 'Female';

-- [CAPS] "NVSC" → "Nvsc" (6 teams)
UPDATE teams SET club_name = 'Nvsc' WHERE club_name = 'NVSC' AND state_code = 'VA' AND gender = 'Female';

-- [CAPS] "Old Dominion Football Club (ODFC)" → "Old Dominion Football Club (Odfc)" (4 teams)
UPDATE teams SET club_name = 'Old Dominion Football Club (Odfc)' WHERE club_name = 'Old Dominion Football Club (ODFC)' AND state_code = 'VA' AND gender = 'Female';

-- [CAPS] "Old Dominion Soccer Club (ODSC)" → "Old Dominion Soccer Club (Odsc)" (3 teams)
UPDATE teams SET club_name = 'Old Dominion Soccer Club (Odsc)' WHERE club_name = 'Old Dominion Soccer Club (ODSC)' AND state_code = 'VA' AND gender = 'Female';

-- [CAPS] "PWSI Courage" → "Pwsi Courage" (9 teams)
UPDATE teams SET club_name = 'Pwsi Courage' WHERE club_name = 'PWSI Courage' AND state_code = 'VA' AND gender = 'Female';


-- === WA ===
-- [CAPS] "BVBIA WA - Seattle" → "Bvbia WA - Seattle" (2 teams)
UPDATE teams SET club_name = 'Bvbia WA - Seattle' WHERE club_name = 'BVBIA WA - Seattle' AND state_code = 'WA' AND gender = 'Female';

-- [CAPS] "CYSA Timber Barons" → "Cysa Timber Barons" (5 teams)
UPDATE teams SET club_name = 'Cysa Timber Barons' WHERE club_name = 'CYSA Timber Barons' AND state_code = 'WA' AND gender = 'Female';

-- [CAPS] "Eastside FC (WA)" → "Eastside FC (Wa)" (25 teams)
UPDATE teams SET club_name = 'Eastside FC (Wa)' WHERE club_name = 'Eastside FC (WA)' AND state_code = 'WA' AND gender = 'Female';

-- [CAPS] "NPSA" → "Npsa" (44 teams)
UPDATE teams SET club_name = 'Npsa' WHERE club_name = 'NPSA' AND state_code = 'WA' AND gender = 'Female';

-- [CAPS] "NWSC" → "Nwsc" (2 teams)
UPDATE teams SET club_name = 'Nwsc' WHERE club_name = 'NWSC' AND state_code = 'WA' AND gender = 'Female';

-- [CAPS] "PUMAS-UNAM Filial Seattle" → "Pumas-Unam Filial Seattle" (1 teams)
UPDATE teams SET club_name = 'Pumas-Unam Filial Seattle' WHERE club_name = 'PUMAS-UNAM Filial Seattle' AND state_code = 'WA' AND gender = 'Female';

-- [CAPS] "USYS Cups" → "Usys Cups" (1 teams)
UPDATE teams SET club_name = 'Usys Cups' WHERE club_name = 'USYS Cups' AND state_code = 'WA' AND gender = 'Female';

-- [VARIATION] "Washington Premier FC" → "Washington Premier" (33 teams)
UPDATE teams SET club_name = 'Washington Premier' WHERE club_name = 'Washington Premier FC' AND state_code = 'WA' AND gender = 'Female';

-- [VARIATION] "Wenatchee United SC" → "Wenatchee FC" (5 teams)
UPDATE teams SET club_name = 'Wenatchee FC' WHERE club_name = 'Wenatchee United SC' AND state_code = 'WA' AND gender = 'Female';


-- === WI ===
-- [VARIATION] "Lodi FC" → "Lodi Soccer Club" (1 teams)
UPDATE teams SET club_name = 'Lodi Soccer Club' WHERE club_name = 'Lodi FC' AND state_code = 'WI' AND gender = 'Female';

-- [CAPS] "Portage County Youth Soccer (PCYS)" → "Portage County Youth Soccer (Pcys)" (5 teams)
UPDATE teams SET club_name = 'Portage County Youth Soccer (Pcys)' WHERE club_name = 'Portage County Youth Soccer (PCYS)' AND state_code = 'WI' AND gender = 'Female';

-- [CAPS] "RUSH WI Southeast" → "Rush WI Southeast" (4 teams)
UPDATE teams SET club_name = 'Rush WI Southeast' WHERE club_name = 'RUSH WI Southeast' AND state_code = 'WI' AND gender = 'Female';

-- [CAPS] "RUSH Wisconsin" → "Rush Wisconsin" (11 teams)
UPDATE teams SET club_name = 'Rush Wisconsin' WHERE club_name = 'RUSH Wisconsin' AND state_code = 'WI' AND gender = 'Female';

-- [CAPS] "RUSH Wisconsin West" → "Rush Wisconsin West" (9 teams)
UPDATE teams SET club_name = 'Rush Wisconsin West' WHERE club_name = 'RUSH Wisconsin West' AND state_code = 'WI' AND gender = 'Female';

-- [VARIATION] "Verona SC" → "Verona Soccer Club" (2 teams)
UPDATE teams SET club_name = 'Verona Soccer Club' WHERE club_name = 'Verona SC' AND state_code = 'WI' AND gender = 'Female';


-- === WV ===
-- [CAPS] "EPIC SC" → "Epic SC" (7 teams)
UPDATE teams SET club_name = 'Epic SC' WHERE club_name = 'EPIC SC' AND state_code = 'WV' AND gender = 'Female';

-- [CAPS] "KVSL-WEST SIDE SOCCER CLUB" → "Kvsl-West Side Soccer Club" (3 teams)
UPDATE teams SET club_name = 'Kvsl-West Side Soccer Club' WHERE club_name = 'KVSL-WEST SIDE SOCCER CLUB' AND state_code = 'WV' AND gender = 'Female';

-- [VARIATION] "West Virginia Soccer" → "West Virginia Futbol Club" (2 teams)
UPDATE teams SET club_name = 'West Virginia Futbol Club' WHERE club_name = 'West Virginia Soccer' AND state_code = 'WV' AND gender = 'Female';


COMMIT;

-- Summary: 498 fixes, 3927 teams affected